### ISSUE TITLE
cmdstan random seed not reading correctly (seems like a 32bit thing?)

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstan#1003]
#### Summary:

I ran a model and it gave me as output:

```
data
  file = lv.json
init = 2 (Default)
random
  seed = 2431820427
```

And then I tried to run it again with: 
```
./lv sample data file=lv.json random seed=2431820427
```

And I got:
```
2431820427 is not a valid value for "seed"
  Valid values: integer >= 0 or -1 to generate seed from system time
Failed to parse command arguments, cannot run model.
```

2^31 = 2147483648

I assume somewhere in the I/O we're reading this as a signed 32 bit int and it should be unsigned 32 bit.

#### Current Version:
v2.26.1

**Comment by mitzimorris** [comment]
just to check, running this from the cmd line, not via a CmdStanX wrapper?

**Comment by bbbales2** [comment]
Yeah command line

**Comment by bbbales2** [comment]
Oh and I just noticed -1 is apparently a valid argument so I guess we need to read in a 64bit signed int to cover everything.
