### ISSUE TITLE
`generate_quantities` handles `save_warmup=True` "wrong". 

### ISSUE THREAD

**Issue by funko-unko** [stan-dev/cmdstan#1011]
#### Summary:

If `save_warmup=True`, `generate_quantities` takes the first `num_samples` warmup and samples to generate the gqs. 

https://github.com/stan-dev/cmdstan/blob/develop/src/cmdstan/command.hpp
```c++
    size_t num_cols = param_names.size();
    size_t num_rows = fitted_params.metadata.num_samples;
    // check that all parameter names are in sample, in order
    if (num_cols + hmc_fixed_cols > fitted_params.header.size()) {
      msg << "Mismatch between model and fitted_parameters csv file \"" << fname
          << "\"" << std::endl;
      throw std::invalid_argument(msg.str());
    }
    for (size_t i = 0; i < num_cols; ++i) {
      if (param_names[i].compare(fitted_params.header[i + hmc_fixed_cols])
          != 0) {
        msg << "Mismatch between model and fitted_parameters csv file \""
            << fname << "\"" << std::endl;
        throw std::invalid_argument(msg.str());
      }
    }
    return_code = stan::services::standalone_generate(
        model,
        fitted_params.samples.block(0, hmc_fixed_cols, num_rows, num_cols),
        random_seed, interrupt, logger, sample_writer);
```
Has to be changed into something that handles this differently, also incorporating the thinning parameter.

#### Current Version:
v2.26.1

**Comment by funko-unko** [comment]
Also, here is an MWE:

**Stan**
```stan
parameters {
  real x;
}
model {
  x ~ normal(0,1);
}
generated quantities{
  real y = x;
}
```
**Python**
```python
import cmdstanpy

model = cmdstanpy.CmdStanModel(stan_file='gq.stan')
fit = model.sample(save_warmup=True, iter_sampling=1, chains=1)
gq = model.generate_quantities(dict(), fit)
print(gq.sample_plus_quantities[['x', 'y']])
```

**Output**
```
          x         y
0 -0.330773  0.362201


```

**Comment by mitzimorris** [comment]
> CmdStan just takes the first `num_samples` draws from the output `csv` amd runs the gq block. If the fit was generated with `save_warmup=True`, these may turn out to only be warmup samples.

not quite.  CmdStan takes the `fitted_params` csv file and hands that off to the `generate_quantities` service method.  however many draws there are in that csv file, that's the new set of outputs.  (I implemented this feature and added it to CmdStan - I just checked the code, and nothing seems to have been changed).

I'll check on what CmdStanPy is doing - it sounds like that's where add'l config is needed.

**Comment by mitzimorris** [comment]
if you look at the code - line 285 is going to advance the stream reader to the adaptation message - past warmup samples.  then line 289 reads the post-warmup draws.

**Comment by funko-unko** [comment]
Slightly extended MWE from above, same Stan file

```python
import cmdstanpy

model = cmdstanpy.CmdStanModel(stan_file='gq.stan')
fit = model.sample(save_warmup=True, iter_sampling=1, chains=1)
print(fit.draws_pd(inc_warmup=True)['x'])
gq = model.generate_quantities(dict(), fit)
print(gq.sample_plus_quantities[['x', 'y']])
```
Output:
```
0      -0.543328
1      -0.177736
2      -0.177736
3      -1.121910
4      -1.329880
          ...   
996    -0.850899
997    -0.799468
998    -0.616761
999    -0.483609
1000   -1.144480
Name: x, Length: 1001, dtype: float64
         x         y
0 -1.14448 -0.543328
```

Maybe some version is out of date, let me check.

**Comment by funko-unko** [comment]
Ah. I had a mini heart attack. I changed the cmdstanpath to use the version that I downloaded from github, and suddenly it worked. So I thought I was wrong and wasted your time, **but actually** I already fixed the bug in my CmdStan code.

This is the header of my csv file, does this confirm that everything is up to date?

```
# stan_version_major = 2
# stan_version_minor = 26
# stan_version_patch = 1
# model = gq_model
# method = generate_quantities
#   generate_quantities
#     fitted_params = /tmp/tmp9ocuyis7/gq-202105112050-1-dkj8s3x5.csv
# id = 1
# data
#   file = /tmp/tmp9ocuyis7/oinkjs25.json
# init = 2 (Default)
# random
#   seed = 66815
# output
#   file = /tmp/tmp9ocuyis7/gq-202105112050-1-kybspozc.csv
#   diagnostic_file =  (Default)
#   refresh = 100 (Default)
#   sig_figs = -1 (Default)
#   profile_file = profile.csv (Default)
# stanc_version = stanc3 7de91659
# stancflags = 
```

**Comment by mitzimorris** [comment]
this is fubar and you are right.  eating words.

in CmdStan 2.26.1:

```
> ./examples/bernoulli/bernoulli sample algorithm=hmc save_warmup=1 output file=fp.csv data file=examples/bernoulli/bernoulli.data.json 
```

model b2.stan:

```
data {
  int<lower=0> N;
  int<lower=0,upper=1> y[N];
}
parameters {
  real<lower=0,upper=1> theta;
}
model {
  theta ~ beta(1,1);  // uniform prior on interval 0,1
  y ~ bernoulli(theta);
}
generated quantities {
  real theta_copy = theta;
}
```
and run this with file `fp.csv` as the `fitted_params` arg:

```
./examples/bernoulli/b2 generate_quantities fitted_params=fp.csv output file=gq.csv data file=examples/bernoulli/bernoulli.data.json 
```

simple sanity check:

```
wc -l *.csv
    2052 fp.csv
    1022 gq.csv
```

so far so good, _but_ - first draw of `fp.csv`, which is warmup: 

```
lp__,accept_stat__,stepsize__,treedepth__,n_leapfrog__,divergent__,energy__,theta
-13.2719,0.0211121,1,1,3,0,15.5608,0.747871
```

first draw of `gq.csv`:

```
theta_copy
0.747871
```

looks like the Stan csv reader isn't doing what it should be doing.   will investigate.



```

**Comment by mitzimorris** [comment]
many thanks. probably never properly unit tested.  will fix.  (but have to write grant proposal first) - you're welcome to - the question is - why doesn't `read_adaptation` advance the stream reader properly?  in other words, wtf?

**Comment by mitzimorris** [comment]
answer to above question:  `stan::io::stan_csv_reader::read_samples` isn't doing what I though it was.
it reads from the beginning of the file and assembles all draws into the Eigen Xd matrix.
the metadata has fields `num_warmup`, `save_warmup`, and `num_samples`.

therefore, two options:

a) use all draws
b) add argument to flag whether or not to use warmup draws.

a) is a whole lot easier.  given that by default, warmup draws are not saved, if warmup draws are present, then that's a deliberate choice, and standalone GQ should use all draws.

**Comment by mitzimorris** [comment]
> Ie reading of the adaptation does not seem to work when warmup draws have been saved. But I have made no tests and my understanding is very shallow.

it's not your understanding that's shallow - it's the code.  no comments.  haven't checked out the unit tests - probably not enough of them, either.

**Comment by mitzimorris** [comment]
going with option a) then, draws in the `fitted_params` csv file will be used, all of them.
CmdStanPy will have to document this, and could also print info message to user that warmup draws are present.

if CmdStanPy wants to get fancier, it could - I suggest we don't and push back on Python users to do their own data munghing.

**Comment by funko-unko** [comment]
Yes, I would not want to deal with data wrangling in C...
