### ISSUE TITLE
Feature request: rows_dot_product( row_vector [] , matrix )

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/cmdstan#1015]
When doing hierarchical models, [it can be useful to use rows_dot_product](https://discourse.mc-stan.org/t/rows-dot-product-is-intended-as-a-shorthand-rather-than-compute-optimization-right/20798) before the final likelihood, but in models with "centered-parameterization" the first term will typically be an array of row_vectors, so a conversion is currently necessary:

```stan
data{
...
  matrix[n,k] w_n[k]
...
}
...
parameters{
...
  row_vector[k] m ;
  vector<lower=0>[k] s ;
  row_vector[k] z[n] ;
  cholesky_factor_corr[k] r ;
...
}
model{
...
  // z as multivariate normal ("centered" parameterization)
  z ~ multi_normal_cholesky( m , diag_pre_multiply(s,r) ) ;

  //convert z from array of row-vectors to matrix
  matrix[n,k] z_mat ;
  for(i_n in 1:n){
    z_mat[i_n] = z[i_n] ;
  }

  // Loop to compute the loc for each subject in each condition implied by the design matrix
  matrix[n,k] loc ;
  for(i_k in 1:k){
    loc[,i_k] = rows_dot_product( z_mat , w_n[i_k]  ) ;
  }
...
}

```

**Comment by t4c1** [comment]
I think you can simplify this into computing rowwise sum of `w_n` before `elt_multiply`ing it with `z`, so there is no need to construct `z_mat`. It should also be a bit faster.

**Comment by mike-lawrence** [comment]
Is `elt_multiply` exposed in Stan? I see it's in the math library but not in the Stan functions reference.

**Comment by nhuurre** [comment]
It is but it's called .* and not elt_multiply
https://mc-stan.org/docs/2_26/functions-reference/elementwise-functions.html

**Comment by mike-lawrence** [comment]
Oh! I just realized I failed to include the description that `w_n` is an array of matrices, so `w_n[i_k]` is itself a matrix, hence working when the other argument to `rows_dot_product` is also a matrix. I think that @t4c1 your suggestion was based on assuming that `w_n[i_k]` was a row vector and not a matrix? Because I otherwise don't understand your suggestion, as (and writing this out in detail mostly to check my own understanding):

```stan
vector[num_rows_mn] o = rows_dot_product( m, n) ;
```

is equal to 

```stan
vector[num_rows_mn] o ;
for(i in 1:num_rows_mn){
  o[i] = dot_product(m[i], n[i] ) ;
}
```

which is equal to 

```stan
vector[num_rows_mn] o ;
for(i in 1:num_rows_mn){
  o[i] = sum( m[i] .* n[i] ) ;
}
```

where the sum and multiply operations aren't commutative, so one can't do:

```stan
vector[num_rows_mn] o ;
for(i in 1:num_rows_mn){
  o[i] = sum(m[i])  * sum(n[i]) ;
}
```

Or have I completely missed your intent?

**Comment by mike-lawrence** [comment]
Oh wait. I don't even have my own example right.

**Comment by t4c1** [comment]
No, I misunderstood. I missed that `z` is an array. Than the conversion is necessary. In math we have a `to_matrix` signature that could do the conversion for you, but it looks like it is not exposed to the language.

**Comment by mike-lawrence** [comment]
Moving this to a [new issue at stanc3](https://github.com/stan-dev/stanc3/issues/928).
