### ISSUE TITLE
Release 2.27.0 is unavailable from URL

### ISSUE THREAD

**Issue by ParthivNaresh** [stan-dev/cmdstan#1020]
#### Summary:
After the new release, `install_cmdstan.py` within the `cmdstanpy` package is unable to install `cmdstan-2.27.0.tar.gz`. I believe that the artifacts created on GitHub with the latest release are only archived:

<img width="631" alt="Screen Shot 2021-06-02 at 3 51 10 PM" src="https://user-images.githubusercontent.com/29577911/120543613-7fc6cb00-c3ba-11eb-9512-7f5f19eb857a.png">

as opposed to the previous releases:

<img width="631" alt="Screen Shot 2021-06-02 at 3 51 43 PM" src="https://user-images.githubusercontent.com/29577911/120543629-83f2e880-c3ba-11eb-859b-eb3ac1f6bda5.png">

When this command is run 

```
pip install cmdstanpy==0.9.68
python "../site-packages/cmdstanpy/install_cmdstan.py" -d "../site-packages/"
```

within `install_cmdstan.py`:

```
try:
     urllib.request.urlopen(url)
except urllib.error.HTTPError as err:
     print('Release {} is unavailable from URL {}'.format(version, url))
     print('HTTPError: {}'.format(err.code))
     is_available = False
     break
```

results in this output:

```
Release 2.27.0 is unavailable from URL https://github.com/stan-dev/cmdstan/releases/download/v2.27.0/cmdstan-2.27.0.tar.gz
HTTPError: 404
```

Perhaps this should be posted in the `cmdstanpy` project, but my initial reaction was wondering if a non-archived artifact would be built from this repo for the latest release.

**Comment by rok-cesnovar** [comment]
Hi, it will be built shortly. Apologize for the inconvenince. 

@serban-nicusor-toptal  lets tag it as pre-release untill we have the tarball

**Comment by serban-nicusor-toptal** [comment]
Hey, everything should be ready to go now.

**Comment by rok-cesnovar** [comment]
Thanks!
