### ISSUE TITLE
Allow any CSV of parameters to be passed to generate_quantities

### ISSUE THREAD

**Issue by somebody-cool** [stan-dev/cmdstan#1028]
#### Summary:
Seems related to https://github.com/stan-dev/stan/issues/2968 but I can't tell where y'all landed on that.

Currently, when I try and call a generate_quantities against a stan program using a fitted parameters CSV, it needs to be the literal output file from an HMC run, when I'd like to be able to use arbitrary CSV files.

#### Description:
Currently, when I try and call a generated_quantities against a stan program using a fitted parameters CSV, it'll fail with with `Error reading fitted param names from sample csv file "[FILENAME]"` unless I have a header. It also fails with `Mismatch between model and fitted_parameters csv file "[FILENAME]"` unless I have the HMC diagnostic outputs ("lp__", "accept_stat__", "stepsize__", "treedepth__", "n_leapfrog__", "divergent__", "energy__").  I don't think any of this information is to generate quantities consistent with particular fitted parameters, and not requiring this makes many workflows easier. In particular, it would let me unit test user defined stan functions using the generated quantities method for keeping code quality high, and let me stress test behavior of the model under extreme conditions that are difficult to simulate. Currently, I'm injecting garbage information in both the header and the HMC diagnostic columns from a template, but that's a rather awkward interface.

#### Reproducible Steps:
Run generated_quantities against any stan program without the header or HMC diagnostic columns.

#### Current Output:

*  `Error reading fitted param names from sample csv file "[FILENAME]"`
* `Mismatch between model and fitted_parameters csv file "[FILENAME]"`

#### Expected Output:

Normal Stan output

#### Current Version:
v2.27.0

**Comment by mitzimorris** [comment]
here's the description of what's needed in the Stan CSV file:  https://mc-stan.org/docs/2_27/cmdstan-guide/stan-csv.html#mcmc-sampler-csv-output

good luck.

**Comment by WardBrian** [comment]
A combination of https://github.com/stan-dev/cmdstan/pull/1106 and https://github.com/stan-dev/stan/pull/3179 have allowed this
