### ISSUE TITLE
Issue with STAN_NUM_THREADS and default num_threads

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#1043]
#### Description:

Run:

```
make STAN_THREADS=true examples/bernoulli/bernoulli
STAN_NUM_THREADS=4 ./examples/bernoulli/bernoulli sample data file=examples/bernoulli/bernoulli.data.json
```

throws an error:
```
STAN_NUM_THREADS= 4 but argument num_threads= 1. Please either only set one or make sure they are equal.
```

given that this worked for 2.27, I think it should still work.

#### Current Version:
v2.27.0

**Comment by rok-cesnovar** [comment]
This is a simple fix and I can do it right now before we make the RC public.

**Comment by wds15** [comment]
So the problem is that num_threads is defaulted to 1 and that triggers the error message?

I would still like to see the error if a user specifies both things and they contradict.

**Comment by rok-cesnovar** [comment]
> So the problem is that num_threads is defaulted to 1 and that triggers the error message?

Yeah, that is correct. 

The solution I had in mind is saying that the default is -2 for STAN_THREADS=true and 1 otherwise.
In case num_threads = -2 that means "use STAN_NUM_THREADS". 

If num_threads is not defined an STAN_NUM_THREADS is also not defined we error.

**Comment by wds15** [comment]
but then you get the same error whenever STAN_THREADS=true, no?

**Comment by rok-cesnovar** [comment]
> but for STAN_THREADS=false there is possibly an issue... or do we ignore STAN_NUM_THREADS in this case?

In that case  `stan::math::internal::get_num_threads()` returns 1 regardless of what STAN_NUM_THREADS is set to so there is no issue there.
