### ISSUE TITLE
XCode error for clang++ --version

### ISSUE THREAD

**Issue by jb621-star** [stan-dev/cmdstan#1045]
#### Summary:
Although this issue may not deal directly with CmdStan, it is a required step in the installation of CmdStan. When testing if Command Line Tools for XCode were properly installed, an error was thrown even though I followed the instructions on the Cmd Installation guide. 

#### Description:
The command clang++ --version throws the error:
dyld: Library not loaded: @rpath/libLLVM-10.dylib
  Referenced from: /Users/jamesonblount/opt/anaconda3/bin/clang++
  Reason: image not found
zsh: abort      clang++ --version

#### Reproducible Steps:
On Mac Terminal, the command "clang++ --version" produces this error. 

#### Current Output:
dyld: Library not loaded: @rpath/libLLVM-10.dylib
  Referenced from: /Users/jamesonblount/opt/anaconda3/bin/clang++
  Reason: image not found
zsh: abort      clang++ --version

#### Expected Output:
Current version of clang++

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.27.0

**Comment by rok-cesnovar** [comment]
Hey @jb621-star, sorry no one responded on this one. Did you manage to fix the issue on your own?
