### ISSUE TITLE
Release CmdStan & Stan 2.28.2

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#1061]
#### Description:

There were two bugs that were discovered in the 2.28.1 release:
 - https://github.com/stan-dev/cmdstan/issues/1055
 - https://github.com/stan-dev/cmdstan/issues/1058

These have now been addressed and we can do a patch release. We don't want to release on a Friday, so we should do it Monday or whenever @serban-nicusor-toptal has time (but not before Monday).

Here is a short checklist:

- [x] merge https://github.com/stan-dev/cmdstan/pull/1060
- [x] check that Stan submodule updates on CmdStan master after https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/master/30/pipeline/ finishes
- [x] update the release numbers of Stan on the master branch (not on develop!)
- [x] update the release numbers of CmdStan on the master branch (not on develop!)
- [x] release Stan 2.28.2 (release notes are posted below)
- [x] release CmdStan 2.28.2 (use 2.28.1 stanc3 tarballs - there were no changes there, release notes are posted below)
- [x] run CmdStanPy/R tests to make sure we didn't miss anything (CmdStan tests arent really that rich)
- [x] create and merge Stan PR to merge master to develop
- [x] create and merge CmdStan PR to merge master to develop

Stan release notes:
- Fixed a performance regression caused by using the diagnostic writer even when diagnostics were not requested.

CmdStan release notes:
- Fixed a performance regression caused by using the diagnostic writer even when diagnostics were not requested.
- Fixed a bug that prevented the use of init files when `num_chains` > 1.

#### Current Version:
v2.28.1

**Comment by serban-nicusor-toptal** [comment]
Release for Stan/CmdStan is now ready.
CmdStanR tests are running [here](https://github.com/stan-dev/cmdstanr/actions/runs/1490523486)

**Comment by serban-nicusor-toptal** [comment]
@rok-cesnovar cmdstan is failing on [master](https://jenkins.mc-stan.org/blue/organizations/jenkins/CmdStan/detail/master/34/pipeline/94), did I mess something up ?

**Comment by rok-cesnovar** [comment]
Yes, it related to 1062. Start a run with master branches for submodules and it will pass.

**Comment by serban-nicusor-toptal** [comment]
Argh I think Stan failed because of this `develop` [here](https://github.com/stan-dev/stan/blob/develop/Jenkinsfile#L280)

**Comment by rok-cesnovar** [comment]
The releases look good, the cmdstanr tests seem to be passing. @WardBrian can you run cmdstanpy when you have the chance?


> PS: I've fixed #1062 so there's no need for manual action.

hm, but wont this now be a problem with develop cmdstan? I guess we will see :) But we can address that later.

**Comment by rok-cesnovar** [comment]
Only thenon-x86 binaries are missing, then should be good if cmdstanpy tests pass.

**Comment by WardBrian** [comment]
Cmdstanpy tests are running now as a result of my pr to allow us to run them on arbitrary versions: https://github.com/stan-dev/cmdstanpy/pull/502

If either of you could take a look at the GHA file and approve, in the future this should allow us to manually run all the cmdstanpy tests on any version (including RCs, for example)

**Comment by serban-nicusor-toptal** [comment]
I'm not entirely sure why Stan fails, I've ran it with `master` [here](https://github.com/stan-dev/stan/blob/develop/Jenkinsfile#L280) with no success.

**Comment by WardBrian** [comment]
CmdStanPy tests are green

**Comment by serban-nicusor-toptal** [comment]
non-x86 are up now! The only thing left is to make Stan tests pass green on Jenkins and the PRs

**Comment by rok-cesnovar** [comment]
Order seems to be restored and the patch release process is done. Thanks @serban-nicusor-toptal !
