### ISSUE TITLE
Master tests of CmdStan should run with master branches of submodules

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#1062]
#### Description:

Currently, master branch tests of CmdStan run with develop branches of submodules. This is typically fine as we normally only merge to master on releases when `develop == master`. This pops up when doing patches at a later time, when develop has advanced significantly.

#### Current Version:
v2.28.1

**Comment by serban-nicusor-toptal** [comment]
[Switched](https://github.com/stan-dev/jenkins-shared-libraries/commit/bb84dc50e3375b83b8483c7bb0700b935a2f5cf2) to master.

**Comment by serban-nicusor-toptal** [comment]
@rok-cesnovar `hm, but wont this now be a problem with develop cmdstan? I guess we will see :) But we can address that later.`
You are right, let's first finish with the release and I will patch it right after.

I'll make it checkout `master` submodules when we're running a master branch and `develop` submodules when running a develop branch, is that correct or do we want a different behaviour ?

**Comment by serban-nicusor-toptal** [comment]
I've [pushed](https://github.com/stan-dev/jenkins-shared-libraries/commit/2988f972c0e61bd0fea2f4716404379de5b9acb7) a new change that will make the function to checkout the submodules from the current running branch. Meaning that if cmdstan develop is running, it will use develop submodules but when cmdstan master will run we will checkout master submodules.

**Comment by rok-cesnovar** [comment]
I think this should work now yeah.

**Comment by rok-cesnovar** [comment]
Alas, we need to improve it :) 

The logic should be: 
- is the branch master? then all submodules should be master if not specified otherwise
- is the branch not master? then al submodules should be develop if not specified otherwise

The way its written now, for a PR3090 in Stan it would look for a branch Stan Math PR 3090, which is not what we want. See https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/PR-3090/1/pipeline

Sorry for not specifying this more clearly in the first place.

**Comment by serban-nicusor-toptal** [comment]
[Refactored](https://github.com/stan-dev/jenkins-shared-libraries/commit/8eb1bdb16208bc1130b2dbbf9037b2babecc2a4c. 
No problem, glad we got it right now!
