### ISSUE TITLE
colab-stan for version 2.28

### ISSUE THREAD

**Issue by fartist** [stan-dev/cmdstan#1068]
Hi I was wondering if there is a new colab-stan that I can use for the newest comdstan? as in the case study below:
https://github.com/stan-dev/example-models/blob/master/knitr/cloud-compute-2020/CmdStanR_Example_Notebook.ipynb

Or in general I would appreciate it if anyone can let me know how to get cmdstan 2.28 working on colab - thanks.

**Comment by WardBrian** [comment]
Relevant forum discussion here: https://discourse.mc-stan.org/t/planning-the-2-29-release/25711/26

In short, the standard `install_cmdstan` functions in either CmdStanPy or CmdStanR will work, but will take quite some time each instance. The 'collab release' available for 2.23 is simply the tar-gzip'd result of running that install.

**Comment by WardBrian** [comment]
A collab-cmdstan tar.gz is now available for the freshly released CmdStan 2.29
