### ISSUE TITLE
Different behavior for cmdstan v2.28 and v2.29 when accessing row of matrix with 1:1

### ISSUE THREAD

**Issue by nikuehn** [stan-dev/cmdstan#1084]
#### Summary:
There is a difference in behavior between v2.28.0/1 and v2.29.0/1 when accessing the first element of a matrix with `1:1`.

#### Description:
I have a model where I loop over some data, stored in a matrix, and need to access all rows before the current iteration.
The loop starts at 2 (`for (i in 2:N)`), and then the data gets accessed with `A[1:i-1]`.
For `i=2`, the result is of size `[1,Nc]` in v2.28, while the size is `[0,Nc]` in v2.29.

#### Reproducible Steps:
This is a minimal example (`model.stan`):
```
data {}

parameters {}

model {}

generated quantities {
  matrix[3,3] A;

  print(dims(A), dims(A[1]), dims(A[1:1]), dims(A[:,1:1]));
}
```
which I run with `./model sample num_warmup=0 num_samples=1 algorithm=fixed_param`.

#### Current Output:
Output with cmdstan v2.29.1:
`[3,3][1,3][0,3][3,1]`

Output with cmdstan v2.28.1:
`[3,3][1,3][1,3][3,1]`

#### Expected Output:
I would expect the output to be like in v2.28, and be consistent when accessing rows/columns.

#### Additional Information:
OS information: macOS Catalina, clang version 12.0.0

#### Current Version:
v2.29.1

**Comment by WardBrian** [comment]
Seems like it would be related to https://github.com/stan-dev/stan/pull/3095

Is this the intended behavior @SteveBronder @bob-carpenter ?

**Comment by bob-carpenter** [comment]
Thanks, @nikuehn.  This is a serious bug.  The 2.28 behavior is correct.  The intended behavior is that a matrix given a single multi-index returns a new matrix with the rows given by the indexes.  So that in general, the shapes will work like this:

```
int[J] idxs;
matrix[M, N] a;
matrix[J, N] b = a[idxs];
```

In your specific case of `idxs = 1:1 = { 1 }`, you should have this:

```
matrix[M, N] a;
matrix[1, N] b = a[1:1];
```

and then `b` is equal to the first row of `a`.  In contrast, a single index reduces the dimension, so you'd get:

```
matrix[M, N] a;
row_vector[N] b = a[1];
```

**Comment by rok-cesnovar** [comment]
I got it. 

This:
https://github.com/stan-dev/stan/blob/008bffb7aeb6e9dc70b6e6bd8dd10ade5bff729b/src/stan/model/indexing/rvalue.hpp#L341

should be `>=`. Just need to write a test and will open a PR.

**Comment by SteveBronder** [comment]
Ooof, thanks for catching that Rok!
