### ISSUE TITLE
compilation error linked to array of ints when run on Mac M1

### ISSUE THREAD

**Issue by aakhmetz** [stan-dev/cmdstan#1087]
#### Summary:
The program is not compiled with the message
```
error: non-constant-expression cannot be narrowed from type 'int' to 'double' in initializer list [-Wc++11-narrowing]
                 stan::model::rvalue(E_inc_R, "E_inc_R",
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
when I use Mac M1.

#### Description:
I declare the array of ints in my data
```
array[N] int E_inc_R;
```
and do the following for-loop in my model:
```
for (k in 1:N) 
    exposure_inc[k] = fma(min({E_inc_R[k], onset_inc[k]}) - E_inc_L[k],  x_raw[k], E_inc_L[k]);
```
the program is not compiled with the error above. ```onset_inc``` is a vector.

However, if I write either ```array[N] real E_inc_R;``` or remove ```min({...})``` by writing simply ```E_inc_R[k]```, the program succeeds to be compiled.

#### Expected Output:
I have run this program on ubuntu and there were no problems.

#### Current Version:
v2.29.2, a notebook of Mac M1

**Comment by WardBrian** [comment]
Are you able to share the full code of the model which leads to this error?

**Comment by WardBrian** [comment]
I believe instead of `min({E_inc_R[k], onset_inc[k]}) ` you can write `min(E_inc_R[k], onset_inc[k])`, does that change the result here?

**Comment by SteveBronder** [comment]
Can you show what flags you have set for the model (like in `CXXFLAGS`)

**Comment by aakhmetz** [comment]
Dear all, I am sorry, but it looks like I installed a "normal" version on my mac instead of "arm". I have been confused and such mistake with min({..}) is one of the signatures of such wrong-doing. Please forgive me.
