### ISSUE TITLE
CmdStan Bernoulli Example Compiling but Not Running

### ISSUE THREAD

**Issue by adayim** [stan-dev/cmdstan#1089]
#### Summary:
I can successfully compile the Stan model with cmdstan located in the examples/bernoulli directory, but the model is not running.

#### Description:
I found a similar issue [here](https://discourse.mc-stan.org/t/cmdstan-bernoulli-example-compiling-but-not-running-windows-10-cmdstan-2-26-1/21586). But I want to use stan in my computer, can't solve with that. It worked before, which I installed following the steps from the CmdStanR. But it stopped working after I updated the cmdstan with CmdStanR to 2.29.2. I forgort the older version of the cmdstan, I installed it around Oct. So I think it should be version 2.80.0. 

#### Reproducible Steps:
At the begaining, I have followed the steps in [here](https://mc-stan.org/cmdstanr/articles/cmdstanr.html). Everything went well, no error or warning was shown. After the compilation of the cmdstan, I restarted the R session. After that, I tried to run the example model from the CmdStanR, but it failed.
```r
> library(cmdstanr)
This is cmdstanr version 0.5.0
- CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
- CmdStan path: C:/Users/alimd/Documents/.cmdstan/cmdstan-2.29.2
- CmdStan version: 2.29.2
> fit <- cmdstanr_example(chains = 1)
Compiling Stan program...
Warning: Chain 1 finished unexpectedly!

Warning message:
No chains finished successfully. Unable to retrieve the fit. 
```
I checked the steps [here](https://mc-stan.org/docs/2_29/cmdstan-guide/cmdstan-installation.html). Added the `tbb` to the environment path. I opened cmd session in the cmdstan directory, and executed the following:
```cmd
mingw32-make examples/bernoulli/bernoulli.exe
```
This is successful, and there's a `bernoulli.exe` file under the `examples/bernoulli` folder. I followed the steps [here](https://mc-stan.org/docs/2_29/cmdstan-guide/mcmc-intro.html) try to run the sampler:
```cmd
cd examples/bernoulli
bernoulli.exe sample data file=bernoulli.data.json
```
But nothing happened. I removed everything and followed steps [here](https://mc-stan.org/docs/2_29/cmdstan-guide/cmdstan-installation.html#source-installation), compiled cmdstan from source. The problem is still there after trying cmdstan from 2.70.0 to 2.92.2. 

I have added `tbb` path manually and also run `mingw32-make install-tbb`. But the `mingw32-make install-tbb` works if I add quotation marks around the path in the setx command:
```cmd
setx Path "%~dp0stan\lib\stan_math\lib\tbb;%OLD_SYSTEM_PATH%"
```

#### Current Output:
No output from the following command:
```cmd
cd examples/bernoulli
bernoulli.exe sample data file=bernoulli.data.json
```
Error from R:
```r
> fit <- cmdstanr_example(chains = 1)
Compiling Stan program...
Warning: Chain 1 finished unexpectedly!

Warning message:
No chains finished successfully. Unable to retrieve the fit. 
```

#### Expected Output:
Based on the manual [here](https://mc-stan.org/docs/2_29/cmdstan-guide/mcmc-intro.html), it should start working.

#### Additional Information:
I am using Windows 11, Rtools 4.0, R 4.1.0. 
```cmd
C:\Users\alimd>g++ --version
g++ (Built by Jeroen for the R-project) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

C:\Users\alimd>mingw32-make --version
GNU Make 4.2.1
Built for x86_64-w64-mingw32
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
My environment path is here, don't know if this has any impact.
```cmd
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe;
C:\Users\alimd\AppData\Roaming\ActiveState\bin;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;
C:\Program Files\SASHome\SASFoundation\9.4\ets\sasexe;
C:\Program Files\SASHome\Secure\ccme4;
C:\Program Files\SASHome\SASFoundation\9.4\core\sasexe;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\WINDOWS\System32\OpenSSH\;
C:\Program Files\dotnet\;
C:\Program Files (x86)\PDFtk Server\bin\;
C:\Program Files\Git\cmd;
C:\Perl64\bin;
C:\Users\alimd\Documents\.cmdstan\cmdstan-2.29.2\stan\lib\stan_math\lib\tbb;
C:\rtools40\usr\bin;
C:\rtools40\mingw64\bin;
C:\Users\alimd\AppData\Local\Microsoft\WindowsApps;
C:\Program Files\R\R-4.1.0\bin;
C:\Users\alimd\AppData\Local\Programs\Python\Python39;
C:\Users\alimd\AppData\Local\Programs\Python\Python39\Scripts;
C:\Users\alimd\AppData\Local\Programs\Microsoft VS Code\bin;
C:\Users\alimd\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;
C:\gs;
C:\Users\alimd\AppData\Local\Pandoc\;
```

I believe this is hard to reproduce, but I don't know where is the problem. I have been struggling for days now. I don't want to reinstall my OS to solve this.

#### Current Version:
v2.29.2

**Comment by adayim** [comment]
These are the names of the files under `C:\Users\alimd\Documents\.cmdstan\cmdstan-2.29.2\stan\lib\stan_math\lib\tbb`.

```cmd
arena.d                    condition_variable.o  pipeline.d            spin_mutex.o                tbb_misc_ex.o
arena.o                    critical_section.d    pipeline.o            spin_rw_mutex.d             tbb_statistics.d
backend.d                  critical_section.o    private_server.d      spin_rw_mutex.o             tbb_statistics.o
backend.o                  dynamic_link.d        private_server.o      spin_rw_mutex_v2.d          tbb_thread.d
backref.d                  dynamic_link.o        proxy.d               spin_rw_mutex_v2.o          tbb_thread.o
backref.o                  frontend.d            proxy.o               task.d                      tbbmalloc.d
cache_aligned_allocator.d  frontend.o            queuing_mutex.d       task.o                      tbbmalloc.def
cache_aligned_allocator.o  governor.d            queuing_mutex.o       task_group_context.d        tbbmalloc.dll
concurrent_hash_map.d      governor.o            queuing_rw_mutex.d    task_group_context.o        tbbmalloc.o
concurrent_hash_map.o      itt_notify.d          queuing_rw_mutex.o    task_v2.d                   tbbmalloc_proxy.dll
concurrent_monitor.d       itt_notify.o          reader_writer_lock.d  task_v2.o                   tbbvars.bat
concurrent_monitor.o       itt_notify_malloc.d   reader_writer_lock.o  tbb-make-check              tbbvars.csh
concurrent_queue.d         itt_notify_malloc.o   recursive_mutex.d     tbb.def                     tbbvars.sh
concurrent_queue.o         large_objects.d       recursive_mutex.o     tbb.dll                     version_string.ver
concurrent_queue_v2.d      large_objects.o       rml_tbb.d             tbb_function_replacement.d  version_tbb_2020.3
concurrent_queue_v2.o      market.d              rml_tbb.o             tbb_function_replacement.o  x86_rtm_rw_mutex.d
concurrent_vector.d        market.o              scheduler.d           tbb_main.d                  x86_rtm_rw_mutex.o
concurrent_vector.o        mutex.d               scheduler.o           tbb_main.o
concurrent_vector_v2.d     mutex.o               semaphore.d           tbb_misc.d
concurrent_vector_v2.o     observer_proxy.d      semaphore.o           tbb_misc.o
condition_variable.d       observer_proxy.o      spin_mutex.d          tbb_misc_ex.d
```

This is the output of `Get-Command g++`:
```ps
PS C:\Users\alimd> Get-Command g++

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     g++.exe                                            0.0.0.0    C:\rtools40\mingw64\bin\g++.exe

```
But the `Get-Item Env:CXX` throw me error:
```ps
PS C:\Users\alimd\Documents\.cmdstan\cmdstan-2.29.2> Get-Item Env:CXX
Get-Item : Cannot find path 'Env:\CXX' because it does not exist.
At line:1 char:1
+ Get-Item Env:CXX
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Env:\CXX:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
```

Is this the cuase of the problem? I don't know how to fix this. 

I guess I have to use WSL if I can't find any solution for this.

**Comment by WardBrian** [comment]
That error is probably because I'm not up to date on my Powershell, not due to an error, sorry.

What does `mingw32-make print-compiler-flags` output if you run it in the cmdstan folder?

**Comment by adayim** [comment]
No, nothing. It's wierd and hard to debug this problem I think.

**Comment by WardBrian** [comment]
Also, what is the output of `where.exe tbb.dll`?

**Comment by adayim** [comment]
It returns `C:\Windows\System32\tbb.dll`.

**Comment by WardBrian** [comment]
If you would like to test this before editing your path, you should be able to copy `tbb.dll` from the tbb folder to the examples/bernoulli folder and then run the commands

**Comment by adayim** [comment]
🎉🎉🎉It worked after I copied the `tbb.dll` file under the `examples/bernoulli` folder. I will try to find a way to remove `system32` path within R and put my solution here. So others can see how to do deal with this. Thank you very much.

**Comment by adayim** [comment]
Thank you. I agree I shouldn't play with system32 folder, but I have renamed `tbb.dll` under the system32 folder. The date of the `tbb.dll` quite new and I think this was a leftover by some programs. After rebooting my computer, the system startup as expected. And the most exciting part is that the stan works. Thank you so much for the help.

**Comment by mitzimorris** [comment]
> fit <- cmdstanr_example(chains = 1)

the bernoulli model must be run with data.  `(chains=1, data="bernoulli.data.json")` or however you specify path in CmdStanR.

**Comment by adayim** [comment]
It works, this example is given by the cmdstanr vignette. 
It might be good to add quotation to the setx Path in the `install-tbb.bat` file though or it will throw an error.
```cmd
setx Path "%~dp0stan\lib\stan_math\lib\tbb;%OLD_SYSTEM_PATH%"
```

**Comment by mitzimorris** [comment]
is this a documentation problem? for CmdStan, CmdStanR, CmdStanPy?

**Comment by adayim** [comment]
I don't think it's a documentation problem. I just checked the source code of the `cmdstanr_example` function, it actually loads the  `bernoulli.data.json` data. This is just running the example provided by the `cmdstanr` package.
