### ISSUE TITLE
How to build `cmdstan` against system libraries?

### ISSUE THREAD

**Issue by sukanka** [stan-dev/cmdstan#1090]
#### Summary:
Please provide a short couple sentence summary.
How to build cmdstan against system libraries by writing a `make/local`?
#### Description:
Describe the issue as clearly as possible.
I want to build cmdstan against these system libraries: 
```
 'gtest' 'benchmark' 'sundials' 'boost' 'eigen' 'tbb'  'stanmath`
 'python-cpplint' 'opencl-headers' 'rapidjson' 'cli11'
```
I write a `local` file  like this, and put it in `make`  `stan/make`  to overwrite the library path
```
MATH = /usr/include/stan/
BOOST = /usr/include/boost
EIGEN = /usr/include/eigen3
OPENCL = /usr/include/CL
TBB = /usr/include/tbb
SUNDIALS = /usr/include/sundials
BENCHMARK = /usr/include/benchmark
GTEST = /usr/include/gtest
CPPLINT = /usr/lib/python3.10/site-packages/
RAPIDJSON = /usr/include/rapidjson/
CLI11 = /usr/include/CLI/
```
But when I run `make build` I get the error
```
--- Compiling the main object file. This might take up to a minute. ---
g++    -c -o src/cmdstan/main.o src/cmdstan/main.cpp
src/cmdstan/main.cpp:1:10: fatal error: cmdstan/command.hpp: No such file or directory
1 | #include <cmdstan/command.hpp>
|          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [make/program:14: src/cmdstan/main.o] Error 1
```

However, when I remove the `local` file and rerun `make build`. It works.
#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.29.2

**Comment by syclik** [comment]
@sukanka, thanks for writing up the issue!

Before getting into the technical issues, could I ask why you want to do this? It's not really the supported use-case for CmdStan (and really the rest of Stan) because there's a lot of chance for version mismatch that could cause compilation issues and runtime issues.

On to the technical issues:
1. does CmdStan build without modification?
2. is that the actual output from `make build`? It seems to be missing ALL the includes. I'm not even sure how that could happen.
3. did you modify anything else other than `make/local`? That could explain question 2.
4. rather than replacing everything, can we try replacing one library at a time? I feel like you'll run into a version mismatch where it won't compile soon, but it's easier to diagnose when only changing one thing at a time.

**Comment by sukanka** [comment]
Thanks for your reply! I'm running archlinux, I'm afraid that if `cmdstand` is build against the old dependencies (shipped with the released tarball), it will fail to run in the future (as the other libraries will be updated). But currently, it runs just fine.
My system has the following libs:
```
boost 1.78.0-1
eigen 3.4.0-1
tbb 2021.5.0-1
opencl-headers 2:2022.01.04-1
...
```
For the technical issues:
1. Sure, and it runs just fine, no coredumps.
2. It is all the output. The command stopped there. I also wondered why it didn't find the headers. The headers are just there.
3. No. Only `make/local` is changed.
4. Thanks for you suggestion! It helps a lot! I just add 
```
RAPIDJSON = /usr/include/rapidjson/
CLI11 = /usr/include/CLI/
```
to `make/local` and run `make build -j14`. It stopped with 
```
src/cmdstan/stansummary.cpp:11:10: Fatal error：CLI11/CLI11.hpp：No such file or directory
11 | #include <CLI11/CLI11.hpp>
```
But I noticed there is only `CLI.hpp`. So it is the problem of archlinux it self.
```
➜  ~ ls  /usr/include/CLI/
App.hpp  ConfigFwd.hpp  Error.hpp         Formatter.hpp  Option.hpp  StringTools.hpp  TypeTools.hpp   Version.hpp
CLI.hpp  Config.hpp     FormatterFwd.hpp  Macros.hpp     Split.hpp   Timer.hpp        Validators.hpp
```
and I noticed there is some log containing ` /usr/include/rapidjson/`.
Therefore, the above `local` file works. 
```
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I /usr/include/rapidjson/ -I /usr/include/CLI/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.75.0 -I stan/lib/stan_math/lib/sundials_6.0.0/include -I stan/lib/stan_math/lib/sundials_6.0.0/src/sundials    -DBOOST_DISABLE_ASSERTS          -c -fvisibility=hidden -o bin/cmdstan/stansummary.o    
```
After changing `CLI11 to CLI` and rerun `make build` I find some errors like 
```
src/cmdstan/stansummary.cpp: In function 'int main(int, const char**)':
src/cmdstan/stansummary.cpp:52:17: error: no matching function for call to 'CLI::App::add_option(const char [14], int&, const char [32], bool)'
52 |   app.add_option("--sig_figs,-s", sig_figs, "Significant figures, default 2.",
|   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
53 |                  true)
|                  ~~~~~
```
So the API in CLI11 has changed. Maybe I should write a patch for it.

---

But when I add a `local` file to the `make/` directory inside `stan_math` and run `make build`(in the source directory of cmdstan)
It seems that it still uses the bundled libraries
```
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I /usr/include/rapidjson/ -I /usr/include/CLI/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.75.0 -I stan/lib/stan_math/lib/sundials_6.0.0/include -I stan/lib/stan_math/lib/sundials_6.0.0/src/sundials    -DBOOST_DISABLE_ASSERTS                -Wl,-L,"/tmp/makepkg/stanc/src/cmdstan-2.29.2/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/tmp/makepkg/stanc/src/cmdstan-2.29.2/stan/lib/stan_math/lib/tbb"      bin/cmdstan/print.o        -Wl,-L,"/tmp/makepkg/stanc/src/cmdstan-2.29.2/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/tmp/makepkg/stanc/src/cmdstan-2.29.2/stan/lib/stan_math/lib/tbb"   -o bin/print
```

**Comment by syclik** [comment]
> I'm running archlinux, I'm afraid that if cmdstand is build against the old dependencies (shipped with the released tarball), it will fail to run in the future (as the other libraries will be updated).

I think the direction is backward! If you're only using what's in CmdStan without external dependencies, then it'll always build... even if system libraries change. The only time this wouldn't be true is if the compiler ends up not supporting the C++ code that particular version of CmdStan uses.

Does that make sense?

**Comment by sukanka** [comment]
Maybe you are correct. Well, this issue can be closed now. I will open another issue  to ask  for updating the  dependecies if someday the excutable built against these dependencies  crashes with a coredump.  Thanks for your opinions and patience.

**Comment by syclik** [comment]
@sukanka, thanks! Closing the issue. If you do need more help, please reach out.
