### ISSUE TITLE
too many makefile warnings about PCH headers

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#1098]
#### Summary:

In CmdStanPy, continually getting warnings to call rebuild CmdStan.
The makefile logic which creates specific PCH headers is not doing the right thing.
This is triggered when running the CmdStanPy unit tests, which include tests compiling models with/without threads, etc.

#### Description:
Fresh install of CmdStan from develop.

```
make: *** [make/program:58: /Users/mitzi/github/stan-dev/cmdstanpy/test/data/complex_var] Error 1

Command ['make', '/Users/mitzi/github/stan-dev/cmdstanpy/test/data/complex_var']
	error during processing No such file or directory

WARNING  cmdstanpy:model.py:562 CmdStan's precompiled header (PCH) files may need to be rebuilt.If your model failed to compile please run cmdstanpy.rebuild_cmdstan().
If the issue persists please open a bug report
```

#### Reproducible Steps:

not sure how to reproduce this consistently - when running development tests for CmdStanPy, this happens alot.

#### Current Output:
see above.

#### Expected Output:
make should just work.

#### Additional Information:
spend last weekend providing Bob Carpenter with stripped-down makefiles for his Stan Model Server project.  I think the makefiles need another round of refactoring.

#### Current Version:
v2.29.2

**Comment by mitzimorris** [comment]
I don't get these errors outside of my conda environment - @WardBrian - is conda caching information somewhere that might be screwing things up?

**Comment by WardBrian** [comment]
Are you using cmdstan from conda-forge or just a conda environment and cmdstan built from source?

**Comment by mitzimorris** [comment]
a conda environment and CmdStan build from source.

**Comment by mitzimorris** [comment]
all sorts of fun with cmdstan from conda-forge - that one was at 2.28 which is why that complex_var.stan file failed to compile.

**Comment by WardBrian** [comment]
You should be able to specify a version to install.

I suspect when using conda but building from source you have have multiple compilers being used in such a way that is inconsistent, leading to the PCH warning. I can look into this, it will be tricky without a Mac though

**Comment by WardBrian** [comment]
If you enable debug logging or print out the console, can you confirm that the pch error is showing up in the actual log? It's possible this is a cmdstanpy issue with being too sensitive to the output text

**Comment by WardBrian** [comment]
I believe that issue was related specifically to the new ARM based Macs, which now in theory also have a conda build.

getting an older version is odd but should be fixable with `conda upgrade cmdstan`. As for make errors, if everything is working correctly a conda user should never need to rebuild cmdstan - at most theyd reinstall it from conda. 

But, because the conda version doesn’t ship with a precompiled header, I suspect the string “model_header.gch” (or one of the others we’re searching for) might appear in the console string of the first build after install, possibly generating spurious warnings from python

**Comment by mitzimorris** [comment]
transfer this issue to CmdStanPy?

**Comment by WardBrian** [comment]
Depends, if you’re able to recreate and post the console output of the command we can confirm whether or not clang itself is issuing a PCH error

**Comment by mitzimorris** [comment]
closing issue because unable to recreate.
