### ISSUE TITLE
Release 2.30

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#1101]
**Feature freeze (21st of June):**
- [x] Ensure all expiring language deprecations have been removed or given new removal dates.
- [x] Create and merge version updating pull requests in Math/Stan/Cmdstan. These should be the last PRs accepted before the freeze.
- [x] Create Math/Stan RC releases.
- [x] Create Stanc3 RC binary.
- [x] Create a release candidate tarball for x86. Make sure RC tarballs include stanc3 binaries.
- [x] Check external links in docs (i.e. TBB docs link) - use https://github.com/tcort/markdown-link-check
- [x] Create a release candidate feature/bugfix list (major features/bugfixes that need testing, link to new docs in Github)
- [x] Run [CmdStanR tests](https://github.com/stan-dev/cmdstanr/actions/workflows/cmdstan-tarball-check.yaml) with the RC tarball.
- [x] Run CmdStanPy tests with the RC tarball.
- [x] Make a Discourse RC post.
- [x] Post a tweet with a link to the Discourse RC post.

**Release (10 days after the RC):**
- [x] Create the Math Release notes.
- [x] Create the Stan Release notes.
- [x] Create the Cmdstan Release notes.
- [x] Create the Stanc3 Release notes, include new deprecations and removals.
- [x] Rebuild and publish docs for the new version.
- [x] Check that docs for the previous release links correctly to the newest docs.
- [x] Create the Math release.
- [x] Create the Stan release.
- [x] Create the Stanc3 release.
- [x] Create x86 CmdStan tarballs (check version, check that the extracted folder is in the cmdstan-version format).
- [x] Create non-x86 CmdStan tarballs.
- [x] Create conda CmdStan tarballs.
- [x] Run CmdStanR tests with the release tarball.
- [x] Make a Stan blog release announcement post (thank the sponsors and all contributors, mention new devs).
- [x] Link to the blog post in a Discourse thread.
- [x] Make a Twitter announcement.
- [x] Update https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms#supported-cpp-versions-and-compilers
 
**Things to highlight in the release notes:**
- [x] The Windows RTools35 toolchain will no longer be supported

**Comment by rok-cesnovar** [comment]
The RC is currently set to this coming Thursday, but if it helps anyone we can move it to Monday, which is our typical "release" day. Let me know.

**Comment by WardBrian** [comment]
It would be great to get any of https://github.com/stan-dev/math/issues/2699 addressed before release. 

I think we will need to add a message to the release notes about “Please let us know if functions you expect to work with complex matrices are not yet supported so we can prioritize what to work on” or something like that anyway, but those should be fairly obvious ones

**Comment by rok-cesnovar** [comment]
On it! Been promising that one since January :)

**Comment by WardBrian** [comment]
I think that one is as simple as 

```c++
else {
        throw std::invalid_argument(
            "num_chains can currently only be used for HMC with adaptation engaged");
      }
```

following the `if (is_hmc && adapt_engaged) {`

**Comment by rok-cesnovar** [comment]
lol yeah

**Comment by rok-cesnovar** [comment]
Barring anything unexpected, the RC will be released on Tuesday. The only thing left open currently is the std_normal_qf I believe.

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal the current develop (master for stanc3) is what we want to release for the 2.30 RC. Whenever you are free tomorrow, feel free to start with the process. No rush.

I will make an RC announcement with some highlights until sometime afternoon CET when the US folks get up.

**Comment by rok-cesnovar** [comment]
The draft of the RC announcement is here: https://gist.github.com/rok-cesnovar/3a1419b665f4b09c26f2e56995938c81#file-stan-2-30-rc-announcement

Would appreciate any comments.

**Comment by serban-nicusor-toptal** [comment]
Hey @rok-cesnovar I've created the PRs to update the versions:
- https://github.com/stan-dev/math/pull/2759
- https://github.com/stan-dev/stan/pull/3132
- https://github.com/stan-dev/cmdstan/pull/1105

Would you mind taking a look and approve? Should we also skip waiting for CI and merge straight away so I can do the RC ?

**Comment by rok-cesnovar** [comment]
Thanks! Go ahead and merge them.

**Comment by rok-cesnovar** [comment]
We are not under any time pressure, so whenever they are built its fine.

**Comment by rok-cesnovar** [comment]
Thanks. I am seeing a cmdstan-2.30.0-rc1.tgz and .tar.gz file. And it seems as if they dont have the Stan sources inside?

**Comment by serban-nicusor-toptal** [comment]
Unintended mistake, I forgot to checkout submodules in cmdstan.
Everything should be fine now, updated release candidates as pre-release and re-uploaded the `tar.gz`

**Comment by rok-cesnovar** [comment]
Thanks, this seems to work. The RC announcement was posted on Discourse and Twitter. I am also running CmdStanR tests. I will check for broken links in the next few days.

**Comment by WardBrian** [comment]
Ran cmdstanpy tests here: https://github.com/stan-dev/cmdstanpy/actions/runs/2557546817

**Comment by rok-cesnovar** [comment]
Thanks! I also checked the links. All of them work, some just require an unnecessary redirect, that is addressed here: https://github.com/stan-dev/docs/pull/552

**Comment by WardBrian** [comment]
>  - Removed for loop trick for inlining functions without multiple return statements. (#1097)

This title should probably be something more like "Re-enabled function inlining optimizations at `O1`", and I think the abs/fabs change should be higher up. Otherwise the notes look good to me!

**Comment by rok-cesnovar** [comment]
Thanks. Updated my post, also added the line for the Math bugfix of gamma_lcdf.

**Comment by serban-nicusor-toptal** [comment]
Hey @rok-cesnovar I'll try to do it later today or early tomorrow

**Comment by WardBrian** [comment]
Docs look good to me

**Comment by rok-cesnovar** [comment]
There is some formatting issue here: https://mc-stan.org/docs/functions-reference/array-reductions.html#norms
I am not sure exactly what is up. It's a minor issue though. Not something we need to delay anything for.

**Comment by WardBrian** [comment]
Looks alright to me? What am I missing?

**Comment by rok-cesnovar** [comment]
On refresh it did show the equations, seems just a temporary browser issue. Sorry for the false alarm.

**Comment by rok-cesnovar** [comment]
All tasks are done so I am going to close this. Thanks all.
