### ISSUE TITLE
USER_HEADER is included twice if model lives on path `examples/bernoulli/bernoulli`

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstan#1103]
#### Summary:
This is an odd one. If one is trying, for example, the [documentation example](https://mc-stan.org/docs/2_29/cmdstan-guide/using-external-cpp-code.html) by editing the bernoulli file shipped with cmdstan, compilation will fail. The command which fails includes a `-include <USER_HEADER path>` directive twice, leading to errors for re-declaration.

This was discovered by matthew_ay on the forums: https://discourse.mc-stan.org/t/errors-with-stan-and-external-c-functionality/27768

The MAKE logic for the user header seems to have `examples/bernoulli/bernoulli` as a special string of some kind? See:

https://github.com/stan-dev/cmdstan/blob/6ed32b5445b6cc2c6e5be6033e3bedb3771e7017/make/program#L35-L37

#### Current Version:
v2.29.2

**Comment by rok-cesnovar** [comment]
I didnt quite understand from the discussion on discourse. So the problem with USER_HEADER only happens with the bernoulli model? Which is caused by this string matching somehow?

**Comment by rok-cesnovar** [comment]
Its been there since make/program was created: https://github.com/stan-dev/cmdstan/pull/645 
I think it just slipped through after some debugging effort for example.

We can just remove it.
