### ISSUE TITLE
cmdstan does not build (Windows 10, Rtools42 for Windows)

### ISSUE THREAD

**Issue by beckyfisher** [stan-dev/cmdstan#1113]
#### Summary:
Building cmdstan fails using rtools42, using mingw32-make with the g++ compiler.

#### Description:
Describe the issue as clearly as possible.

There are function definitions used but not defined in the build process. The specific example below is for 'at_quick_exit'. This is expected in the standard library and is either not found or not present.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

* Install rtools42
* Install mingw32-make
*    - pacman -Sy mingw-w64-x86_64-make
*     - signature checking is off because mingw-w64 package signature is unknown
* use the g++ in rtools42/ucrt64/bin path
* in cmdstan directory
  * mingw32-make clean-all
  * mingw32-make build

That starts the build process and leads to the error below.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

mingw32-make[1]: Entering directory 'c:/cmdstan/stan/lib/stan_math/lib/tbb'
g++ -c -MMD -O2 -DUSE_WINTHREAD -D_WIN32_WINNT=0x0502 -DMINGW_HAS_SECURE_API=1 -D__MSVCRT_VERSION__=0x0700 -msse -mthreads -m64 -mrtm   -Wno-unknown-warning-option -Wno-deprecated-copy -Wno-missing-attributes -Wno-class-memaccess -Wno-sized-deallocation   -DTBB_SUPPRESS_DEPRECATED_MESSAGES=1 -fno-rtti -fno-exceptions -D__TBBMALLOC_BUILD=1 -Wno-parentheses -Wno-uninitialized -Wno-non-virtual-dtor  -flifetime-dse=1 -I../tbb_2020.3/src -I../tbb_2020.3/src/rml/include -I../tbb_2020.3/include -I../tbb_2020.3/src/tbbmalloc -I../tbb_2020.3/src/tbbmalloc ../tbb_2020.3/src/tbbmalloc/backend.cpp
In file included from C:/rtools42/ucrt64/include/c++/12.1.0/stdlib.h:36,
                 from C:/rtools42/ucrt64/lib/gcc/x86_64-w64-mingw32/12.1.0/include/mm_malloc.h:27,
                 from C:/rtools42/ucrt64/lib/gcc/x86_64-w64-mingw32/12.1.0/include/xmmintrin.h:34,
                 from C:/rtools42/ucrt64/lib/gcc/x86_64-w64-mingw32/12.1.0/include/immintrin.h:31,
                 from ../tbb_2020.3/include/tbb/machine/gcc_itsx.h:57,
                 from ../tbb_2020.3/include/tbb/machine/gcc_ia32_common.h:107,
                 from ../tbb_2020.3/include/tbb/machine/gcc_generic.h:232,
                 from ../tbb_2020.3/include/tbb/tbb_machine.h:197,
                 from ../tbb_2020.3/src/tbbmalloc/Synchronize.h:20,
                 from ../tbb_2020.3/src/tbbmalloc/Customize.h:29,
                 from ../tbb_2020.3/src/tbbmalloc/TypeDefinitions.h:54,
                 from ../tbb_2020.3/src/tbbmalloc/tbbmalloc_internal.h:21,
                 from ../tbb_2020.3/src/tbbmalloc/backend.cpp:19:
C:/rtools42/ucrt64/include/c++/12.1.0/cstdlib:137:11: error: 'at_quick_exit' has not been declared in '::'
  137 |   using ::at_quick_exit;

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

Successful build

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.30.1

**Comment by rok-cesnovar** [comment]
You need to add these two lines to the `make/local` file:

```
CXXFLAGS += -Wno-nonnull
TBB_CXXFLAGS= -U__MSVCRT_VERSION__ -D__MSVCRT_VERSION__=0x0E00
```

then try to build again. We recommend using the Rtools40 toolchain on Windows if possible as the Rtools42 has some issues that require additional compile instructions like this. If using cmdstanr, this is handled automatically.

**Comment by beckyfisher** [comment]
Brilliant, thankyou so much. Your solution worked perfectly.
