### ISSUE TITLE
add +Jacobian adjustment option for optimization

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstan#1124]
#### Summary:

Add a new argument to optimization methods to allow inclusion of Jacobian in order to produce the maximum a posteriori (MAP) estimate in addition to the existing penalized maximum likelihood estimate.

#### Description:

Add a new argument

* `jacobian`: boolean valued, default `false`, indicating whether to include Jacobian in log density target

#### Expected Output:

This is testable with a constrained parameter that induces a Jacobian adjustment.  A simple one like a single positive-constrained value is easy to test.

#### Other information

This will have to be staged after an upgrade to optimization service functions in Stan, which in turn require an update to the optimization functions.

#### Current Version:
v2.30.1

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/stan/pull/3152

**Comment by mitzimorris** [comment]
Also update CmdStan User's Guide.
