### ISSUE TITLE
Integer overflow when allocating a vector in transformed data

### ISSUE THREAD

**Issue by vtraag** [stan-dev/cmdstan#1125]
#### Summary:
When allocating a vector of `N - 1` elements, with `N = 0`, the code compiles without warnings, but running the code freezes the system.

#### Description:
The `stan` program below compiles without problems, but running it freezes the system. The program is incorrect, and it probably suffers from integer overflow somewhere. This presumably leads to an attempt to allocate a vector of $2^{32} - 1$ elements.

#### Reproducible Steps:

Compile

```stan
transformed data
{
    int N = 0;
    vector[N - 1] x;
}
```

and then run the resulting executable.

#### Current Output:
My system freezes, and presumably running the test executable triggers the OOM killer.

#### Expected Output:
Warning or error of a probable integer overflow.

#### Additional Information:

--

#### Current Version:
v2.30.1

**Comment by vtraag** [comment]
My apologies, I thought I double checked whether the program to reproduce the problem froze, but apparently I didn't do a good job there, because I now also can't reproduce it.

At first, I was using `N` uninitialized, as follows:

```stan
transformed data
{
    int N;
    vector[N - 1] x;
}
```

This does freeze for me, without yielding a warning still. I wasn't sure about initialization rules, so I tried explicitly with `N = 0`, which I thought froze as well, but I probably didn't test it correctly.

In this example (i.e. without initializing `N`), still no proper check is being done somehow. That is, if I print the (uninitialized) value of `N`, it can be negative, but then instead of erroring out, it freezes.

I do have the entry `stan::math::validate_non_negative_index("x", "N - 1", (N - 1));` in the generated `.hpp` code.

I have installed `cmdstan` as a dependency of `cmdstanpy` in an Anaconda environment from the `conda-forge` channel. To be precise, `cmdstan=2.30.1=h34c9540_0` as a dependency of `cmdstanpy=1.0.7=pyhd8ed1ab_0`.

**Comment by WardBrian** [comment]
Uninitialized integers in Stan are set to INT_MIN, and subtracting any value from INT_MIN is undefined behavior in C++. 

For many compilers this will result in INT_MAX which will do as you specified, but that is not guaranteed in the C++ standard. 

At any rate, I’m not sure if there is anything we can do to prevent this in general (maybe someone actually wants a MAX_INT sized vector on their large server, I think it’s “only” ~20Gb).

You can try to get a compile-time warning for uninitialized variables with the `warn-uninitialized` flag to the stanc3 compiler. You can pass this to cmdstanpy as `CmdStanModel(…, stanc_options={“warn-uninitialized“:True})`

**Comment by vtraag** [comment]
OK, that sounds fair enough, this should probably be closed then.

Just to understand: what is the rationale for stan to explicitly initialise integers to INT_MIN instead of 0?

**Comment by WardBrian** [comment]
Stan initializes variables without values to NaN if they are floats and INT_MIN if they are ints. I believe the rationale is to make these values “noisy” rather than being 0 which could be easy to miss
