### ISSUE TITLE
Release 2.31

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#1126]
**Feature freeze (8th of November):**
- [x] Ensure all expiring language deprecations have been removed or given new removal dates.
- [x] Create and merge version updating pull requests in Math/Stan/Cmdstan. These should be the last PRs accepted before the freeze.
- [x] Create Math/Stan RC releases.
- [x] Create Stanc3 RC binary.
- [x] Create a release candidate tarball for x86. Make sure RC tarballs include stanc3 binaries.
- [x] Check external links in docs (i.e. TBB docs link) - use https://github.com/tcort/markdown-link-check
- [x] Create a release candidate feature/bugfix list (major features/bugfixes that need testing, link to new docs in Github)
- [x] Run [CmdStanR tests](https://github.com/stan-dev/cmdstanr/actions/workflows/cmdstan-tarball-check.yaml) with the RC tarball.
- [x] Run CmdStanPy tests with the RC tarball.
- [x] Make a Discourse RC post.
- [x] Post a tweet with a link to the Discourse RC post.

**Release (~18th of November):**
- [x] Create the Math Release notes.
- [x] Create the Stan Release notes.
- [x] Create the Cmdstan Release notes.
- [x] Create the Stanc3 Release notes, include new deprecations and removals.
- [x] Rebuild and publish docs for the new version.
- [x] Check that docs for the previous release links correctly to the newest docs.
- [x] Create the Math release.
- [x] Create the Stan release.
- [x] Create the Stanc3 release.
- [x] Create x86 CmdStan tarballs (check version, check that the extracted folder is in the cmdstan-version format).
- [x] Create non-x86 CmdStan tarballs.
- [x] Run CmdStanR tests with the release tarball.
- [x] Make a Stan blog release announcement post (thank the sponsors and all contributors, mention new devs).
- [x] Link to the blog post in a Discourse thread.
- [x] Make a Twitter announcement.

**Comment by WardBrian** [comment]
I saw @serban-nicusor-toptal made the RC tarballs (thanks Nic!) so I ran the CmdStanPy tests - all looks good
https://github.com/stan-dev/cmdstanpy/actions/runs/3420089171/jobs/5694455810

**Comment by rok-cesnovar** [comment]
Running cmdstanr as well: https://github.com/stan-dev/cmdstanr/actions/runs/3422302336/jobs/5699544847

**Comment by rok-cesnovar** [comment]
I will prepare an RC post in the morning and then publish it on Discourse once you have a chance to check it @WardBrian. Does that sound good?

**Comment by WardBrian** [comment]
Yep, just ping me here or slack when you have a draft of the notes. Thanks!

**Comment by rok-cesnovar** [comment]
The RC highlights were posted on Discourse and linked to Twitter.

**Comment by rok-cesnovar** [comment]
Sorry for the delay. Here you go:
```
Math:
 - Added the generalised hypergeometric function. (#2510)
 - Added var<Matrix> overloads for  `pow()`, `owens_t()`, `log_inv_logit` . (#2546, #2787, #2806)
 - Add tuple overload and cleanup code for promote_scalar. (#2706)
 - New gradient function allows evaluated gradient to be stored into an array, enabling memory reuse when stan/math called via a FFI. (#2743)
 - Added function for casting `double` and `std::vector<double>` types to `int` and `std::vector<int>` types(#2771)
 - Added `hypergeometric_2F1` function. (#2792)
 - Fix bug with vectorised `pow()` incorrectly forcing `Eigen::Matrix` return instead of `Eigen::Array`. (#2793)
 - Exposed the `hypergeometric_3F2` function and improved its numerical stability. (#2797)
 - Fixed incorrect return from `log_inv_logit_diff` with positive infinity first argument. (#2798)
 - Added reverse-mode specializations for `fft2` and `inv_fft2`. (#2800)
 - Removed the cause of the out-of-order initializer compiler warning.(#2808)
 - Vectorized `atan2()`.(#2812)
 - Added `complex_schur_decompose_t` and `complex_schur_decompose_u`.(#2814)
 - Vectroized the `conj()` function. (#2817)
 - Stan's algebraic solvers now support variadic arguments. (#2820)
 - Fixed forward mode autodiff for FFT functions. (#2821)
 - Added `log_sum_exp_signed` function for computing `log_sum_exp` while respecting signs of arguments and tracking the sign of the result. (#2829)
 - `stan_print` can now print std::tuple types. (#2835)
 - `stan::math::minus` can now accept `std::vector`. (#2840)

Stan:
 - RapidJSON library is now a part of Stan (previously part of CmdStan) (#3143)
 - Added a #define flag flag to enable nested autodiff in model_base class (#3144)
 - Set up the service function so interfaces can offer Laplace approximation. (#3148)

CmdStan:
 - Allowed standalone generate_quantities using non-HMC fit (#1106)
 - Added method for calculating log_prob and its gradients (#1107, #1108)

 Stanc3:
 - Improved the error message for bad multiple declarations. (#1239)
- Fixed a bug where using a C++ reserved word as a name in certain situations would prevent compilation. (#1243)
 - Build binaries in parallel on Jenkins. (#1244)
 - Added functions `complex_schur_decompose_t()` and `complex_schur_decompose_u()` implementing the complex-valued Schur decomposition for matrices.(#1247)
 - Vectorized the `conj` function for complex types.(#1253)
 - CI change, build backwards-compatible Mac executables on flatiron mac. (#1255)
 - Improved the error generated when a function is re-declared, or when a function is not given a definition. (#1256)
 - `print` and `reject` will now be listed as functions in `stanc --info`s output. (#1257)
 - Added quantile functions (inverse-CDFs) `std_normal_qf` and `std_normal_log_qf`. `std_normal_qf` is a synonym for `inv_Phi`, and `std_normal_log_qf` is the same but with the input on the log-scale.(#1258)
 - Fix using `reject()` with container types. (#1261)
 - Vectorized sampling statements can now be used with the truncation syntax `T[ , ]`(#1263)
 - Functions which return integer types are considered as "data" for purposes of data-only arguments.(#1265)
 - The negation operator `-` can now accept arrays, e.g. `array[N] int foo = {...}; print(-foo);`(#1266)
 - Exposes algebraic functions with a variadic arguments, using the following four functions: `solve_powell`, `solve_powell_tol`, `solve_newton` and `solve_newton_tol`.  Relevant changes to Stan-math are already merged.(#1268)

```

**Comment by serban-nicusor-toptal** [comment]
If there are no objections, I will start soon ( ~30 minutes ) with the release

**Comment by rok-cesnovar** [comment]
Go for it!

**Comment by serban-nicusor-toptal** [comment]
I generated docs in the meanwhile so you guys can review it if it's fine.
https://github.com/stan-dev/docs/pull/598
https://github.com/stan-dev/stan-dev.github.io/pull/176

**Comment by serban-nicusor-toptal** [comment]
The release is now mostly done.

- stanc3 https://github.com/stan-dev/stanc3/releases/tag/v2.31.0
- math https://github.com/stan-dev/math/releases/tag/v4.5.0
- stan https://github.com/stan-dev/stan/releases/tag/v2.31.0
- cmdstan https://github.com/stan-dev/cmdstan/releases/tag/v2.31.0

We need to review and merge docs, after that, all links in the release notes will start working.
I also created PRs to update develop with the release notes in the release branch and after this we will do develop -> master PRs.
Conda binaries are still building, will add them shortly.

**Comment by rok-cesnovar** [comment]
Thanks! Running tests with cmdstanr now. Then the last point is making the blog post & link to it in various places. I hope to have it up today.

**Comment by rok-cesnovar** [comment]
The blog post is now live https://blog.mc-stan.org/2022/11/23/release-of-cmdstan-2-31/. I apologize for the delay. 

With that, I am going to close this issue. Thanks to Nic and Brian for all the help, as always!

**Comment by rok-cesnovar** [comment]
For the record, the non-x86 tarballs were not named properly. They were still using the old release versions. Replaced them today. Need to think of a way to automatically test that.
