### ISSUE TITLE
log_prob method changed - missing prefix `g_` for final param

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#1132]
https://github.com/stan-dev/cmdstan/blob/6bfcc1cd7315d11a90bfa2c09a6a8e2e5a4fd282/src/cmdstan/command.hpp#L695

not sure what's going on here - shouldn't this line also prefix the param name with `g_`?

**Comment by mitzimorris** [comment]
check via git blame - change is here:  https://github.com/stan-dev/cmdstan/blame/cc7061252cc093317999b275b6ac7be233b4b86f/src/cmdstan/command.hpp#L696

**Comment by WardBrian** [comment]
Seems like a fairly simple oversight, I agree it should have the prefix
