### ISSUE TITLE
Suspected typos in make prevent building of 2.31.0 on Linux

### ISSUE THREAD

**Issue by mikegilchrist** [stan-dev/cmdstan#1136]
#### Summary:
I cannot build 2.31.0 on a MATE/Ubuntu 22.04 LTS machine. Removing the single quotes around `'$(MAKE)'` at lines 169 and 173 in file `stan/lib/stan_math/make/libraries`  fixes the issue.

#### Description:

Download 2.31.0 tar, unzip, enter root directory of download and issue `$ make build` results in the following output

```
.
.
.
g++ -pipe   -pthread -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_matho
ar -rs stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_kinsol.a stan/lib/stan_math/lib/sundials_6.1.1/src/kinsol/kinsol_bbdpre.o stan/lib/stan_math/lib/sundials_6.1.1/src/kinsol/kinsol.o stan/lib/stano
ar: creating stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_kinsol.a
touch stan/lib/stan_math/lib/tbb/tbb-make-check
tbb_root="../tbb_2020.3" CXX="g++" CC="gcc" LDFLAGS='-Wl,-L,"/tmp/cmdstan-2.31.0/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/tmp/cmdstan-2.31.0/stan/lib/stan_math/lib/tbb"  ' 'make -j8' -C "stan/lib/stan_math/"
bash: line 1: make -j8: command not found
make: *** [stan/lib/stan_math/make/libraries:173: stan/lib/stan_math/lib/tbb/tbbmalloc.def] Error 127
```

#### Additional Information:

Removing the `'`' fixes the problem.

#### Current Version:
v2.18

**Comment by WardBrian** [comment]
I cannot recreate this on Ubuntu 22.04 myself. Do you have a custom MAKE set?

I believe this logic is important for windows users if they have a space in the path to make

**Comment by mikegilchrist** [comment]
Apparently I do.  

```
$ echo "$MAKE"
make -j8
```

My apologies, I didn't realize that was the case.
