### ISSUE TITLE
New laplace method enforces constraint not observed by optimize

### ISSUE THREAD

**Issue by jbolstad** [stan-dev/cmdstan#1156]
#### Summary:
The new Laplace method for obtaining posterior draws enforces parameter constraint(s) that are not ensured by the output of optimize.

#### Description:
I have a model containing a simplex vector of parameters. The output of optimize sums to 1.0000001, while the new laplace command requires the input to sum to 1.

#### Reproducible Steps:
Create model with a simplex of parameters, and run optimize and laplace as described [here](https://discourse.mc-stan.org/t/obtaining-posterior-draws-from-optimize-in-cmdstan/30991/5?u=novice). 

#### Current Output:
"Exception: stan::math::simplex_free: Simplex variable is not a valid simplex. sum(Simplex variable) = 1.0000001, but should be 1 (found before start of program)
Bad or missing parameter values, cannot unconstrain."

#### Suggested Solution:
Either optimize should enforce the sum-to-one constraint for simplexes or laplace should do it (at least for inputs that sum to ca. 1.01)?

#### Current Version:
v2.32.0 -- pre-release

**Comment by WardBrian** [comment]
Optimize does enforce this constraint internally but it’s not necessarily going to round trip after being output in a CSV of only 6 digits of precision. You may be able to resolve the problem by increasing the number of digits you’re saving

**Comment by jbolstad** [comment]
That does seem to help, thank you. (The question is whether I can consider this a satisfactory solution, as I cannot really afford occasional errors here.)

**Comment by jbolstad** [comment]
Saving 18 digits (`output sig_figs=18`), I have not yet reproduced this issue, so I'm assuming this solves it. Thank you!

**Comment by WardBrian** [comment]
Anything above ~16 digits should essentially be full double precision, which might be necessary depending on your exact requirements. 

This is something that hopefully will be less necessary in the future if we add binary output formats, which would store full precision much more cheaply.

**Comment by bob-carpenter** [comment]
Our simplex validator

https://github.com/stan-dev/math/blob/develop/stan/math/prim/err/check_simplex.hpp

uses the constant `CONSTRAINT_TOLERANCE` in:

https://github.com/stan-dev/math/blob/develop/stan/math/prim/err/constraint_tolerance.hpp

which is `1e-8`.
