### ISSUE TITLE
documentation clarify require make from CMDSTAN_HOME

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstan#118]
Make sure that 

* [x] section 2.3 (compiling) emphasizes that you have to be in CMDSTAN_HOME for CmdStan to work.

* [ ] section 2.3 (summarizing sampler output) Remove backslash in front of `bin` in `/bin/print` example

* [x] section 4.2, paths pointing into Stan as if it's still part of stan-dev/stan rather than its own repo (see `stan/example-models/basic_estimators`)

* [x] update logo

**Comment by syclik** [comment]
I couldn't find the backslash. If it's still there after I fix everything, let me know.
