### ISSUE TITLE
multi-pathfinder algorithm - add arg to enable/supress output of single-path pathfinders

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#1180]
#### Summary:
For multi-path Pathfinder, add a command-line argument to enable/supress writing of CSV files for the individual single-path pathfinders.

#### Description:
When running multi-path pathfinder, the algorithm outputs the draws from each single-path pathfinder as well as the PSIS draws.  The single-path CSV files are there mainly for the purpose of checking the Pathfinder algorithm; the PSIS draws are the outputs intended for inference.

#### Current Version:
v2.32.2

**Comment by WardBrian** [comment]
My vote is disabled by default with a flag to enable

**Comment by mitzimorris** [comment]
there's this argument grouping - adding this to "output" seems most natural, but this is totally pathfinder-specific.   any suggestions for arg name?

**Comment by WardBrian** [comment]
The assumption that output spec is independent of algorithm looks more questionable by the day. I think it really only makes sense to place under pathfinder, since putting it under output would add an argument to all the other methods which don't need it. 

I think calling it `save_individual_paths` is good. The edge case of `num_paths=1 save_individual_paths=0` is a bit annoying, but I think we can just ignore it entirely if num_paths is 1

**Comment by bob-carpenter** [comment]
This was, of course, the failure mode I anticipated for this design, so I'm also OK putting it under the pathfinder hierarchy of command-line args.

**Comment by mitzimorris** [comment]
proposed fix:

pathfinder boolean arg `save_single_paths`, default false.

the PSIS sample file is `output.csv`

by default, pathfinder method runs 4 single-path pathfinders.
when  `save_single_paths`, single-path pathfinder output filenames look like:
`output_pathfinder_<path-id>.csv`, e.g.

`output_pathfinder_1.csv` ... `output_pathfinder_4.csv`

if arg `num_paths` == 1,  the result of the single-path pathfinder run will also be in file `output.csv`.
reasoning here is that if you only get one output file, you don't need any qualifiers on the filename.

happy to modify this as @bob-carpenter and @WardBrian see fit.

**Comment by bob-carpenter** [comment]
That sounds OK to me.

**Comment by mitzimorris** [comment]
single-path output name suggestions?

`output_pathfinder_1.csv` vs `output_single_path_1.csv`. ???

**Comment by WardBrian** [comment]
I would say output_path_1
