### ISSUE TITLE
spurious error message for models which don't need input data

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#1182]
#### Summary:
if a model doesn't have a data block, then no input data file is required, but now that we have Rdump warnings,
this results in a spurious error message.  fix.

#### Description:

many of the test models don't have data.  when running the unit tests, seeing this message:

>     Warning: file '' is being read as an 'RDump' file.
> 	This format is deprecated and will not receive new features.
> 	Consider saving your data in JSON format instead.

#### Reproducible Steps:
 see above.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.32.2

**Comment by WardBrian** [comment]
This is coming from this specific place the warning is raised:
https://github.com/stan-dev/cmdstan/blob/a3d01b2d9a0f901528b374289347f71ebaba7e58/src/cmdstan/command_helper.hpp#L169-L174

All the other places are properly guarded against empty files.
