### ISSUE TITLE
A returning function was expected but an undeclared identifier 'wiener_full_lpdf' was supplied.

### ISSUE THREAD

**Issue by swg168** [stan-dev/cmdstan#1211]
#### Summary:

After configured cmdstan, run the command make ./my_stan_model, return:
`A returning function was expected but an undeclared identifier 'wiener_full_lpdf' was supplied.`

#### Description:

I want use the stan math function in this paper [The Seven-parameter Diffusion Model: an Implementation in Stan for Bayesian Analyses](https://doi.org/10.3758/s13428-023-02179-1), but when  I configured the cmdstan according to the [CmdStan User’s Guide](https://mc-stan.org/docs/cmdstan-guide/index.html)  and run the command `make ./ my_stan_model` , it returns `A returning function was expected but an undeclared identifier 'wiener_full_lpdf' was supplied.` . However I found the function in stan math branch fix/wiener5_fixes, so I tried to change the stan math branch in cmdstan-home-directory/stan/lib/stan_math through git, but it didn't work, still return `A returning function was expected but an undeclared identifier 'wiener_full_lpdf'`.  I want to know if there exists a way to make it work?

#### Reproducible Steps:

1. git clone https://github.com/stan-dev/cmdstan.git --recursive
2. cd cmdstan
3.  make build
4. make ./my_stan_model

#### Current Output:
The current output. Knowing what is the current behavior is useful.
`A returning function was expected but an undeclared identifier 'wiener_full_lpdf' was supplied`

#### Expected Output:
--- Translating Stan model to C++ code ---
......

--- Compiling C++ code ---
.......

--- Linking model ---
........
#### Additional Information:
system: Ubuntu 22.04

#### Current Version:
v2.33.1

**Comment by WardBrian** [comment]
This function is not yet implemented in Stan's Math library (see https://github.com/stan-dev/math/pull/2822) or the Stan compiler
