### ISSUE TITLE
pathfinder: output files don't respect multiple periods, clobber outputs

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstan#1213]
#### Summary:

Reported by @andrewjradcliffe

Passing an output file argument with multiple `.`s in it and requesting `save_single_paths` leads to output files with the same name, so they all end up clobbering the output files on disk.

#### Reproducible Steps:

```
./bernoulli pathfinder save_single_paths=1 output file=foo.bar.baz data file=bernoulli.data.json
```

#### Current Output:

This produces files `foo.bar.csv  foo_path_1.bar  foo_path_2.bar  foo_path_3.bar  foo_path_4.bar`

The files `foo_path_1.bar`... all have a incoherent mix of json/csv in them.

#### Additional Information:

I believe this is because the `make_filenames` function doesn't replace an extension if it is already provided. This works if there is 1 `.` in the name since we artificially strip it out for pathfinder, but if there is more than one we get this problem. 

#### Current Version:
v2.33.1

**Comment by mitzimorris** [comment]
the logic is all fubar.   for the downstream regression tests, there's one set that uses suffix ".tmp" instead of ".csv".

this logic would be greatly simplified if we specified that output CSV files are always suffixed ".csv" and changed the regression testset names.

**Comment by WardBrian** [comment]
> this logic would be greatly simplified if we specified that output CSV files are always suffixed ".csv" and changed the regression testset names.

That seems fine to me? Maybe we should print a warning if they were specified with another extension and we ignore it. Pathfinder is technically the only interface where we need to be able to ignore it, since the csvs and jsons differ only by extension, but threading a flag through the helper code seems like overkill
