### ISSUE TITLE
Missing headers fail `make build`, `clean-libraries` has no target

### ISSUE THREAD

**Issue by Tarotis** [stan-dev/cmdstan#1227]
#### Summary:
Please provide a short couple sentence summary.

`make build` fails for cmdstan-2.33.1 on MacOS ARM2, but not for cmdstan-2.32.2

#### Description:
Describe the issue as clearly as possible.

We are not able to compile cmdstan on MacOS ARM2 due to (apparently) missing headers.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

```
blum@lingn45 cmdstan-2.33.1 % make clean-all
rm -f -r test
rm -f 
rm -f 
rm -f 
rm -f 
  removing dependency files
rm -f    
rm -f   
rm -f   
make: *** No rule to make target `clean-libraries', needed by `clean-all'.  Stop.
blum@lingn45 cmdstan-2.33.1 % make build
curl -L https://github.com/stan-dev/stanc3/releases/download/nightly/mac-stanc -o bin/stanc --retry 5 --retry-delay 10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11.5M  100 11.5M    0     0  8781k      0  0:00:01  0:00:01 --:--:-- 24.6M
chmod +x bin/stanc

--- Compiling the main object file. This might take up to a minute. ---
clang++    -c -o src/cmdstan/main.o src/cmdstan/main.cpp
src/cmdstan/main.cpp:1:10: fatal error: 'cmdstan/command.hpp' file not found
#include <cmdstan/command.hpp>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [src/cmdstan/main.o] Error 1
```

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

Correct build.

#### Additional Information:
Provide any additional information here.

I tried to run `make clean-all` which helped with some previous issues, but this did not work, since the make command failed.

#### Current Version:
v2.33.1

**Comment by WardBrian** [comment]
Do you have the submodules populated (e.g., is there anything in the folder `stan/` and `stan/lib/stan_math`)?

**Comment by Tarotis** [comment]
The folder is a fresh clone of the most recent release, and the `stan`-folder is completely empty.

` blum@lingn45 .cmdstan % git clone https://github.com/stan-dev/cmdstan/ --branch v2.33.1 cmdstan-2.33.1`

**Comment by mitzimorris** [comment]
CmdStan needs its submodules - you need to add `--recursive` to the git clone directive.

cf. the install instructions here:  https://mc-stan.org/docs/cmdstan-guide/cmdstan-installation.html#installation-from-github. (apologies for the rtfm)

**Comment by Tarotis** [comment]
I see now, should have read more carefully. Thanks!
