### ISSUE TITLE
Error: GitHub download of release list failed with error: cannot open URL 'https://api.github.com/repos/stan-dev/cmdstan/releases/latest'

### ISSUE THREAD

**Issue by BEAST-Community** [stan-dev/cmdstan#1247]
Dear @maverickg,

How to deal with this?

install_cmdstan()
The C++ toolchain required for CmdStan is setup properly!
trying URL 'https://api.github.com/repos/stan-dev/cmdstan/releases/latest'
trying URL 'https://api.github.com/repos/stan-dev/cmdstan/releases/latest'
trying URL 'https://api.github.com/repos/stan-dev/cmdstan/releases/latest'
trying URL 'https://api.github.com/repos/stan-dev/cmdstan/releases/latest'
trying URL 'https://api.github.com/repos/stan-dev/cmdstan/releases/latest'
trying URL 'https://api.github.com/repos/stan-dev/cmdstan/releases/latest'
Error: GitHub download of release list failed with error: cannot open URL 'https://api.github.com/repos/stan-dev/cmdstan/releases/latest'

**Comment by rok-cesnovar** [comment]
Is there any chance you have a `GITHUB_PAT` set in `.Renviron` and it expired?

**Comment by WardBrian** [comment]
If this persists please open an issue against cmdstanr
