### ISSUE TITLE
remove compilation of `print` utility from makefile

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#1250]
#### Summary:

The `print` utility is advertised as deprecated.  why bother to compile it by default?

#### Description:

Makefile advertises that print will be removed: https://github.com/stan-dev/cmdstan/blob/3284433f25bd589f2cfc6dbc6abec3b8e09be3a3/makefile#L171

question of semantics - if we leave the source file avilable but don't compile it, does this count?

compiled here:  https://github.com/stan-dev/cmdstan/blob/3284433f25bd589f2cfc6dbc6abec3b8e09be3a3/makefile#L266

Is it worth skipping the compile step of one utility program?   I'm doing an initial install of CmdStan on a linux HPC cluster, running cmdstanr's `install_cmdstan()` function and it is *slow*.   `print` utility is a very small part of that.

#### Current Version:
v2.34.1

**Comment by bob-carpenter** [comment]
I think we can get rid of it.  The doc doesn't even say what it does, only that it's been replaced by `stansummary`.

https://mc-stan.org/docs/cmdstan-guide/print-deprecated-mcmc-output-analysis.html

**Comment by WardBrian** [comment]
See discussion in #1251
