### ISSUE TITLE
cmdstan 2.34.1 source does not have stan_math? 

### ISSUE THREAD

**Issue by segasai** [stan-dev/cmdstan#1252]
#### Summary:
The released  2.34.1 .tar.gz of cmdstan doesn't seem to include stan_math.

#### Description:
Previously (at least 2.32.2 version I have around) included stan_math. 

#### Reproducible Steps:
Download  cmdstan-2.34.1.tar.gz
unpack and run `make build` which gives
```
ERROR: Missing Stan submodules.
We tried to find the Stan Math submodule at:
```

#### Current Version:
v2.34.1

I understand that the git repo checkout needs the git submodule steps, but I was assuming that the provided  .tar.gz should work without that  (and that was the case before).

Thanks

**Comment by mitzimorris** [comment]
I just downloaded the 2.34.1 release, unzipped it, and `tar -t` shows all stan_math files are there - subdir `stan/lib/stan_math`

```
cmdstan-2.34.1/stan/lib/stan_math/stan/
cmdstan-2.34.1/stan/lib/stan_math/stan/math/
cmdstan-2.34.1/stan/lib/stan_math/stan/math/version.hpp
cmdstan-2.34.1/stan/lib/stan_math/stan/math/rev/
cmdstan-2.34.1/stan/lib/stan_math/stan/math/rev/core.hpp
cmdstan-2.34.1/stan/lib/stan_math/stan/math/rev/functor.hpp
cmdstan-2.34.1/stan/lib/stan_math/stan/math/rev/fun/
cmdstan-2.34.1/stan/lib/stan_math/stan/math/rev/fun/acos.hpp
cmdstan-2.34.1/stan/lib/stan_math/stan/math/rev/fun/trace.hpp
cmdstan-2.34.1/stan/lib/stan_math/stan/math/rev/fun/is_nan.hpp
cmdstan-2.34.1/stan/lib/stan_math/stan/math/rev/fun/to_var.hpp
```

**Comment by segasai** [comment]
My apologies. I don't quite know how it happened. I can see the file is indeed smaller than needed 

$ ls -lth cmdstan-2.34.1.tar.gz 
-rw-rw-r-- 1 .. 1.5M Feb 26 16:46 cmdstan-2.34.1.tar.gz

and when redownloading stan_math is there. 

Sorry for the noise
