### ISSUE TITLE
Let generated quantities run in parallel

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/cmdstan#1253]
#### Summary:

We are using the single threaded API for the generated quantities service, but we have a service layer API for doing multiple generated quantities at once. We should be using that for GQ

command.hpp code

https://github.com/stan-dev/cmdstan/blob/develop/src/cmdstan/command.hpp#L361

multi threaded gqs code
https://github.com/stan-dev/stan/blob/develop/src/stan/services/sample/standalone_gqs.hpp#L112

#### Current Version:
v2.34.1

**Comment by WardBrian** [comment]
#1256
