### ISSUE TITLE
Doc Fix? Setting STAN_THREADS=false (or FALSE, 0, etc) results in STAN_THREADS=true

### ISSUE THREAD

**Issue by katrinabrock** [stan-dev/cmdstan#1293]
#### Summary:

As concisely stated in this comment: https://github.com/stan-dev/cmdstan/issues/1179#issuecomment-1683935722

>Most of our makefile logic just checks if STAN_THREADS is defined, not that it is set to a "truthy" value.

However, the [documentation](https://mc-stan.org/docs/cmdstan-guide/parallelization.html) does not explicitly state this, leading users (including apparently cmdstanr developers) to incorrectly infer that falsy values will turn off multi-threading. 

#### Description:

Not sure if the behavior should change or the doc should change here, but certainly if the behavior remains as-is, it would be good to make the doc more explicit. This issue likely impacts other flags as well.

It would also be helpful for `make help-dev` or a similar command to resolve the value to how it will be interpreted at compile time.

#### Reproducible Steps:

```{bash}
~/.cmdstan/cmdstan-2.35.0$ STAN_THREADS=false make examples/bernoulli/bernoulli
~/.cmdstan/cmdstan-2.35.0$ examples/bernoulli/bernoulli info|grep STAN_THREADS
```

#### Current Output:
```
STAN_THREADS=true
```

#### Expected Output:

```
STAN_THREADS=false
```

#### Current Version:
v2.35.0

**Comment by WardBrian** [comment]
I definitely agree this needs to be explained better!

Re:
>It would also be helpful for make help-dev or a similar command to resolve the value to how it will be interpreted at compile time.

You can use `make print-compiler-flags` to see a lot of good info. In particular, if you set `STAN_THREADS`, the define is included:

```
...
  - CXXFLAGS_THREADS             -DSTAN_THREADS
...
```

**Comment by katrinabrock** [comment]
ah, thanks! re: `make print-compiler-flags`

**Comment by katrinabrock** [comment]
^ PR for doc fix
