### ISSUE TITLE
Support accepting file path argument to the optimize init parameter

### ISSUE THREAD

**Issue by jachymb** [stan-dev/cmdstan#1305]
#### Summary:
The `init` parameter of the `optimize` method can be set to a number x which is a range (-x, x). The `init` parameter of the `sample` method can be set to a json file.  I think there should be something similar for the `optimize` which doesn’t currently seem to accept a file path as argument.

#### Current Version:
v2.36.0

**Comment by WardBrian** [comment]
The init argument is the same for all algorithms
