### ISSUE TITLE
cmdstan package for Homebrew-science

### ISSUE THREAD

**Issue by sjackman** [stan-dev/cmdstan#145]
Hi. I'm packaging `cmdstan` for [Homebrew-science](http://brew.sh/homebrew-science). Should the package name be `cmdstan` or just `stan`? I'm going with `cmdstan`, but wanted to check.
The name `bin/print` is too common, likely to conflict with other packages, and must be renamed. I was going to name it `stanprint`. Do you have a better suggestion? Would you consider also renaming it upstream?

Cheers,
Shaun

**Comment by sjackman** [comment]
Here's the pull request for the Homebrew formula: https://github.com/Homebrew/homebrew-science/pull/2639

**Comment by sjackman** [comment]
There's an issue with this formula with a missing header file `stan/math.hpp`. I can't find this file in the GitHub repository.

```
❯❯❯ brew test cmdstan -v
Testing homebrew/science/cmdstan
==> /usr/local/Cellar/cmdstan/2.7.0/bin/stanc --version
stanc version 2.7.0
==> /usr/local/Cellar/cmdstan/2.7.0/bin/stanc bernoulli.stan
Model name=bernoulli_model
Input file=bernoulli.stan
Output file=bernoulli_model.cpp
==> make bernoulli_model
/usr/bin/clang++ -Os -w -pipe -march=native -mmacosx-version-min=10.10 -F/usr/local/Frameworks -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names  bernoulli_model.cpp   -o bernoulli_model
In file included from bernoulli_model.cpp:3:
/usr/local/include/stan/model/model_header.hpp:4:10: fatal error: 'stan/math.hpp' file not found
#include <stan/math.hpp>
         ^
1 error generated.
make: *** [bernoulli_model] Error 1
```

**Comment by dustinvtran** [comment]
I have no authority on this matter, but personally I prefer: `cmdstan`, `stanprint`, and `stanmake`. `cmdstan` follows the convention of installing `rstan` in R, `pystan` in Python, etc. `stanprint` and `stanmake` is what @akucukelbir uses as the names of the excellent scripts which print and make stan-related files from any directory.

On your error: To get the math header, you have to git clone recursively. Or as suggested in the [wiki](https://github.com/stan-dev/cmdstan/wiki/Getting-Started-with-CmdStan), call `make stan-update` in the cmdstan repo.

**Comment by betanalpha** [comment]
The print function is really a component of cmdstan, hence
our local naming.  I’m fine with stanprint.

Assuming that the Homebrew recipe is for the cmdstan
interface then, yes, the name should be “cmdstan”.
“stan” refers to the C++ API, not any single interface.

**Comment by syclik** [comment]
Yes to `cmdstan`. I'm happy changing `bin/print` to `bin/stanprint` for CmdStan (#49: we should just fix that on a separate pull request).

@sjackman, regarding the last error, we have the Stan Math Library as a submodule. Did you update that?

**Comment by syclik** [comment]
@dustinvtran, @akucukelbir: what is `stanmake`?

**Comment by dustinvtran** [comment]
@syclik A version of it exists [here](https://github.com/stan-dev/cmdstan/pull/56#issuecomment-54553949)

**Comment by akucukelbir** [comment]
@syclik @dustinvtran an updated version is
```
stanmake () {
	inputFile=$1
	inputFileStripped=$inputFile:r
	rm -i -f $inputFileStripped.hpp
	origPWD=$PWD
	pathToProgram=$PWD/$inputFileStripped
	pathToStan=/Users/alpkucukelbir/GitHub/cmdstan/
	cd $pathToStan
	make $pathToProgram
	cd $origPWD
	rm -i -f $inputFileStripped.d
	rm -i -f $inputFileStripped.o
	rm -i -f $inputFileStripped.hpp
}
```

**Comment by syclik** [comment]
@sjackman, what's the timeline / process for getting it into Homebrew science? Is there anything else you'll need to make life easier?

**Comment by bob-carpenter** [comment]
I know "stanprint" is more like our current "print", but
I prefer "stansummary" if that's not too verbose, because
it's more precise.  I'd write "stanposteriorsummary" but
that's way too verbose and smashed together.

I like the idea of deprecating print if that's feasible (i.e.,
it won't conflict).   Can we do it just by copying?

- Bob

**Comment by sjackman** [comment]
I'm using `cmdstan-2.7.0.tar.gz`. It includes the `stan` submodule, but not the `math` submodule. `math` does not appear to be a dependent submodule of `cmdstan`. I'd prefer not to run `stan-update` so that the installation does not require network access.

**Comment by sjackman** [comment]
`stansummary` sounds like a good name for `print`.

**Comment by sjackman** [comment]
> @sjackman, what's the timeline / process for getting it into Homebrew science? Is there anything else you'll need to make life easier?

@syclik It's pretty quick. Once I've resolved the issue with the dependency on `stan/math` it'll be in Homebrew in a few hours, once it's been built by the @BrewTestBot.

**Comment by bob-carpenter** [comment]
Feel free to repackage however you want for distribution.

My understanding is that:

  stan-dev/math is submodule of stan-dev/stan
  stan-dev/stan is submodule of stan-dev/cmdstan

- Bob

**Comment by sjackman** [comment]
`stan-dev/math` does not appear to be a git submodule of `stan-dev/stan`. Please do correct me if I'm wrong.

**Comment by bob-carpenter** [comment]
https://github.com/stan-dev/stan/blob/develop/.gitmodules

**Comment by sjackman** [comment]
Ah, thanks. I was looking for it under the root directory. It's at `lib/stan_math`.

**Comment by sjackman** [comment]
@bob-carpenter `lib/stan_math` isn't included in `cmdstan-2.7.0.tar.gz`. Should it be?

**Comment by bob-carpenter** [comment]
Not sure why this is directed at me. 

From a quick look at the doc (which says 2.6.2 on the web site but
points to the 2.7.0 doc --- I created an issue to fix that), if 
it's not included in the .tar.gz distribution, then we need
much better documentation to show how to include it.

- Bob

**Comment by syclik** [comment]
It is included in the tar gz file I uploaded.
https://github.com/stan-dev/cmdstan/releases/download/v2.7.0/cmdstan-2.7.0.tar.gz

GitHub doesn't include submodule inside their direct downloads.

**Comment by sjackman** [comment]
The Homebrew formula is working now. Here it is: https://github.com/Homebrew/homebrew-science/pull/2639
Once it builds the binary bottles, I'll merge it.

**Comment by sjackman** [comment]
`cmdstan` is now in Homebrew-science. `brew install homebrew/science/cmdstan`

**Comment by syclik** [comment]
Sweet!

Shaun, sorry -- been a little busy. Was there anything else you need us
(really me) to do to make this easier going forward? If you can think of
anything, please throw up issues and I'll try to get to it.
