### ISSUE TITLE
stanmake script

### ISSUE THREAD

**Issue by syclik** [stan-dev/cmdstan#146]
@akucukelbir, is script solid enough to distribute publicly? If so, let's get it into the repo. We would need:
- documentation
- install instructions
- when and where it works / doesn't work

If you think it's not going to hold up, close this issue with a comment.

**Comment by akucukelbir** [comment]
@syclik it depends on whether you want to ship an installer with cmdstan. 

the script is only useful if it lives somewhere on your path (e.g. ```/usr/local/bin```) or in your RC file (e.g. ```.zshrc```).

i suspect we'd need some sort of installer to copy ```stanmake``` and make it point to wherever ```cmdstan``` lives.

**Comment by syclik** [comment]
I'm not opposed to having a `cmdstan` installer.

It sounds like the script isn't useful as-is.

**Comment by akucukelbir** [comment]
yeah, i think this will require too much hassle on our end to get working "straight out of the box".
