### ISSUE TITLE
Trying to install StataStan

### ISSUE THREAD

**Issue by jbtack** [stan-dev/cmdstan#204]
I am using the Chrome web browser.

I am following the getting started instructions here:
https://github.com/stan-dev/statastan

At step 1, when I click on the "CmdStan" link, it takes me to the page:
http://mc-stan.org/cmdstan.html

On this page, there is an informational message that reads:
"The current Metropolis proposal is about to be rejected because of the following issue: The page you were trying to view does not exist."

Any guidance on how to install StataStan much appreciated.

**Comment by syclik** [comment]
Sorry about that. The website path is incorrect. This is the correct link:
http://mc-stan.org/interfaces/cmdstan.html

I'll fix the readme. Let us know if you have any other trouble.

**Comment by jbtack** [comment]
Thank you very much for the help, however now I am having the following problem at Step 3 of the Getting Started instructions here: 
https://github.com/stan-dev/statastan

I am running the "stan example.do" file and received the following error inside of Stata (v13):

. stan y, modelfile("mystanmodel.stan") cmd("$cmdstandir") globals("N") load mode
unrecognized command:  windowsmonitor
r(199);

I have changed the cmdstan folder path at the top of the do-file, for me the path is:
"C:\Users\Tack\Documents\cmdstan-2.8.0"

Any help much appreciated!

**Comment by syclik** [comment]
@jbtack, sorry for the delay -- this got lost due to being on the wrong repo. Can you either post to the stan-users email list (https://groups.google.com/forum/#!forum/stan-users) or go to the statastan repo and open an issue there?
