### ISSUE TITLE
src/test/interface/services/argument_configuration_test.cpp fails with ADVI occasionally

### ISSUE THREAD

**Issue by syclik** [stan-dev/cmdstan#261]
@akucukelbir / @dustinvtran: this test fails occasionally. We need to fix this asap. It's holding up our build process. It should fail never.

Here's the command it tries to run:
`cd test ; ../src/test/test-models/test_model method=variational algorithm=meanfield iter=10000 grad_samples=1 elbo_samples=1 eta=1 adapt engaged=1 iter=50 tol_rel_obj=0.01 eval_elbo=100 output_samples=1000`

You can run the test by typing:
`./runCmdStanTests.py src/test/interface/services/argument_configuration_test.cpp`

If it doesn't fail the first time, run it a few more times and it fails fairly regularly.

**Comment by syclik** [comment]
I found a seed that makes it fail -- 2233103535.

To build the model, from the CmdStan home:
`make src/test/test-models/test_model`

To run:
`src/test/test-models/test_model method=variational algorithm=meanfield iter=10000 grad_samples=1 elbo_samples=1 eta=1 adapt engaged=1 iter=50 tol_rel_obj=0.01 eval_elbo=100 output_samples=1000 random seed=2233103535`

**Comment by akucukelbir** [comment]
just landed. i'll take a look asap.

**Comment by syclik** [comment]
Thanks.

**Comment by akucukelbir** [comment]
@syclik what does this test do? does it just randomly pick some configuration of input parameters and run it?

what seems to be happening is that if `variational::advi::adapt_eta` fails (which can happen) then we throw a `stan::math::domain_error`. this seems to be happening here when `test_model` picks a particularly meaningless setting of parameters. (the example you posted above fails because `elbo_samples=1` [why not the default?]. i tried it again and it set the eta adapt `iter=2` [again, why?])

**Comment by syclik** [comment]
It's an automated test that walks through the arguments and instantiates it
with the values that are specified in the argument. It checks to make sure
the "_good_value" results in a non-error and a "_bad_value" results in an
error.

If you look at stan's
src/stan/services/arguments/arg_variational_eval_elbo.hpp, you'll see line
24: "_good_value = 1.0;" This is where it's getting the 1 from. If there's
another value you want to insert for the test, change that value.

I didn't realize how often adaptation fails... we should talk about how to
deal with this after you're back from NIPS. In the meantime, if you have
good values that make the adaptation not fail, please create a pull request
with those values as the "_good_value" so our tests fail less often.

**Comment by syclik** [comment]
Fixed in Stan.
