### ISSUE TITLE
stansummary and print don't compile on Arch Linux (Eigen problems)

### ISSUE THREAD

**Issue by gilesc** [stan-dev/cmdstan#296]
The relevant part of the make output:

```
g++ -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I src -I stan/src -isystem stan/lib/stan_math/ -isystem  -isystem  -Wall -pipe -DEIGEN_NO_DEBUG -I/include   -c -O3 -o bin/cmdstan/stansummary.o src/cmdstan/stansummary.cpp
In file included from stan/src/stan/mcmc/chains.hpp:4:0,
                 from src/cmdstan/stansummary.cpp:5:
stan/src/stan/io/stan_csv_reader.hpp:6:23: fatal error: Eigen/Dense: No such file or directory
compilation terminated.
makefile:80: recipe for target 'bin/cmdstan/stansummary.o' failed
make: *** [bin/cmdstan/stansummary.o] Error 1
```

Same error with print. I am on Arch Linux 64-bit with both Eigen2 and Eigen3 installed (headers are in /usr/include/{eigen2,eigen3} respectively). But it also failed with only Eigen3 installed. libstanc.a and stanc compile just fine.

**Comment by syclik** [comment]
It looks like you didn't clone CmdStan properly. Or you downloaded the
packaged version from git, which only includes CmdStan and not the
necessary libraries.

Can you follow these instructions and report back?
https://github.com/stan-dev/cmdstan/wiki/Getting-Started-with-CmdStan

**Comment by gilesc** [comment]
Argh. I had done a simple `git submodule init && git submodule update`, missing the recursive. Thanks.
