### ISSUE TITLE
Add flag to stanc to not ouput C++ to a file

### ISSUE THREAD

**Issue by jrnold** [stan-dev/cmdstan#309]
## Feature Request

**Description**

Add a flag to `stanc` to compile the model to C++, but not output to a file. Possible flag names could be `-c` for check, `-d` for debug, or `-n` for null. This would be useful (though not necessary) for developing on the fly error checking in emacs or Atom. Alternatively a flag to  ouput to stdout, so it could be directed to `/dev/null` would work.

**Example**

Run `stanc` on a model to check for compiler errors but not output to a file,

```
$ stanc -n foo.stan
```

**Additional Information**

I've been playing around with a linter for [Atom](https://github.com/jrnold/atom-linter-stanc) and at various times supporting flycheck for emacs.

**Comment by ariddell** [comment]
It seems like stdout should be the default with -o being an output to a filename.

**Comment by jrnold** [comment]
Except that compilers like `gcc` and `clang` output by a file by default.

**Comment by ariddell** [comment]
But stanc isn't a compiler. It's a transpiler.

**Comment by bob-carpenter** [comment]
If you take a look at stan-dev/stan/src/stan/lang/compiler.hpp,
you'll see

    bool compile(std::ostream* msgs,
                 std::istream& stan_lang_in,
                 std::ostream& cpp_out,
                 const std::string& model_name) {
      program prog;
      bool parsed_ok = parse(msgs, stan_lang_in,
                             model_name, prog);
      if (!parsed_ok)
        return false;  // syntax error in program
      generate_cpp(prog, model_name, cpp_out);
      return true;
    }

I should've named this "transpile".  I may change it going
forward.  But the point is that it calls the parse function,
then generates C++.  We could write a command in stanc that
just called the parser --- it's save all the I/O in generate_cpp.

So if this really must be in stanc, then I think we want a command-line
flag that gets passed right down to stan::lang::compile()
to tell it not to bother generating the C++.

We still have some residual bugs from time to time where
something transpiles but doesn't actually parse in C++, but that's very
expensive to test and not something that should be happening,
so I don't think we'd want to test for bugs.

- Bob

P.S.  "Transpiler" is just a portmanteau for "source-to-source compiler":

  https://en.wikipedia.org/wiki/Source-to-source_compiler

I've conufsingly just called it a compiler in the code, as you see above.

**Comment by jrnold** [comment]
Now that I know where to look, I could figure it out when I have some time. It seems minimal work for something useful. Catching the C++ errors isn't what I was looking for (as those should be rarer :-) ), but simply catching parse errors as the model is being written.

**Comment by bob-carpenter** [comment]
Yup --- hopefully the C++ is easy for another command.  It's
the testing and doc and code formatting and code review
and revisions that are the time sinks :-)

- Bob

**Comment by rok-cesnovar** [comment]
Closing as C++ stanc will be deprecated soon. Open a new issue on the stan-dev/stanc3 repository if this is still relevant.
