### ISSUE TITLE
trim Boost and Eigen libs in releases a la RStan

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstan#33]
Chop down the library size in CmdStan for releases the same way it's done in RStan (and presumably PyStan).

I think C++ Stan should keep all of the libs in its repo to make it easy to develop against.

**Comment by syclik** [comment]
@bgoodri, what steps do you take for RStan?

**Comment by bgoodri** [comment]
We just use the BH package (plus some stuff that I have to add).

**Comment by syclik** [comment]
Ok. I'm closing this. If it isn't straightforward to do it, I think it's easier not to.

**Comment by bgoodri** [comment]
It isn't that hard for Boost; just run bcp. But there is nothing similar
for Eigen.

**Comment by syclik** [comment]
This doesn't look straightforward: http://www.boost.org/doc/libs/1_62_0/tools/bcp/doc/html/index.html

If I'm not mistaken, we would need to know everything Stan and Math depends on in Boost to generate the include libs to feed to bcp.

Just found the key lines of text:

> If you want to figure out which Boost headers are being used by your specific compiler then the best way to find out is to prepocess the code and scan the output for boost header includes. You should be aware that the result will be very platform and compiler specific, and may not contain all the headers needed if you so much as change a compiler switch (for example turn on threading support).

I don't think we'll need to do that for CmdStan.

**Comment by bgoodri** [comment]
For Stan Math,

mkdir /tmp/boost_1.62.0
find stan -name \*\.\[ch]pp -exec bcp --scan --boost=lib/boost_1.62.0 '{}'
/tmp/boost_1.62.0/ \;

and then for Stan Library

find src -name \*\.\[ch]pp -exec bcp --scan
--boost=lib/stan_math/lib/boost_1.62.0 '{}' /tmp/boost_1.62.0/ \;

Then /tmp/boost_1.62.0/boost is about 55M.

**Comment by syclik** [comment]
I'm opening this up again with a later milestone. Thanks for doing that -- I think that's enough to script as part of the release process.
