### ISSUE TITLE
make fails to remake model when headers change

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/cmdstan#34]
Presumably related to #27 -- make doesn't pick up any changes to dependent headers, requiring a user to delete any existing compiled executable before recompiling.  I'm guessing that the makefile doesn't look into the Stan submodule somehow, although the best I can figure is that the dependencies are set in Line 108 of the makefile which should look into the submodule.

**Comment by syclik** [comment]
I'll get back on this after the release.

**Comment by syclik** [comment]
#645 fixed this!
