### ISSUE TITLE
Failing to build on OS X

### ISSUE THREAD

**Issue by drbenvincent** [stan-dev/cmdstan#347]
When I try to build on mac using `make build -j2` as described in the manual, I get the following error

    make: *** No rule to make target `build'.  Stop.

I am not overly command-line fluent (so apologies if I'm missing something simple) but I've tried to follow the instructions and can't get anywhere.

Using cmdstan-2.9.0
I'm on OSX 10.11.4
Make 3.81
g++ 4.2.1

#### Current Version:
v2.9.0

**Comment by drbenvincent** [comment]
Sorry, this was my fault. I was copying and pasting the line

    make build -j2

from the manual, which gave the error. But typing it in manually worked. Sorry about he false alarm. I'm now up and running.

**Comment by bob-carpenter** [comment]
Thanks for reporting.  The comment indicates a problem that should be fixed, so I created a new issue citing this one:

https://github.com/stan-dev/cmdstan/issues/348
