### ISSUE TITLE
cut-and-paste from manual fails

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstan#348]
#### Summary:

See:  https://github.com/stan-dev/cmdstan/issues/347#issuecomment-204660721

in which @drbenvincent says:

... copying and pasting the line

```
make build -j2
```

from the manual, which gave the error. But typing it in manually worked.
#### Description:

I think LaTeX to PDF is messing up the character encoding so that the hyphen is no longer a regular hyphen.
#### Reproducible Steps:

See above.
#### Current Output:

Error.
#### Expected Output:

Cut-and-paste from manual works.
#### Additional Information:

We should see if this might be platform-specific.
#### Current Version:

v2.9.0

**Comment by rok-cesnovar** [comment]
Works in the manual for 2.20.
