### ISSUE TITLE
Softlinked cmdstan sample output of parameter values

### ISSUE THREAD

**Issue by alexpkeil1** [stan-dev/cmdstan#399]
#### Summary:
I have a softlinked (ln -s) version of cmdstan. When I run from the softlinked version, the output from 'method=sample' is typical, except that all values for the sampled parameters are identical across samples.

#### Description:
OS: OSX 10.11.5
stan: cmdstan 2.9.0 installed from github

I installed cmdstan from github into  ```/directory/where/I/store/github/repos/cmdstan ```

I then softlinked the cmdstan directory using:

 ```ln -s /directory/where/I/store/github/repos/cmdstan /better/directory/cmdstan ```

I then built a stan model in 'stanmodel.txt' that included a single parameter ```mu``` and called 
 ```/better/directory/cmdstan/make stanmodel.txt```

and ran with
 ```stanmodel method=sample output file=stanout.csv ```

#### Current Output:
When I inspected ```stanout.csv``` I noted that the values for ```mu``` were identical across all samples. The values for ```lp__``` and other variables ending in ```__``` seemed to look as expected, however.

#### Expected Output:
I expected ```mu``` to vary across samples. I have recreated this with other models that I have successfully run in the past.

#### Additional Information:
How I solved it:
I fixed this by calling stan from the non-softlinked directory, i.e. I fixed it using
 ```/directory/where/I/store/github/repos/cmdstan/make stanmodel.txt```

instead of 
 ```/better/directory/cmdstan/make stanmodel.txt```

Now I get the expected output. This is an admittedly strange way to run stan, but I figured it might be useful in case someone else runs into the same issue. I didn't pick up on it right away because everything else seemed to work fine.

#### Current Version:
v2.9.0

**Comment by bob-carpenter** [comment]
We'd love to be able to figure out how to make a Stan program in CmdStan from somewhere other than the install directory, but so far haven't been able to figure out how to do it.  Make's not the most flexible system and we're far from experts.  We're open to suggestions or pull requests, though.

**Comment by syclik** [comment]
Sorry I missed this issue when you opened it.

I'm not sure what you're doing because the way you have it written, it won't work. There's no make target in CmdStan's makefiles for `*.txt`. Also, the makefile in `make` is not an executable. 

I'm closing this issue for now, but if you still have issues, could you paste in exactly what you're typing into the command line so I can have a chance to follow along?

**Comment by alexpkeil1** [comment]
Sorry, I was doing this without looking at my code. For completeness, the code should be more like this:

     cd /path/to/cmdstan/ 
     make /Path/to/model

**Comment by syclik** [comment]
That should work fine.

Is the program / data something you can post? I can try to recreate locally
if it is.

**Comment by alexpkeil1** [comment]
I can't post it and have signed an agreement not to share it. I also cannot recreate this now on my own machine, but I'm now using one of the stan releases.

The original issue arose when I had installed directly from github, and there were a number of other issues, so I went back to the 2.9.0 release, figuring I had screwed up the github install.

**Comment by syclik** [comment]
Ok. We can leave it closed for now. If you do see the problem again, please reach out.
