### ISSUE TITLE
Copy Stan's src/stan/services/arguments/* to CmdStan

### ISSUE THREAD

**Issue by syclik** [stan-dev/cmdstan#404]
#### Summary:
Stan doesn't use `src/stan/services/arguments/*` and it's not used in RStan or PyStan. It should be moved to CmdStan.

#### Current Version:
v2.9.0

**Comment by betanalpha** [comment]
This was the first step of the original refactor, which would then
get propagated to the interfaces.  Of course that the refactor died
in a flames leaving the code in an intermediate state.  I don’t think
it’s worth moving this all to CmdStan but rather implementing the
“proper” refactor that is supposedly in the works directly.

**Comment by syclik** [comment]
Once again, Mike, you're right. It's not as simple as moving things over since it's all tied together. It was blocking me conceptually, but I'll have to work around it.
