### ISSUE TITLE
Directories not found in two pushd commands in test-all.sh (release v2.9.0)

### ISSUE THREAD

**Issue by felixleungsc** [stan-dev/cmdstan#437]
Line 16 has ```pushd stan``` and line 24 has ```pushd stan/lib/stan_math_2.7.0```, but the directory is actually named stan_2.9.0, and not stan.

The shell script seems to be running fine after changing the two lines to ```pushd stan_2.9.0``` and ```pushd stan_2.9.0/lib/stan_math_2.9.0```.

#130

**Comment by syclik** [comment]
Thanks. I'll get that fixed now.
