### ISSUE TITLE
Bad command line arguments causes program to stall (infinite loop somewhere?)

### ISSUE THREAD

**Issue by syclik** [stan-dev/cmdstan#443]
#### Summary:
Command line program doesn't terminate. It doesn't produce output.

#### Description:
The command line program hangs. This shouldn't happen. It should kick out with some sort of message. See below for reproducible example.

#### Reproducible Steps:
From CmdStan
```
make examples/bernoulli/bernoulli
cd examples/bernoulli
./bernoulli sample adapt=0
```

#### Current Output:

```
> ./bernoulli sample adapt=0

```
It stalls here forever. It does take up CPU cycles.

#### Expected Output:
Perhaps something to mirror what happens with `diagnose`

```
> ./bernoulli sample adapt=0
adapt=0 is either mistyped or misplaced.
Perhaps you meant one of the following valid configurations?
  [not sure what should be put here]
Failed to parse arguments, terminating Stan
```

#### Current Version:
v2.10.0

**Comment by betanalpha** [comment]
Moved to stan-dev/stan#1949 as the fix requires changing the arguments code in stan-dev/stan/services/arguments.

**Comment by syclik** [comment]
Thanks.
