### ISSUE TITLE
catches with informative errors for wrong argument value types in command.hpp

### ISSUE THREAD

**Issue by syclik** [stan-dev/cmdstan#48]
(original issue: stan-dev/stan#398)

Bob writes:
We should print out informative answers for arguments of the wrong types in the command. Here's the current behavior:

~/temp2$ ./sd sample adapt engaged=4

Exception: bad lexical cast: source type value could not be interpreted as target
Diagnostic information: 
Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_16bad_lexical_castEEEEE
std::exception::what: bad lexical cast: source type value could not be interpreted as target

What should be happening is that we detect that 4 is not a valid value for engaged, which only takes boolean values, and we should report that.

**Comment by syclik** [comment]
This needs to wait for the arguments to move to the repo: #287. After that gets merged, we can start on this.

**Comment by maedoc** [comment]
It doesn't seem like a type error, but passing an integer which is to long as `id` also produces a lexical cast error, e.g. 
```
./foobar id=2546248240 sample
bad lexical cast: source type value could not be interpreted as target
```

**Comment by bob-carpenter** [comment]
That should definitely have a better error message going back to the user.  it means we really need better integer I/O.  This will remain a problem when we move to long integers, because users will still be passing strings.

**Comment by rok-cesnovar** [comment]
Closing. The current output for this case is: 

```
4 is not a valid value for "engaged"
  Valid values: [0, 1]
Failed to parse arguments, terminating Stan

```
