### ISSUE TITLE
Manual should mention that in Windows make requires a drive letter with absolute paths

### ISSUE THREAD

**Issue by juhokokkala** [stan-dev/cmdstan#482]
#### Summary:
`make /myfolder/mymodel.exe` does not work, `make c:/myfolder/mymodel.exe` is required. This is not obvious from the manual.

#### Description:
I installed Rtools as recommended. The manual has example syntax only for the case where the target is in a subdirectory of the current directory. In Windows/DOS, \ in the beginning of a path points to the root of the current disk, so I assumed the corresponding syntax here to be `make /myfolder/mymodel.exe` when the `myfolder` directory is in the current disk.  It originally took me some time to get the idea of trying `c:/myfolder/mymodel.exe`.   In addition, neither `\...`  nor `c:\...` works.

#### Reproducible Steps:
Place a `mymodel.stan` file in `c:\myfolder`. Try calling `make /myfolder/mymodel.exe` from the CmdStan directory.

Observed with Windows 8(.1, I think) + CmdStan 2.9 (forgot to report back then) and reproduced with Windows 10 + CmdStan 2.11.0 + Rtools 3.3.  

#### Current Output:
`C:\stan\cmdstan-2.11.0> make /myfolder/mymodel.exe`
 `uname: not found`
 `uname: not found`
 `make: *** No rule to make target ``/myfolder/mymodel.exe'. Stop.`

#### Expected Output:
(In my opinion) The behavior does not need to be changed, but a remark about this in the manual would be useful. 

#### Additional Information
In the CmdStan tools (at least stansummary) and compiled models (at least for data file) all combinations of (\ or /) and (drive letter or no drive letter) work. 

#### Current Version:
v2.11.0

**Comment by juhokokkala** [comment]
I did not find a general "manual v 2.11.0" issue, I hope this is ok.

**Comment by bob-carpenter** [comment]
Thanks --- we appreciate feedback in any route.  We only keep the next manual issue open all the time for Stan itself, as that's where we get the most comments.

I agree that it'd be good to update the manual, so I assigned to Daniel who's been doing the CmdStan releases.  I'm pretty sure the path you need is `c:\myfolder\mymodel.exe` rather than one starting with '\'.  But your mileage (or kilometerage) will vary based on whether or not you have Cygwin on the PATH.

**Comment by syclik** [comment]
@juhokokkala, thanks! I've updated the manual and added a note. It's one of those things where I always use relative paths, so I didn't think about it.
