### ISSUE TITLE
Rename print stansummary

### ISSUE THREAD

**Issue by syclik** [stan-dev/cmdstan#49]
(original issue: stan-dev/stan#664)

from @tmalsburg:
The name `print` is already taken by other Unix tools.  Installing `print` on Unix-like systems may therefore lead to conflicts.  Apart from that, `print` is not very informative as a name.  The issue came up in #630 and I proposed to rename `print` to `stansummary` (reminiscent of R's summary function which does something similar for mixed models).  @bob-carpenter proposed `mcmcprint` and `stanprint`.  I like the use of `stan` as a prefix for all stan-binaries because that is informative and it reduces the probability of naming conflicts with other software packages.

Changing the name would probably require changes in some other places as well: documentation, other software that builds on stan (stan-mode.el for example), etc.  Not at least, the users have to relearn the command.  Nevertheless, it might make sense to change it.

**Comment by syclik** [comment]
@sjackman has suggested `stanprint`.

The two options we have: `stansummary`, `stanprint`. Any others?
When do we change this to have minimal impact on users?

**Comment by tmalsburg** [comment]
I don't know how many people are actually using the print command.  (I don't because I'm on RStan.)  If there are reasons to believe that it's a substantial number, it might make sense to have a transition period where the old and the new name are both supported but where the old name gives a deprecation warning.

**Comment by syclik** [comment]
that seems reasonable.

**Comment by syclik** [comment]
+1 for `stansummary`
