### ISSUE TITLE
rewrite bin/print to not require footer/comments 

### ISSUE THREAD

**Issue by syclik** [stan-dev/cmdstan#50]
[moved from stan-dev/stan#486]

Reported by Bob:
From Marcus (and me informally):

It would be great if we could run bin/print on just a CSV file of samples. That would let us monitor as we go on the CSV file. For online evaluation, it'd be very nice if we could ignore an incomplete last line.

It'd be even nicer if we had something that could connect to tail or something and calculate as we go, rather than having to recalculate bin/print. Then we could have live monitors like BUGS did

**Comment by syclik** [comment]
Using the current version, we can read partial csv files, but not arbitrary csv files. There's some dependence on the header.

The comments can be stripped out and it'll work fine.

**Comment by rok-cesnovar** [comment]
`bin/print` is deprecated so this issue is obsolete.
