### ISSUE TITLE
generate transformed parameters and generated quantities from parameters

### ISSUE THREAD

**Issue by syclik** [stan-dev/cmdstan#513]
_From @bob-carpenter on January 24, 2014 9:58_

Suggestion from John Hall on stan-users:

Provide functionality to read in parameters (say in an output CSV file) and generate the transformed parameters and generated quantities.  

For generated quantities, we should specify a new random seed --- so it won't be totally replicable because the generated quantities are generated interleaved with the other random variates right now.

_Copied from original issue: stan-dev/stan#513_

**Comment by bob-carpenter** [comment]
This is the same as the "rerun generated quantities" block.  No need to regenerate transformed parameters, though, as those are deterministic.

**Comment by mitzimorris** [comment]
this has been implemented - CmdStan has method 'generate_quantities'  -
https://github.com/stan-dev/cmdstan/pull/672
