### ISSUE TITLE
meaningful messages on files not existing

### ISSUE THREAD

**Issue by syclik** [stan-dev/cmdstan#516]
#### Summary:
Provide meaningful messages on exit when files are missing.

#### Description:
When files are missing, produce reasonable messages. The current behavior is to allow the var_context dump reader to fail.

The behavior should be fixed for the data and init files.

This should be fixed in the validation of the arguments. This needs to wait for stan-dev/math#1751.

We should also add a test for this.

#### Current Output:
```
> ./examples/bernoulli/bernoulli sample data file=foo.data.R

Exception: variable does not exist; processing stage=data initialization; variable name=N; base type=int
Diagnostic information: 
Dynamic exception type: std::runtime_error
std::exception::what: variable does not exist; processing stage=data initialization; variable name=N; base type=int
```

#### Expected Output:
```
>  ./examples/bernoulli/bernoulli sample data file=foo.data.R

Can't open specified data file, "foo.data.R"
```

#### Current Version:
v2.12.0

**Comment by rok-cesnovar** [comment]
This has been fixed sometime in between. Cmdstan outputs `Can't open specified file, "foo.data.R"`
