### ISSUE TITLE
Truncation of large parameter values in cmdstan output

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/cmdstan#521]
#### Summary:

Draws of parameter values from Cmdstan are truncated at 6 significant digits, resulting in loss of precision for parameters with values > 1e5 (like `lp__` in models with many observations).

#### Reproducible Steps:
Sample from this model in cmdstan:

```
data {
} 
parameters {
  real theta;
}
model {
  theta ~ normal(1e6, 1);
}
```

#### Current Output:

Draws for `theta` will be discrete, likely: `999997, 999998, 999999,  1e+06`.

#### Expected Output:

`theta - 1e6` should generate draws from a standard normal distribution. 

#### Current Version:
v2.13.1

**Comment by mitzimorris** [comment]
do we have a corresponding issue on stan::io ?
