### ISSUE TITLE
Problems Compiling Bernoulli Example under Windows 7 (64-bits)

### ISSUE THREAD

**Issue by rubgb** [stan-dev/cmdstan#534]
#### Summary:
When executing "make examples/bernoulli/bernoulli.exe" I get the following errors:
g++.exe: error: stan_2.14.0/lib/stan_math_2.14.0/lib/cvcodes_2.9.0/lib/libsundials_nvecserial.a: No such file or directory
g++.exe: error: stan_2.14.0/lib/stan_math_2.14.0/lib/cvcodes_2.9.0/lib/libsundials_cvcodes..a: No such file or directory
#### Description:
I cannot compile the bernoulli example under Windows 7 (64-bits) from the command line getting the error messages stated above. However, I don't have any problems running Stan in R.

#### Current Version:
v2.14.0

**Comment by syclik** [comment]
If that does happen, it's a bug. 

I'll try to verify. In the meantime, try typing `make build` then build the example.

**Comment by rubgb** [comment]
Thanks for the suggestion. After 'make build' I was able to compile the example.

**Comment by rok-cesnovar** [comment]
This has been fixed since. Cmdstan works on windows 64-bit.
