### ISSUE TITLE
Print statement suppressed if initialization fails

### ISSUE THREAD

**Issue by mespe** [stan-dev/cmdstan#546]
#### Summary:

Print statements do not work if the model does not initialize.

#### Reproducible Steps:

`data{}
parameters{
  real<upper=0> phi;
}
model{
  print("phi is: ", phi);
  target += beta_lpdf(phi| 1, 1);
}
`

#### Current Output:

Rejecting initial value:
  Error evaluating the log probability at the initial value.

#### Expected Output:

"phi is: ___"

#### Additional Information:

Using cmdstan 2.15.0. Also present in Rstan 2.15.1

#### Current Version:
v2.15.0

Using both clang v4.0.0 and gcc v6.3.1 20170306

**Comment by bob-carpenter** [comment]
Thanks for filing a clear bug.

@syclik diagnosed this as an underlying Stan issues and it will be fixed as part of https://github.com/stan-dev/stan/issues/2294
