### ISSUE TITLE
is = allowed for dump data?

### ISSUE THREAD

**Issue by tpapp** [stan-dev/cmdstan#548]
In `Appendix C.9 BNF Grammar for Dump Data`, definitions have the form
```
definition ::= name ("<-" | '=') value optional_semicolon
```
but apparently `=` is not accepted, only `<-`. Tested on `2.14.0` and `2.15.0`.

**Comment by bob-carpenter** [comment]
Thanks.  We'll fix that.  Hopefully we'll be able to deprecate the R format and implement the JSON we've had waiting in the wings for years.

**Comment by tpapp** [comment]
JSON would be great (and possibly [Feather](https://github.com/wesm/feather) for the samples — one can dream), but in the short run either removing `=` from the docs or allowing them in the dump data format would be helpful.

**Comment by bob-carpenter** [comment]
Yes, will definitely update the docs.  Thanks for reporting.

**Comment by rok-cesnovar** [comment]
This issue is still relevant. 

@bob-carpenter at this point do we want to support "=" in the R data format or should we just fix the manual?

If we want to support it, I can make a separate PR to fix it. Otherwise I can fix the manual along with other minor manual open issues. Just need someone with more seniority on the project to chime in.

**Comment by seantalts** [comment]
my two cents would be to go ahead and fix it if it's not too hard, unless JSON is faster than rdump now in which case just remove it from the docs and deprecate the whole thing :P

**Comment by rok-cesnovar** [comment]
RapidJSON will be faster definitely, I just need someone to review https://github.com/stan-dev/cmdstan/pull/726 and https://github.com/stan-dev/stan/pull/2803 so we can finally include it. Sorry for the shame less plug/beg for PR reviews :) 

But will play around with a fix.

**Comment by bob-carpenter** [comment]
I'm OK either way.  I don't think we use `=` anywhere and there's no hope of supporting the kind of arbitrary R code that R itself produces with `dump`.
