### ISSUE TITLE
point-and-click instructions for Windows install

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstan#556]
#### Summary:

Transferred from http://discourse.mc-stan.org/t/cmdstan-windows-installation-may-need-extra-steps/725:

On my Windows 7 PC the instructions given in cmdstan-guide-2.15.0 do not seem to be complete, as at least one of the below was required in order to compile successfully. I am not sure which solved the problem, which manifested first as a BSOD and then as incomplete compilation.

1. Turning off antivirus;
2. Installing Rtools to C:\Rtools rather than choosing another directory;
3. After unpacking cmdstan-2.15.0: right clicking on the folder in explorer; selecting properties; clearing the box marked "Read-Only"; and applying to all directories and files.

#### Description:

We should clarify for people who want to point and click.  I don't think there's anyting Windows 7 specific here, just general advice.

#### Current Version:
v2.15.0

**Comment by grinsted** [comment]
Rtools is not an ideal toolchain for CmdStan. CmdStan users are probably not R users, and then Rtools just seems gigantic. 

At the moment the instructions for windows are not solid. How about highlighting that you can use the windows subsystem for linux in the manual (#562). That is what I use on my machine, and it is a reasonably smooth experience.

**Comment by bob-carpenter** [comment]
@grinsted are you suggesting we literally have a section saying "you can use the Windows subsystem for Linux".  Do you think that's enough?

> At the moment the instructions for windows are not solid.

@grinsted Could you be more specific about what is wrong with the instructions?  We can fix them if we know what's wrong, but that's not enough of a hint for us.

> CmdStan users are probably not R users, and then Rtools just seems gigantic.

I think Rtools is just the C++ toolchain.  Of course, they don't say what's in it on the home page, which seems like an oversight.

**Comment by grinsted** [comment]
@bob-carpenter I just tested again and hit #617. I also found the path instructions are incorrect for rtools35 (but easy to fix). 

Regarding toolchain: I also have msys2, cygwin, and some unused remains of MS tools installed. I also what comes with anaconda and julia. My msys64 folder is 1.3Gb. It accumulates. It would be nice if i did not have to install yet another toolchain, and if I did then if it was as minimal as possible. Rtools35 with only 64bit installed is 400Mb. For a windows point-and-click version perhaps cmdstan could be packaged with a c-compiler and make. That would probably also make it easier to support. 

Concerning the WSL: Yes, I think it would be useful with a single sentence saying that this is an alternative method. Atleast as long as the Rtools method is not foolproof.

**Comment by bob-carpenter** [comment]
Thanks.  We'll update the doc.

We're actually thinking along exactly those same lines with respect to providing binary installers.  None of us knows how to do that, but we're trying to hire someone at Columbia to deal with the whole dev ops chain from CI through to release packaging.

**Comment by rok-cesnovar** [comment]
Windows instruction work for 2.20. There were some discussion of alternatives RTools as the recommended way of setting up the toolchain, but that is separate issue.
