### ISSUE TITLE
windows make

### ISSUE THREAD

**Issue by Grillard** [stan-dev/cmdstan#557]
#### Summary and description
Building a STAN program with make using the standard folder separation in the windows console fails with my setup.

i.e. from the examples given with STAN distribution:
```make examples\bernoulli\bernoulli.exe```
produces
```make: *** No rule to make target `examples\bernoulli\bernoulli.exe'.  Stop.```

while running 
```make examples/bernoulli/bernoulli.exe```
Correctly builds the model.

What is weird is that after building the model, the make with the backslash separator changes output:
```
make examples\bernoulli\bernoulli.exe
make: Nothing to be done for `examples\bernoulli\bernoulli.exe'.
```
#### Current Version:
I am using cmdstan v2.15.0 in windows 10 powershell (although this also happens in the normal cmd.exe)
with g++.exe (x86_64-posix-seh, Built by MinGW-W64 project) 4.9.3
and GNU Make version 3.79.1
the c++ compiler and make come from the rtools as suggested from the docs.

I do not know if this is just an issue with my environment, but if not, maybe a heads up in the docs should do the trick.

Thanks!

**Comment by syclik** [comment]
It's actually called out in the documentation. See pg. 10. If there's
something that could be called out more clearly, happy to take suggestions.

I'm not sure how the backslash separator changes on you -- is that
something that powershell does? The standard command shell doesn't do that.

Any suggestions on making that clearer and we can get the doc patched.
Thanks!

**Comment by Grillard** [comment]
I do not see that mentioned in page 10, at least not explicitly. It talks about replacing the .exe, but not the difference between using backslash or slash, Maybe I am missing something?

About the powershell, I get the exact same behaviour in the standard cmd.exe, so I am not sure it is a powershell thing

Anyway, if it helps, I would add it to the end of this paragraph:

> For Windows, replace .stan with .exe.

ie.

> For Windows, replace .stan with .exe, and make sure that the path is given with slashes and not backslashes.

Cheers,
