### ISSUE TITLE
Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by grinsted** [stan-dev/cmdstan#562]
#### Summary:
Poor experience on windows. 

#### Description:
I could not get it to compile using Rtools++. 

I instead used "Bash on Ubuntu on Windows", and followed the linux install instructions. That worked. Mention this new possibility as a possibility in the installation instructions.

-Also Rtools++ may be fine for R users but it sucks having to install this for non R users. It would be great to pick a lighter/minimal toolchain for windows. 

#### Current Version:
v2.16.0

**Comment by syclik** [comment]
Awesome! We're there any special steps you needed to follow to get it working?

**Comment by grinsted** [comment]
I only had to install the windows subsystem for Linux : https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

**Comment by grinsted** [comment]
Note it may be easier now - I just saw these news 2 days ago.. 

https://www.theverge.com/2017/7/10/15949096/ubuntu-windows-10-store-linux-distro-sandbox-available-now
