### ISSUE TITLE
Links to 2.16.0 binaries missing

### ISSUE THREAD

**Issue by akucukelbir** [stan-dev/cmdstan#567]
#### Summary:
On https://github.com/stan-dev/cmdstan/releases/ I typically see the following links for each release.

cmdstan-2.X.0.tar.gz
cmdstan-2.X.0.zip

For some reason, they are missing for 2.16.0.

#### Description:
See summary.

#### Reproducible Steps:
Go to: https://github.com/stan-dev/cmdstan/releases/

#### Additional Information:
I depend on these links in automated builds; the builds fail when the links don't exist (or when they change format).

#### Current Version:
v2.17.0

**Comment by seantalts** [comment]
Fixed

**Comment by akucukelbir** [comment]
Thanks @seantalts !
