### ISSUE TITLE
Links to 2.16 manual are broken

### ISSUE THREAD

**Issue by sakrejda** [stan-dev/cmdstan#568]
#### Summary:
mc-stan.org link to manual is broken

#### Description:
No manual here: https://github.com/stan-dev/cmdstan/releases/download/v2.16.0/cmdstan-guide-2.16.0.pdf

#### Reproducible Steps:
1. Try to figure out if CmdStan can to stand-alone functions.
2. Go to https://github.com/stan-dev/cmdstan/releases/download/v2.16.0/cmdstan-guide-2.16.0.pdf
3. Become irritated that life is hard.
4. Go get breakfast instead

#### Current Version:
v2.16.0

**Comment by seantalts** [comment]
Feel free to tag or assign me to these - I didn't see this until just now for an unrelated thing.

**Comment by seantalts** [comment]
Fixed
