### ISSUE TITLE
bin file missing on OS High Sierra

### ISSUE THREAD

**Issue by Artemissy** [stan-dev/cmdstan#575]
On Mac OS High Sierra (10.13) the bin directory is missing. I downloaded version 2.14 to 2.17 of cmdstan but the error is the same for all versions. 

#### Summary:
Bin file not downloaded on mac 10.13

#### Description:
On Mac OS High Sierra (10.13) the bin directory is missing. I downloaded version 2.14 to 2.17 of cmdstan but the error is the same for all versions. 

#### Reproducible Steps:
I downloaded the zip or tar versions, unzipped them into my matlab folder, renamed to cmdstan-home. 

#### Current Output:
When running a test script I get this as first error message:

Error using StanModel/set.stan_home (line 315)
Does not look like a proper stan setup

Function around line 315: 
if fa.directory
            if exist(fullfile(fa.Name,'makefile'),'file') ...
                  && exist(fullfile(fa.Name,'bin'),'dir')
               self.stan_home = fa.Name;
            else
               % TODO make this message more informative
               error('StanModel:stan_home:InputFormat',...
                  'Does not look like a proper stan setup');
            end

Looking into the finder, the folder cmdstan_home does not have any file or folder called 'bin'

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
Hi @Artemissy,

There isn't a binary distributed with CmdStan. What you want to do is first unzip the zip file and from within the CmdStan directory, run this command:
```
make build
```

That will generate `bin/stanc` and `bin/stansummary` for you. If those don't build, then your toolchain isn't configured correctly, which you'll need for any new Stan program anyway.

Please let me know if that works. Also, what language is the test script in?

**Comment by Artemissy** [comment]
Dear Daniel,

thank you very much. With this command everything worked. I had never compiled a code from source and I just didn't understand from the manual how to do it. I thought downloading and unzipping is enough. Sorry for bothering but thank you very much for your help. The test file was written in matlab.

Kind regards,

Diana Hoffmann
________________________________
Von: Daniel Lee [notifications@github.com]
Gesendet: Mittwoch, 11. Oktober 2017 03:14
An: stan-dev/cmdstan
Cc: Hoffmann, Diana; Mention
Betreff: Re: [stan-dev/cmdstan] bin file missing on OS High Sierra (#575)


Hi @Artemissy<https://github.com/artemissy>,

There isn't a binary distributed with CmdStan. What you want to do is first unzip the zip file and from within the CmdStan directory, run this command:

make build


That will generate bin/stanc and bin/stansummary for you. If those don't build, then your toolchain isn't configured correctly, which you'll need for any new Stan program anyway.

Please let me know if that works. Also, what language is the test script in?

**Comment by syclik** [comment]
@Artemissy, you're welcome! (Sorry... I didn't realize I didn't respond earlier.)
