### ISSUE TITLE
Output from diagnose about R-hat is misleading

### ISSUE THREAD

**Issue by jjramsey** [stan-dev/cmdstan#577]
Line 124 of `cmdstan-2.17.0/src/cmdstan/diagnose.cpp` reads as follows:

    std::cout << "The following parameters had split R-hat less than 1.1:"

However, after that line, the `diagnose` utility prints out the names of parameters whose R-hat value is *greater* than 1.1.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
This should be an easy fix and it's definitely a bug.  

And is `1.1` really the target we want for warnings?

I'm also not clear why this is in `diagnose`---there shouldn't be an R-hat in diagnostic mode.  Or is that the posterior analysis program?

**Comment by jjramsey** [comment]
It's the posterior analysis program.

**Comment by bob-carpenter** [comment]
Thanks.  I was confusing it with diagnostic mode, which checks autodiff with initialization.

**Comment by rok-cesnovar** [comment]
Fixed with #593
