### ISSUE TITLE
Add documentation for the "diagnose" utility of CmdStan

### ISSUE THREAD

**Issue by jjramsey** [stan-dev/cmdstan#578]
I've attached a chapter on the "diagnose" utility to add to the CmdStan guide, so that the utility is no longer documented. It's in LaTeX, but I added the ".txt" extension so that GitHub would upload it.

To include it in the guide, you'd need to add `\include{diagnose}` to `cmdstan-guide.tex`, probably just under the line `\include{stansummary}`.

I'd make a pull request, but that would seem to require permissions that I don't have, (i.e. `git push -u origin feature/issue-578-documentation-for-diagnose-utility` just gets me a 403 Forbidden error).

[diagnose.tex.txt](https://github.com/stan-dev/cmdstan/files/1419405/diagnose.tex.txt)

**Comment by mitzimorris** [comment]
totally awesome!
created this branch and added what you sent:
https://github.com/stan-dev/cmdstan/tree/feature/issue-578-documentation-for-diagnose-utility

**Comment by mitzimorris** [comment]
closing, fixed by https://github.com/stan-dev/cmdstan/pull/579
