### ISSUE TITLE
No -std=c++1y on GCC 4.6

### ISSUE THREAD

**Issue by maedoc** [stan-dev/cmdstan#585]
#### Summary:
I can't build CmdStan 2.17 on Windows.

#### Description:
Following CmdStan 2.17 guide, I installed Rtools33 and issued `make build`, which complains first about missing `clang++`, then `unrecognized command line option '-std=c++1y'`. 

#### Reproducible Steps:

- fresh win 10 x64 VM  (get one [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/))
- install Rtools 33 w/ options as described in cmdstan guide (about `PATH`)
- unzip cmdstan and `make CC=g++ build`

#### Current Output:
```
C:\Users\IEUser\Downloads\cmdstan-2.17.0\cmdstan-2.17.0>make build
clang++: not found
clang++: not found
uname: not found
uname: not found
clang++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src -I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -stdlib=libc++ -DNO_FPRINTF_OUTPUT -pipe  -c -O3 -o bin/cmdstan/stanc.o src/cmdstan/stanc.cpp
make: clang++: Command not found
make: *** [bin/cmdstan/stanc.o] Error 127

C:\Users\IEUser\Downloads\cmdstan-2.17.0\cmdstan-2.17.0>make CC=g++ build
uname: not found
uname: not found
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src -I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -m64 -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -DNO_FPRINTF_OUTPUT -pipe  -c -O3 -o bin/cmdstan/stanc.o src/cmdstan/stanc.cpp
cc1plus.exe: error: unrecognized command line option '-std=c++1y'
make: *** [bin/cmdstan/stanc.o] Error 1
```

#### Expected Output:
```
--- CmdStan v2.17.0 built ---
```

#### Additional Information:

- 2.16 builds ok
- Rtools34 still uses GCC 4.6
- LLVM, TDM-GCC 64 & mingw64 produces hundred lines of C++ linking errors (no gxx personality bla bla) 😓 
- mingw64 cross compilers on centos fail too  😓 
- 🐳 -ized crosscompiler toolchains [e.g. crossbuild](https://github.com/multiarch/crossbuild) really be ideal for this 

#### Current Version:
v2.17.0

**Comment by bgoodri** [comment]
You can probably get by for now by putting

CXXFLAGS += -std=c++0x

into make/local. But g++-4.6 is not going to be adequate for Stan >= 2.18.
You will need to use g++-4.9 from RTools.

On Tue, Nov 14, 2017 at 9:58 AM, marmaduke woodman <notifications@github.com

**Comment by maedoc** [comment]
I was unaware that Rtools33 shipped GCC 4.9.3, a mention of that may be helpful in the guide, e..g that
```
make CC=C:/Rtools/mingw_64/bin/x86_64-w64-mingw32-g++.exe build
```
works

**Comment by Ethiral** [comment]
Hello @maedoc  @bgoodri  I'm facing the same issue 
cc1plus.exe: error: unrecognized command line option '-std=c++1y'
cc1plus.exe: warning: unrecognized command line option "-Wno-unused-local-typedefs" [enabled by default]
How did you resolve this?
Thanks

**Comment by syclik** [comment]
What version of g++ are you using?
