### ISSUE TITLE
cmdstan 2.17.0 unable to compile the program after 'make build' in windows 10

### ISSUE THREAD

**Issue by cmelog** [stan-dev/cmdstan#588]
#### Summary:
I had some issues but finally were able to build the cmdstan-2.17.0 on windows 10. Now I am trying to run the first example, bernoulli but without any success

#### Description:
After a while I was able to get:

--- CmdStan v2.17.0 built ---

But when I am trying to run the bernoulli example I got the following message:

C:\cmdstan-2.17.0>make examples/bernoulli/bernoulli.exe
uname: not found
uname: not found
make: Nothing to be done for `examples/bernoulli/bernoulli.exe'.

#### Reproducible Steps:
I modified the extension of the file 'bernoulli.stan' on the examples folder to 'bernoulli.exe' according to the guide on page 10. 

As I mentioned before I am trying to run the bernoulli example but I got:

make: Nothing to be done for `examples/bernoulli/bernoulli.exe'.

#### Current Output:

make: Nothing to be done for `examples/bernoulli/bernoulli.exe'.

#### Expected Output:
I am supposed to generate a C++ code bernoulli.hpp and the compiled executable. 

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
@cmelog, I now understand your confusion.

1. change the name of the file from `bernoulli.exe` to `bernoulli.stan`
2. then type `make examples/bernoulli/bernouli.exe`

Please let me know if that works.

**Comment by cmelog** [comment]
Hi, I changed the file to bernoulli.stan and got:

C:\cmdstan-2.17.0>make examples/bernoulli/bernouli.exe
uname: not found
uname: not found
make: *** No rule to make target `examples/bernoulli/bernouli.exe'.  Stop.

I am now running Stan from Mathlab and is working, which was my original goal. I am not sure if I should also be able to run on cmdstan

**Comment by Ethiral** [comment]
Hello all,
I'm facing the same issue No rule to make target `C:/Users/EVerma/cmdstan/examples/bernoulli/bernoulli.exe'
How did you resolve this?
Thanks

**Comment by cmelog** [comment]
Hi this is what I did:

1. Installed the newest version of Rtools.
2. On the path I included: C:\Rtools\mingw_64\bin to select the adequate version of the Rtools.
3. I created a local file (no extension)  in the C:\cmdstan-2.17.1\make with the following lines:
CC=g++

I hope this helps.

**Comment by Ethiral** [comment]
What is meant by local file (no extension)?
Thanks in advance

**Comment by syclik** [comment]
Just a file inside the make directory called “local”: should be “make/local” without an extension. Hopefully that adds a little clarification. 

If you wanted to generate the file, you could type:
echo CC=g++ > make/local

And that’ll create the file appropriately.

**Comment by Majeed7** [comment]
Hi,

I have exactly the same problem. Adding the local file did not resolve the problem.

FYI I am working on Windows 7. I attached an snapshot from cmd
![cmdstan](https://user-images.githubusercontent.com/13550419/39761541-abc3f21a-52d8-11e8-96ec-1ee9ef27ca6a.jpg)

**Comment by syclik** [comment]
What's the problem? It says CmdStan 2.17.1 has been built. The uname lines
are just extraneous output. (I haven't been able to suppress it
successfully)
