### ISSUE TITLE
meaningful messages on files not existing

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstan#59]
Right now, if the user provides a file that doesn't exist, they get an error message that one of the variables in the model can't be found (init or data, depending on usage).

What should happen is that we should test that the file exists and return a meaningful message if it doesn't.

I don't know whether this is something that's going to get sorted out automatically in the new command config infrastructure or not.

(I also filed the same issue on RStan.)

**Comment by syclik** [comment]
I'll fix this on the current branch, but it'll need to be reimplemented as part of the refactor.

The fundamental problem here is that the validation done by the arguments isn't actually validating this argument. I think we need to rethink the args. After the refactor, it'll be part of the CmdStan repo.
