### ISSUE TITLE
Need better configuration for C++ standard library options.

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstan#590]
#### Summary:
We'd like to let users easily compile with either gcc's stdlib or llvm's libc++ regardless of which compiler they're using (especially because these libraries are often broken in Ubuntu releases). We should probably also make the default standard library be whichever one comes with your compiler.

#### Current Version:
v2.17.0

**Comment by seantalts** [comment]
@sakrejda @syclik Seems like with `make/local` set to `CC=g++` things work appropriately and it implicitly uses gcc's standard library? e.g.
```
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -DNO_FPRINTF_OUTPUT -pipe  -c -O0 -o bin/stan/lang/grammars/statement_2_grammar_inst.o stan/src/stan/lang/grammars/statement_2_grammar_inst.cpp
```

**Comment by sakrejda** [comment]
Is this the develop branch? I'll check when I get home how it breaks for me (I had to add something in make/local but also edit the makefiles last time I checked...

**Comment by seantalts** [comment]
Yep in develop. Thanks!

**Comment by sakrejda** [comment]
@seantalts if I set CXX=g++ in make/local for cmdstan develop I get:

```
krzysztof@hagrid:~/packages/cmdstan-develop$ make examples/bernoulli/bernoulli
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src -I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -stdlib=libc++ -Wno-unused-function -Wno-uninitialized -DNO_FPRINTF_OUTPUT -pipe  -c -O3 -o bin/cmdstan/diagnose.o src/cmdstan/diagnose.cpp
g++: error: unrecognized command line option ‘-stdlib=libc++’
makefile:86: recipe for target 'bin/cmdstan/diagnose.o' failed
make: *** [bin/cmdstan/diagnose.o] Error 1

```

If I set CC=g++ in make/local I get:

```
krzysztof@hagrid:~/packages/cmdstan-develop$ make examples/bernoulli/bernoulli
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src -I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -DNO_FPRINTF_OUTPUT -pipe  -c -O3 -o bin/cmdstan/diagnose.o src/cmdstan/diagnose.cpp
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src -I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -DNO_FPRINTF_OUTPUT -pipe -lpthread  -O0 -o bin/diagnose bin/cmdstan/diagnose.o
Compiling pre-compiled header
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src -I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -DNO_FPRINTF_OUTPUT -pipe  -c -O3 stan/src/stan/model/model_header.hpp -o stan/src/stan/model/model_header.hpp.gch

--- Linking C++ model ---
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src -I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -DNO_FPRINTF_OUTPUT -pipe -lpthread  -include-pch stan/src/stan/model/model_header.hpp.gch -O3 -o examples/bernoulli/bernoulli src/cmdstan/main.cpp -include examples/bernoulli/bernoulli.hpp stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_cvodes.a
cc1plus: fatal error: -pch: No such file or directory
compilation terminated.
make/models:14: recipe for target 'examples/bernoulli/bernoulli' failed
make: *** [examples/bernoulli/bernoulli] Error 1
```

The second one is the bug you have a PR for IIRC.  What's confusing about all this is that we actually include make/local _twice_ in the cmdstan makefile.  The first include is before we run math's make/detect_cc make/detect_os so that makes it work I guess, and it's also before we set CXX from CC.  ... didn't we recently change to CXX (?)

**Comment by seantalts** [comment]
Ah yeah, I think there should only be one include for `make/local`. My sloppiness, apologies. 

We switched to CXXFLAGS for flags that go to just C++ projects, but didn't switch to just using CXX - for example, we still have non-C++ libraries (sundials) that need to be compiled which will use CC. 

Part of what I want to do with this PR https://github.com/stan-dev/cmdstan/pull/589 is reduce confusion about what flags to use, partially by better doc in the manual but also by removing some of the leftover cruft in the makefile that suggests to someone reading it that they can edit variables there instead of in `make/local`.

**Comment by sakrejda** [comment]
I think we do the right thing for gtest by having gtest-specific cxxflags
and the makefiles would work better if we did that all around.

**Comment by syclik** [comment]
+1. I think we already do?

**Comment by skaffen-amtiskaw** [comment]
This info really needs to be in your install doc.

**Comment by syclik** [comment]
Thanks. We’ve recently changed some of the options and didn’t realize it trickled down to CmdStan. It’ll get fixed soon.

**Comment by seantalts** [comment]
I'm confused - it is actually in the install doc, but I think a lot of people maybe missed it:
![image](https://user-images.githubusercontent.com/805356/33955194-b1c6abe6-e008-11e7-8e04-1138d7b25d8b.png)
(this from cmdstan manual 2.16.0).

Is there something else you want, @skaffen-amtiskaw? Especially besides the stuff already brought up in this thread, like the things addressed in https://github.com/stan-dev/cmdstan/pull/589

**Comment by seantalts** [comment]
Did you mean to close this one, @syclik ? I don't think that commit actually helps people set their stdlib in `make/local`

**Comment by syclik** [comment]
Ah. Misunderstood the meaning of this issue. 

Is it not as simple as setting `CXXFLAGS=...`? Questions:
- Does that not work?
- If it does work, does it need better doc?
- If it does work, should it work in a different way?

I don't think there's a variable for stdlib in our makefiles. Is that what we'd want to add?

**Comment by seantalts** [comment]
I think we need a way to set it individually from the compiler, but I can
double check later.

**Comment by syclik** [comment]
That makes sense. We can add a make variable to control it.

**Comment by syclik** [comment]
Is there a reason we're explicitly setting that for any platform? I'm reading StackOverflow answers and it seems like we shouldn't need to anymore.

**Comment by syclik** [comment]
Here's one of the relevant answers:
https://stackoverflow.com/questions/19774778/when-is-it-necessary-to-use-use-the-flag-stdlib-libstdc

**Comment by seantalts** [comment]
I think on at least some versions of Ubuntu on Travis stdlibc++ (the default) doesn't work and we need to specify `-stdlib=libc++` at least when we're using `clang++` (mentioned [here](https://github.com/stan-dev/math/blob/develop/make/detect_cc#L9). 

But on the other hand, I think everyone complaining about the setting was actually setting `CC=g++` in `makefile` instead of `make/local`. So maybe we don't need this anymore.

**Comment by rok-cesnovar** [comment]
Not an issue in 2.20. Closing.
