### ISSUE TITLE
Many tests broken on Windows

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstan#592]
#### Summary:
I was finally getting around to making Jenkins run the CmdStan tests on Windows as well (on @sakrejda's suggestion) and found that actually CmdStan tests are mostly broken on windows:

[----------] Global test environment tear-down
[==========] 16 tests from 1 test case ran. (508 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 15 tests, listed below:
[  FAILED  ] StanUiCommand.printReallyPrints
[  FAILED  ] StanUiCommand.refresh_zero_ok
[  FAILED  ] StanUiCommand.refresh_nonzero_ok
[  FAILED  ] StanUiCommand.zero_init_value_fail
[  FAILED  ] StanUiCommand.zero_init_domain_fail
[  FAILED  ] StanUiCommand.user_init_value_fail
[  FAILED  ] StanUiCommand.user_init_domain_fail
[  FAILED  ] StanUiCommand.CheckCommand_default
[  FAILED  ] StanUiCommand.CheckCommand_help
[  FAILED  ] StanUiCommand.CheckCommand_unrecognized_argument
[  FAILED  ] StanUiCommand.timing_info
[  FAILED  ] StanUiCommand.run_info
[  FAILED  ] StanUiCommand.random_seed_default
[  FAILED  ] StanUiCommand.random_seed_specified_same
[  FAILED  ] StanUiCommand.random_seed_specified_different

You can see more info in a log here: http://d1m1s1b1.stat.columbia.edu:8080/job/CmdStan/job/PR-591/17/execution/node/57/log/ but I also verified on the Windows machine manually.

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
Thanks, Sean. I'll try to dig over this week.

**Comment by seantalts** [comment]
Woops, I think it was on your suggestion that I did the above, my bad. Gmail tends to get the authors wrong in the emails from git and it slipped by me.

**Comment by syclik** [comment]
No worries... credit doesn't really matter for suggesting things. Doing them matters.

(I didn't really want to suggest it -- I don't like making work for other people.)

**Comment by seantalts** [comment]
✋ thanks again! happy this is all working now.
