### ISSUE TITLE
makefiles broken with allow_undefined option

### ISSUE THREAD

**Issue by wds15** [stan-dev/cmdstan#599]
#### Summary:
make quits with an error when allow_undefined is set

#### Description:
see above

#### Reproducible Steps:
try to compile with allow_undefined set

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.1

**Comment by syclik** [comment]
Mind showing exactly how you're calling make? (I don't know how to set allow_undefined off the top of my head.)

**Comment by wds15** [comment]
just put in you make/local

`STANCFLAGS=--allow_undefined`

and you will trigger the bug when you build any model

**Comment by syclik** [comment]
Thanks! I'll take a look.

**Comment by wds15** [comment]
the `make/models` file has unbalanced parentheses in the if-branch for the case of allow undefined. I only removed the very last ")" and now it works.

**Comment by syclik** [comment]
Great. That means the PR fixes the issue?

**Comment by wds15** [comment]
Yes. Very easy fix. Saw you merged already. Great.
