### ISSUE TITLE
Step size initialization with adapt engaged=0 not working

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstan#602]
#### Summary:
@wds15 found that cmdstan is ignoring stepsizes provided as arguments when num_warmup=0 and adapt engaged=0

#### Description:
For more details: http://discourse.mc-stan.org/t/saved-mass-matrix/2921

#### Current Output:
The step size is being set to 1 and the calculation doesn't work

#### Expected Output:
The step size should be set to what is provided on the command line

#### Current Version:
v2.17.1

**Comment by bbbales2** [comment]
Ah, okay, so we can close this?

**Comment by wds15** [comment]
So I just checked again and here is what happens:

1. for num_warmup=0 and engaged=0 everything is fine
2. for num_warmup=0 and engaged=1 then the stepsize will be set to 1 no matter what the users gives it

I do not think that the second case makes sense. That is, I have disabled any warmup and I still get the stepsize set to unity. The really bad thing is that this is what happens by default!

I suggest to either make this behavior more explicit in the documentation (along with noting that initials should be set as desired for restarting) or we change the behavior under engaged=1 for the case of num_warmup=0. For num_warmup=0 I think that Stan should simply never touch the tuning parameters.

**Comment by bbbales2** [comment]
Had a look at this.

With num_warmup=0, engaged=1, and a specified stepsize, the stepsize indeed gets thrown away and the sampler runs with stepsize=1.

I don't think there's really a valid use case here, so I think this is something we should just address at the interface. Made a pull req. for it https://github.com/stan-dev/cmdstan/pull/604.

The issue is that the Nesterov dual averaging thing never gets any samples, and so it just spits out a 1 when the zero length adaptation window ends (it's this code: https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/nuts/adapt_diag_e_nuts.hpp#L50)

**Comment by rok-cesnovar** [comment]
Fixed in #604
