### ISSUE TITLE
error: unable to open output file 'stan/src/stan/model/model_header.hpp.gch': 'Permission denied'

### ISSUE THREAD

**Issue by idontgetoutmuch** [stan-dev/cmdstan#610]
#### Summary:
`cmdstan` tries to create a file where it is installed but on my computer that is read only.

#### Description:

```
bin/stanc  /var/folders/h1/bkwn2ct12hvb6__dzrk5gwx80000gn/T/stanhs/s3849448837379259560.stan --o=/var/folders/h1/bkwn2ct12hvb6__dzrk5gwx80000gn/T/stanhs/s3849448837379259560.hpp
Model name=s3849448837379259560_model
Input file=/var/folders/h1/bkwn2ct12hvb6__dzrk5gwx80000gn/T/stanhs/s3849448837379259560.stan
Output file=/var/folders/h1/bkwn2ct12hvb6__dzrk5gwx80000gn/T/stanhs/s3849448837379259560.hpp
Compiling pre-compiled header
c++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem stan/src -isystem stan/lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DEIGEN_NO_DEBUG -DNO_FPRINTF_OUTPUT -pipe  -c -O3 stan/src/stan/model/model_header.hpp -o stan/src/stan/model/model_header.hpp.gch
error: unable to open output file 'stan/src/stan/model/model_header.hpp.gch': 'Permission denied'
1 error generated.
```

#### Reproducible Steps:

Install stan as another user and then try to use the installation.

#### Current Output:

See above.

#### Expected Output:

Any stan should compile.

#### Additional Information:

rStan does not exhibit this problem so maybe cmdstan can copy this?

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
It's not the Stan code so much as the makefiles that need to be generalized.  If somebody knows how to do that, it'd be fantastic---we've wanted that feature for a long time.  Maybe the move to cmake by @seantalts and @danluu will make it feasible.

**Comment by seantalts** [comment]
Yeah, I think CmdStan will always create files like `stanc` et al. If you want to `make build` to generate (most of) those before making the directory read-only, that should work. The .pch is probably not made with `make build` right now, though.

**Comment by idontgetoutmuch** [comment]
For us it might be better to see how R handles things. I'm guessing it uses a directory which is advertised as being available for temporary files. The alternative is to use a directory with links to the installed system but which is writable.

I'll let you know how we get on.

**Comment by bob-carpenter** [comment]
Is it just the bin/ directory we're talking about needing to be writeable or are we talking about compiled programs?

**Comment by seantalts** [comment]
Yep. What are your goals here? You could change the makefiles to not use pre-compiled headers as one possible step, but they are compiled once and speed up compilation of models by about 15% (IIRC). You could also just include the pre-compiled headers before making it read-only.

**Comment by idontgetoutmuch** [comment]
We have a domain specific language which compiles to Stan. We want to run the Stan. We call `cmdStan` to do this which is fine if you have installed Stan somewhere writable but we want to package what we have done with nix (https://nixos.org/nix/) and the nix installation is not writable. I am adding @glutamate so he can chip in.

**Comment by seantalts** [comment]
Sweet, it'd be great to have a nix package! I don't think it's unreasonable to say that CmdStan has a compile step that produces binaries, as do most of their packages. I suspect we should be able to deal with CmdStan in the same way, though we could the pre-compiled header to the `build` target so it's easier to build all at once.

**Comment by idontgetoutmuch** [comment]
Did you mean package Stan (and CmdStan) as a nix package? I think we should raise another ticket for that. BTW Stan is _already_ packaged here: https://github.com/NixOS/nixpkgs/blob/482597b4bcd3b532bdfc9e57afa44e5d917f2f28/pkgs/development/compilers/cmdstan/default.nix but I am assuming you mean packaging Stan to use dependencies rather than having all the sources for e.g. sundials?

**Comment by seantalts** [comment]
Ah, no, I didn't mean that, haha. I'm not really sure how that package works but it seems great! This is low-confidence, but it seems like my PR with the proposed fix should fix your problems and allow this package to continue working in nix.

**Comment by idontgetoutmuch** [comment]
Ok - your fix looks promising - it will be a few days before I can try it
