### ISSUE TITLE
dyld issue in compiling example model

### ISSUE THREAD

**Issue by e5c** [stan-dev/cmdstan#612]
#### Summary:
Please provide a short couple sentence summary.

I receiving this new error in cmdstan-2.16 when compiling the example bernoulli model, so removed that and installed cmdstan-2.17.1 on my Mac to see if that would help, yet am running into the same error.

```
$ pwd
/Users/eliza/bin/cmdstan-2.17.1

$ make examples/bernoulli/bernoulli

--- Translating Stan model to C++ code ---
bin/stanc  examples/bernoulli/bernoulli.stan --o=examples/bernoulli/bernoulli.hpp
dyld: lazy symbol binding failed: Symbol not found: __ZNSsC1EOSs
  Referenced from: /Users/eliza/bin/cmdstan-2.17.1/bin/stanc (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libstdc++.6.0.9.dylib

dyld: Symbol not found: __ZNSsC1EOSs
  Referenced from: /Users/eliza/bin/cmdstan-2.17.1/bin/stanc (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libstdc++.6.0.9.dylib

make: *** [examples/bernoulli/bernoulli.hpp] Abort trap: 6
```

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

I'm on Mac OS X 10.13.3, installed the `.tar.gz` from the cmdstan installation page, ran `make build -j4` to install, then ran the above pasted commands.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

Expected output is successful `make` of the model :)

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.1

**Comment by rok-cesnovar** [comment]
I am closing this stale issue. There have been no reports of this issue from Mac users for the last 3 versions. If anyone else is experiencing this feel free to reopen.
