### ISSUE TITLE
R data file parser doesn't recognize lines with comments

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/cmdstan#613]
#### Summary:
data file fails to parse correctly when a line contains comments.

#### Description:
In the simple model 
https://github.com/yizhang-cae/laplace_wos
The input data file 
https://github.com/yizhang-cae/laplace_wos/blob/master/harmonic.data.R
contains comments, and the `cmdstan` parse fails to parse the data.

#### Reproducible Steps:
build the model and run with
```bash
./harmonic sample num_samples=1 algorithm=fixed_param data file=./harmonic.data.R
```
#### Current Output:
```bash
`Exception: variable does not exist; processing stage=data initialization; variable name=m; base type=int  (in '../laplace_wos/harmonic.stan' at line 68)
```

#### Expected Output:
It seems the error is causes by comments in the data file
```R
tolerance <- 0.00001                    # close-to-boundary tolerance
m <- 20                                 # nb. of grids in x-dir
n <- 20                                 # nb. of grids in y-dir
N <- 5000                               # samples to take
                                        # for each solution
```
Successful run requires removing the comments so the data file becomes 
```R
tolerance <- 0.00001
m <- 20
n <- 20
N <- 5000
```

#### Current Version:
Tested on the latest develop branch 
cmdstan: 5b1a3d3
stan: 12f031565
math: 0665998b10

**Comment by mitzimorris** [comment]
agreed it would be nice to have comments - this is a limitation of the stan::io::dump reader.
the appendix of the CmdStan guide specifies the BNF for Stan's custom Rdump parser.
that specification doesn't include comments.
technically, this is a limitation of the stan::io::dump reader.

CmdStan now allows JSON inputs as well - note that JSON doesn't support comments - https://stackoverflow.com/questions/244777/can-comments-be-used-in-json
