### ISSUE TITLE
add MPI cluster init

### ISSUE THREAD

**Issue by wds15** [stan-dev/cmdstan#616]
#### Summary:
Add to cmdstan the possibility to use a MPI cluster in stan-math

#### Description:
In order to take advantage of MPI within-chain parallelization we need to initialize the MPI cluster resource provided by stan-math.

#### Reproducible Steps:
NA

#### Current Output:
NA

#### Expected Output:
NA

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.1

**Comment by rok-cesnovar** [comment]
Done in 2.18.
