### ISSUE TITLE
Building a Stan executable doesn't build the cvodes library automatically in Windows

### ISSUE THREAD

**Issue by syclik** [stan-dev/cmdstan#617]
#### Summary:
From a clean CmdStan install **on Windows**:
```
make examples/bernoulli/bernoulli.exe
```
fails to build.

This was reported on Discourse: [Issue compiling bernoulli example model in cmdstan 2.17](http://discourse.mc-stan.org/t/issue-compiling-bernoulli-example-model-in-cmdstan-2-17/2738)

@seantalts says it's been fixed [here](http://discourse.mc-stan.org/t/issue-compiling-bernoulli-example-model-in-cmdstan-2-17/2738/5), but we should verify.

#### Description:
My guess is that the Windows executable doesn't have a dependency on the library file. We should add that.

#### Reproducible Steps:
See above.

#### Current Version:
v2.17.1

**Comment by grinsted** [comment]
I got this error today strictly following the install instructions from the userguide: 

```
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem stan/src -isystem stan/lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DEIGEN_NO_DEBUG -DNO_FPRINTF_OUTPUT -pipe   -O3 -o examples/bernoulli/bernoulli.exe src/cmdstan/main.cpp -include examples/bernoulli/bernoulli.hpp -include examples/bernoulli/USER_HEADER.hpp stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_cvodes.a
g++.exe: error: stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_nvecserial.a: No such file or directory
g++.exe: error: stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_cvodes.a: No such file or directory
make: *** [makefile:99: examples/bernoulli/bernoulli.exe] Error 1
```

I just installed Rtools35 and downloaded v2.17.1. The "cvodes_2.9.0" folder does not have a "lib" subfolder.

**Comment by syclik** [comment]
I believe there was an error in that released version. I'm not in a
position to check it right now, but mind searching issues for something
about cvodes to see if it's been squashed?

**Comment by druth314** [comment]
I was having similar issues. Any updates on this problem?

**Comment by syclik** [comment]
I'm clearing this issue out. After the makefile fix (#645) was merged, this no longer seems to be a problem.

@grinsted or @druth314, if you see this again using the current versions of everything, please report back!

**Comment by t-student** [comment]
cmdstan-2.18.0>make examples\bernoulli\bernoulli.exe

--- Linking C++ model ---
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.66.0 -isystem stan/lib/stan_math/lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem stan/src -isystem stan/lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DEIGEN_NO_DEBUG -m64 -Wno-unused-but-set-variable -DNO_FPRINTF_OUTPUT -pipe   src/cmdstan/main.cpp -O3 -o examples\bernoulli\bernoulli.exe -include examples\bernoulli\bernoulli.hpp -include examples\bernoulli\USER_HEADER.hpp stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_idas.a
In file included from <command-line>:0:0:
./examples\bernoulli\bernoulli.hpp:343:1: fatal error: examples\bernoulli\USER_HEADER.hpp: No such file or directory

 ^
compilation terminated.
make: *** [makefile:108: examples\bernoulli\bernoulli.exe] Error 1

**Comment by sakrejda** [comment]
@t-student this looks like a different issue (with the makefile).  Can you try this with 2.18.2 and file it separately?

**Comment by sakrejda** [comment]
If you file a separate issue with your current version that's fine.  I'd just check out the `develop` branch to see if it's a current problem anyway (did you use the `develop` branch or just a release (2.18.0?).
