### ISSUE TITLE
SEGV during sampling

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/cmdstan#620]
#### Description:

Program received signal SIGSEGV, Segmentation fault.
0x0000555555568bb3 in stan::math::(anonymous namespace)::subtract_vv_vari::chain() ()
#0  0x0000555555568bb3 in stan::math::(anonymous namespace)::subtract_vv_vari::chain() ()
#1  0x00005555555cfefa in void stan::math::gradient<stan::model::model_functional<model5_model_namespace::model5_model> >(stan::model::model_functional<model5_model_namespace::model5_model> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, double&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&) ()
#2  0x00005555555d010e in void stan::model::gradient<model5_model_namespace::model5_model>(model5_model_namespace::model5_model const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, double&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, stan::callbacks::logger&) ()
#3  0x00005555555d063e in stan::mcmc::base_hamiltonian<model5_model_namespace::model5_model, stan::mcmc::diag_e_point, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >::update_potential_gradient(stan::mcmc::diag_e_point&, stan::callbacks::logger&) ()
#4  0x00005555555d0ce1 in stan::mcmc::base_leapfrog<stan::mcmc::diag_e_metric<model5_model_namespace::model5_model, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > > >::evolve(stan::mcmc::diag_e_point&, stan::mcmc::diag_e_metric<model5_model_namespace::model5_model, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >&, double, stan::callbacks::logger&) ()
#5  0x00005555555fc97a in stan::mcmc::base_nuts<model5_model_namespace::model5_model, stan::mcmc::diag_e_metric, stan::mcmc::expl_leapfrog, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >::build_tree(int, stan::mcmc::ps_point&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, double, double, int&, double&, double&, stan::callbacks::logger&) ()
#6  0x00005555555fcdcc in stan::mcmc::base_nuts<model5_model_namespace::model5_model, stan::mcmc::diag_e_metric, stan::mcmc::expl_leapfrog, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >::build_tree(int, stan::mcmc::ps_point&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, double, double, int&, double&, double&, stan::callbacks::logger&) ()
#7  0x00005555555fcea8 in stan::mcmc::base_nuts<model5_model_namespace::model5_model, stan::mcmc::diag_e_metric, stan::mcmc::expl_leapfrog, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >::build_tree(int, stan::mcmc::ps_point&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, double, double, int&, double&, double&, stan::callbacks::logger&) ()
#8  0x00005555555fcdcc in stan::mcmc::base_nuts<model5_model_namespace::model5_model, stan::mcmc::diag_e_metric, stan::mcmc::expl_leapfrog, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >::build_tree(int, stan::mcmc::ps_point&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, double, double, int&, double&, double&, stan::callbacks::logger&) ()
#9  0x00005555555fdaf1 in stan::mcmc::base_nuts<model5_model_namespace::model5_model, stan::mcmc::diag_e_metric, stan::mcmc::expl_leapfrog, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >::transition(stan::mcmc::sample&, stan::callbacks::logger&) ()
#10 0x00005555555fdc76 in stan::mcmc::adapt_diag_e_nuts<model5_model_namespace::model5_model, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >::transition(stan::mcmc::sample&, stan::callbacks::logger&) ()
#11 0x000055555556d7d7 in void stan::services::util::generate_transitions<model5_model_namespace::model5_model, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >(stan::mcmc::base_mcmc&, int, int, int, int, int, bool, bool, stan::services::util::mcmc_writer&, stan::mcmc::sample&, model5_model_namespace::model5_model&, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> >&, stan::callbacks::interrupt&, stan::callbacks::logger&) [clone .constprop.2752] ()
#12 0x00005555555e3456 in int stan::services::sample::hmc_nuts_diag_e_adapt<model5_model_namespace::model5_model>(model5_model_namespace::model5_model&, stan::io::var_context&, stan::io::var_context&, unsigned int, unsigned int, double, int, int, int, bool, int, double, double, int, double, double, double, double, unsigned int, unsigned int, unsigned int, stan::callbacks::interrupt&, stan::callbacks::logger&, stan::callbacks::writer&, stan::callbacks::writer&, stan::callbacks::writer&) ()
#13 0x000055555560776f in int cmdstan::command<model5_model_namespace::model5_model>(int, char const**) ()

#### Reproducible Steps:
I tried to reproduce this crash by using the same seed, but it doesn't always happen. Would it help to compile with debug symbols and frame pointers?

#### Current Version:
v2.17.1 w/ -O3
gcc Ubuntu 7.3.0-16ubuntu3

**Comment by syclik** [comment]
whoa.

Any information would be useful! Just to verify, you're using the tagged
CmdStan version? Are you able to provide the data and the program so we can
try to pin down where we're running into memory issues?

It looks like there's some problem in the subtraction. Which is really
weird.

Have you done anything to try and debug it? (rebuild the binaries, change
compiler flags, change compilers... perhaps things got into an inconsistent
state?)

**Comment by jpritikin** [comment]
I spent a few hours trying to get a better stack trace using gcc 8.1, but I wasn't able to reproduce the SEGV. I could give you the data and model, but I don't want to waste your time. I'm going to run it overnight. It might be a gcc 7 compiler bug or something.

**Comment by jpritikin** [comment]
> you're using the tagged CmdStan version

Yes, I downloaded the v2.17.1 tarball.

**Comment by syclik** [comment]
Thanks for both pieces of info. Please let us know if we can help track
this down.

**Comment by jpritikin** [comment]
Looks like a compiler bug. Although I ran sampling overnight, I couldn't get it to happen with gcc 8.1.

**Comment by syclik** [comment]
Thanks for following up!
