### ISSUE TITLE
correct doc for Intel compiler

### ISSUE THREAD

**Issue by wds15** [stan-dev/cmdstan#622]
#### Summary:
Not giving the correct option to the intel compiler leads to divergent transitions going unreported (instead of triggering them).

#### Description:
need to correct the doc

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.1

**Comment by maedoc** [comment]
Can you add a detail or two? I'm planning on using icpc with Xeon Phis and would like to avoid this.

**Comment by wds15** [comment]
What do you mean? Just follow the instructions given in the manual to avoid the issue.

... and yes, I was shocked when I learned this a while ago. I was giving a course and people were not able to trigger divergences in Stan when running the 8-schools example in the CP parametrization which has a horrible funnel geometry and lots of divergences. The reason was that people were using the Intel compiler with the defaults which are set such that floating point operations are speed up in a way which leads to non-detection of divergences. So use these -fp-precise options detailed in the manual.

(even better if you would confirm my finding from ~2y back).

**Comment by maedoc** [comment]
> What do you mean? Just follow the instructions given in the manual to avoid the issue.

your description in the issue up top is

> need to correct the doc

so I assumed the manual was not the place to look

> use these -fp-precise options

I think Intel is infamous among numerical analysts & scientists for defaulting to unsafe behavior.  On the other hand, it does a better job vectorizing for wide SIMD workloads.

**Comment by bob-carpenter** [comment]
@maedoc is right here.  This issue needs to be clarified.  

Going forward, I very much want issues to have enough details that a third party can look at them and have enough detail to solve them.  I think this is going to be critical in scaling out to more developers.

**Comment by wds15** [comment]
hmm... I see. This is one of those issue which are filed with the PR solving it, so the description is misleading here since this is already the solution needed to be implemented.

BTW... mind reviewing and merging? Should not take long (unless you want to confirm Intel compiler quirks).

**Comment by maedoc** [comment]
I'll try to reproduce and see if a more subtle set of flags (instead of `-fp-precise`) can eliminate the issue; is the [funnel](https://github.com/stan-dev/example-models/tree/efb4910768e79e923c78abf5829e12233ce73080/misc/funnel) sufficient or need to use exactly the 8-schools CP metnioned above?

**Comment by maedoc** [comment]
In a comparison of g++, icpc with & without `-fp-model precise`, they report similar numbers of divergences.  Maybe icpc has improved recently.

**Comment by wds15** [comment]
which icpc version?

**Comment by maedoc** [comment]
icpc 18.0.2
gcc 4.8.5
cmdstan 2.17.1

**Comment by rok-cesnovar** [comment]
Fixed in #623
