### ISSUE TITLE
documentation should suggest rstan::check_hmc_diagnostics or similar

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/cmdstan#626]
#### Summary:
It took me a while to realized that cmdstan doesn't automatically do anything like rstan::check_hmc_diagnostics

#### Expected Output:
I expected cmdstad to automatically run the diagnostics or suggest that I run them.

#### Current Version:
v2.17.1

**Comment by jjramsey** [comment]
That's what the `diagnose` command is for.

**Comment by jpritikin** [comment]
Oh! Nevermind then.
