### ISSUE TITLE
use AppVeyor to test windows version

### ISSUE THREAD

**Issue by grinsted** [stan-dev/cmdstan#627]
The user experience for windows users is not great at the moment. I just tried following the instructions in the userguide and hit issue #617. I think similar makefile issues could crop up in the future versions unnoticed. -But maybe they could get caught using AppVeyor. This would also be a test of that the recommended install procedure in the userguide is still valid.

**Comment by syclik** [comment]
Mind giving us a summary on what AppVeyor is / does? Are you skilled in it
enough to get this set up? Happy to take contributions!

**Comment by grinsted** [comment]
AppVeyor is a continuous integration tool. It is free and it builds for windows. 

I made a tiny AppVeyor.yml file that attempts to build cmdstan and the bernoulli example using Rtools - it needs to be polished, but it is a starting point. I will make a PR with it shortly.

**Comment by rok-cesnovar** [comment]
We have Windows testing set up on Jenkins for some time now. Closing.
