### ISSUE TITLE
JSON input format/output formats?

### ISSUE THREAD

**Issue by shapenaji** [stan-dev/cmdstan#632]
Per this issue: https://github.com/stan-dev/cmdstan/issues/548

It seems as though JSON input has been a goal for some time. I can't see any other reference to that in the issues, so I thought I'd ask:

When is this planned for? And can we also have alternate output formats?

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
This is a query, not an issue, so I'm closing.  We have a discussion forum for discussing issues before they're concretely defined enough to turn into issues:

http://discourse.mc-stan.org

You can log on with GitHub credentials (or create new ones). The current output discussions is here:

http://discourse.mc-stan.org/t/universal-static-logger-style-output/4851/21

To answer the question, we're more likely to support protobuf in the near term, which would indirectly provide JSON support through protobuf serialization.  But it should be coming before Stan 3, which hopefully means in the next 2 years.
