### ISSUE TITLE
allow include paths to be specified as arguments

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstan#633]
#### Summary:

Add include path argument for calls to stanc to compile models.

#### Description:

There is an argument to `stan::lang::compile` that provides include paths as a `std::vector<std::string>`.  

There should be a way to add include paths from the command line to pass to this function.

Because it has to be passed to the makefile at model compile time, how about an environment variable `STAN_INCLUDE_PATH` that includes a comma-separated lists of absolute or relative paths.   

```
"foo/bar baz/bing",abc,/usr/stan/,""
```

The relative paths will have to be interpreted relative to where stanc is installed because that's where it will be run from.  

#### Current Version:
v2.18.0

**Comment by syclik** [comment]
Currently, make handles the building of the .hpp file and the executable in
one go.

What would be ideal? What you’ve described isnt enough info: it’s an
argument that would need to be provided at compile time.

I can see two ways of handling it:
1. Add a make variable that a user can specify on build. Something that
looks like include_paths. The call would be something like: make
test/bernoulli  include_paths=“foo, bar, baz/bing”. We could even add the
path of the file and . to the include path by default. And users would be
able to add that variable within their make/local.

2. Create instructions for compiling the Stan program (going from Stan to
C++). This would be much clearer as to what’s happening in the build
process, but introduces one additional step in the build process.

Both will need the bin/stanc executable to accept a new argument. I’m happy
with include_paths as the name.

Thoughts?

**Comment by bob-carpenter** [comment]
I forgot that it would have to be before model compile time!  I modified the issue to propose the environment variable approach (suggestion 1).  

I do think we should include "." by default as it's basically assumed in the current implementation that the path can be relative to the location of the CmdStan install.  

If that's still not clear enough, we can keep refining.

I sugggest `STAN_INCLUDE_PATHS` as a "namespace" hack---at least that's what we did for MPI.

**Comment by jjramsey** [comment]
The directory containing the Stan file being compiled (which generally *won't* be the location of the CmdStan install) should also probably be included in the default search path.

**Comment by jjramsey** [comment]
Here's a possible addition to `stanc_helper` that adds additional include paths from a command-line option `--include_paths`. Following the respective conventions for the PATH environment variable on Windows and Unix, the separator of include paths is ";" on Windows and ":" otherwise. So far, it seems to work. 

```
// This is added near the top of stanc_helper.hpp.
#include <boost/algorithm/string/split.hpp>

// This is added just after "" is appended to include_paths in the stanc_helper function.
    if (cmd.has_key("include_paths")) {
#ifdef _WIN32
      std::string inc_path_sep = ";";
#else
      std::string inc_path_sep =  ":";
#endif

      std::string extra_path_str;      
      cmd.val("include_paths", extra_path_str);
      
      std::vector<std::string> extra_path_vec;
      boost::algorithm::split(extra_path_vec,
                              extra_path_str,
                              boost::algorithm::is_any_of(inc_path_sep));

      include_paths.insert(include_paths.end(),
                           extra_path_vec.begin(),
                           extra_path_vec.end());
    }
```

**Comment by mitzimorris** [comment]
@syclik - how exactly do include paths get specified using current makefiles?

**Comment by syclik** [comment]
I don’t understand. What paths? Trying to read your mind: source include
paths or linker paths or path of the target or...?

**Comment by mitzimorris** [comment]
I'm talking about how to compile Stan programs which use the Stan language `include` directive where the included files reside in another directory - how does 
`make foo/bar/stan_program_with_includes` parse out the names of those included directories?

this feature was actually added to CmdStanPy - https://github.com/stan-dev/cmdstanpy/pull/44
I'm just confused looking through the makefiles to see how this works.

**Comment by mitzimorris** [comment]
if the makefiles are working such that Stan programs can includes files from another directory, then we need to add info to the docs.

**Comment by syclik** [comment]
I still don't exactly know what you're looking for... maybe a little more help?

There's some doc in the CmdStan documentation and in the makefile.

https://github.com/stan-dev/cmdstan/blob/develop/makefile#L78
https://github.com/stan-dev/cmdstan/blob/develop/src/docs/cmdstan-guide/stanc.tex#L118

Does that help?

**Comment by mitzimorris** [comment]
yes, that's helpful.   I'm not sure this feature will work as advertised -  do we have makefile tests for this use case?

**Comment by rok-cesnovar** [comment]
Fixed in https://github.com/stan-dev/stan/pull/2635
