### ISSUE TITLE
init=file with only a few parameters specified

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/cmdstan#634]
The command line help says,

````
Initialization method: "x" initializes randomly between [-x, x], "0" initializes to 0, anything else identifies a file of values
````

What happens when I provide a file that only contains inits for a few of many parameters? Do the rest of the parameters get initialized randomly between [-x,x]? If so, can I rely on this behavior? Is it documented anywhere?

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
It's documented in the reference manual, but might not be in the CmdStan doc.

**Comment by mitzimorris** [comment]
closing - the question has been answered.
