### ISSUE TITLE
"make doc" ends in error, fails to put reference manual in doc directory

### ISSUE THREAD

**Issue by jjramsey** [stan-dev/cmdstan#641]
#### Description:
Describe the issue as clearly as possible.

It looks like "make doc" almost works when executed from the root directory of CmdStan, but it fails when it has to execute the following step:

    mv -f src/docs/reference-manual/_book/_main.pdf doc/reference-manual-2.18.0.pdf

When it gets to this point, it fails with the following errors:
```
mv: cannot stat `src/docs/reference-manual/_book/_main.pdf': No such file or directory
stan/make/manual:51: recipe for target 'stan/doc/reference-manual-2.18.0.pdf' failed
make: *** [stan/doc/reference-manual-2.18.0.pdf] Error 1
```

However, while `src/docs/reference-manual/_book/_main.pdf` does not exist, `stan/src/docs/reference-manual/_book/_main.pdf` does, and it appears to have the contents that the reference manual is supposed to have.

#### Current Version:
v2.18.0

**Comment by syclik** [comment]
@jjramsey, thanks for reporting! I'll look into it.

**Comment by bob-carpenter** [comment]
Thanks, and thanks for finding the fix.  We'll be moving this stuff around a bit before the next release and pulling the users guide/Stan book into its own repo.

**Comment by mitzimorris** [comment]
fixed via https://github.com/stan-dev/cmdstan/pull/656
