### ISSUE TITLE
CmdStan has misleading error messages when arguments are misspecified

### ISSUE THREAD

**Issue by jjramsey** [stan-dev/cmdstan#642]
CmdStan provides error messages that provide incorrect advice on how to correct misspecified arguments.

For example, I first try to set `max_depth` via the following command line:

    ../stan_models/rff-fb id=1 data file=curve_data.Rdump output file=output-1.csv max_depth=15

This gets me the following error messages:

    max_depth=15 is either mistyped or misplaced.
    Perhaps you meant one of the following valid configurations?
      method=sample sample algorithm=hmc hmc engine=nuts nuts max_depth=<int>
    A method must be specified!
    Failed to parse arguments, terminating Stan

If I follow this advice by running the following command line,

    ../stan_models/rff-fb id=1 data file=curve_data.Rdump output file=output-1.csv method=sample sample algorithm=hmc hmc engine=nuts nuts max_depth=15

then I get these error messages:

    sample is either mistyped or misplaced.
    Perhaps you meant one of the following valid configurations?
      method=sample sample
    Failed to parse arguments, terminating Stan

However, either of these command lines work:

    ../stan_models/rff-fb id=1 data file=curve_data.Rdump output file=output-1.csv method=sample algorithm=hmc engine=nuts max_depth=15
    ../stan_models/rff-fb id=1 data file=curve_data.Rdump output file=output-1.csv sample algorithm=hmc engine=nuts max_depth=15

One should note that the error messages suggest extraneous arguments, recommending "`method=sample sample`" instead of either `method=sample` or `sample`, "`algorithm=hmc hmc`" instead of just "`algorithm=hmc`", and "`engine=nuts nuts`" instead of just "`engine=nuts`".

Current Version: v2.18.0

**Comment by bob-carpenter** [comment]
Thanks for reporting.  Hopefully we can fix this buggy warning message without pulling the whole interface apart.  

I'd recommend the command skeletons near the end of the CmdStan manual as an indication of the proper calling patterns.

We're likely to just replace this whole nested config thing with something more standard over the next year or two.

**Comment by WardBrian** [comment]
https://github.com/stan-dev/cmdstan/pull/1152
