### ISSUE TITLE
makefiles for MPI are broken

### ISSUE THREAD

**Issue by wds15** [stan-dev/cmdstan#643]
#### Summary:
When enabling MPI, the models are not build with MPI support.

#### Description:
The STAN_MPI (and other MPI settings) are not propagated to the compiler and linker when models are build whenever MPI is turned on. Everything works ok for tests, though.

#### Reproducible Steps:
Put

```
CXX=mpicxx
STAN_MPI=true
```
into `make/local`. Then build cmdstan and then try to build the bernoulli example... the compilation command won't contain a `-DSTAN_MPI` argument such that MPI is not turned on.

#### Current Output:
Like I say... MPI flags don't make it to models which are to be compiled which should be the case.

#### Expected Output:
The MPI flags should be propagated to the compiler whenever the user turns on MPI.

(@syclik the makefile refactor appears to take a moment, so consider this as a quick fix to go in quickly to make things work for a potential short-notice release).

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by syclik** [comment]
@wds15, is this still a problem?

**Comment by wds15** [comment]
This is fixed by now. Thanks for the laundry.
