### ISSUE TITLE
"diagnose" utility doesn't diagnose tree depth problems correctly

### ISSUE THREAD

**Issue by jjramsey** [stan-dev/cmdstan#646]
The problem is in this code (lines 74-93 of src/cmdstan/diagnose.cpp):

    int max_limit = 10;

    if (chains.param_name(i) == std::string("treedepth__")) {
      int max = chains.samples(i).maxCoeff();
      if (max >= max_limit) {
        int n_max = 0;
        Eigen::VectorXd t_samples = chains.samples(i);
        for (long n = 0; n < t_samples.size(); ++n)
          if (t_samples(n) == max) ++n_max;

        std::cout << n_max << " of " << num_samples << " ("
                  << std::setprecision(2)
                  << 100 * static_cast<double>(n_max) / num_samples
                  << "%) transitions hit the maximum treedepth limit of "
                  << max << ", or 2^" << max << " leapfrog steps."
                  << " Trajectories that are prematurely terminated due to this"
                  << " limit will result in slow exploration and you should"
                  << " increase the limit to ensure optimal performance."
                  << std::endl << std::endl;
      }

There are two problems here. First, the maximum tree depth, `max_limit`, is hardcoded to 10 instead of being read from the CSV file. (That probably requires modifying `stan_csv_reader::read_metadata` in order to fix the problem.) Second, and perhaps more importantly, in both the calculation of `n_max` and the error message, the variable `max` is used in place of `max_limit`.

ETA: Plan to fix bug is here: https://discourse.mc-stan.org/t/modifying-stan-csv-reader-to-fix-a-problem-in-cmdstan/5307?u=jjramsey

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
This was fixed.
