### ISSUE TITLE
support JSON for input data files

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#651]
#### Summary:
Add logic to cmdstan so that when the data filename ends in ".json", it uses class `stan::json::json_data` (https://github.com/stan-dev/stan/tree/develop/src/stan/io/json) to read in the data file.

#### Description:
The constructor for a Stan model expects input data in a `var_context`.  The directory `src/stan/io/json` contains all the necessary code.  The remaining piece of the puzzle is adding logic to cmdstan to use it.

The wiki page https://github.com/stan-dev/stan/wiki/JSON-for-model-data-and-parameters contains definitions and examples of the JSON format used by the `stan::json::json_data` class.

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
Could you point to the JSON format that's going to be used?  I know it's implicit in the `var_context`, but it's also relevant for this issue.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/stan/wiki/JSON-for-model-data-and-parameters

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstan/pull/652
