### ISSUE TITLE
Bernoulli Example does not compile on windows 10 - USER_HEADER.hpp: No such file or directory (again?)

### ISSUE THREAD

**Issue by t-student** [stan-dev/cmdstan#655]
#### Description:
Following on from  "Building a Stan executable doesn't build the cvodes library automatically in Windows #617"

Current version of cmdstan (production release https://github.com/stan-dev/cmdstan/releases/download/v2.18.0/cmdstan-2.18.0.tar.gz) fails to compile bernoulli example on windows 10. 

C:\Users\mjones\programs\cmdstan-2.18.0>cat make\local
CXX=g++
CC=g++
STANCFLAGS = --allow_undefined

C:\Users\mjones\programs\cmdstan-2.18.0>make C:\Users\mjones\programs\cmdstan-2.18.0\examples\bernoulli\bernoulli.exe

--- Linking C++ model ---
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.66.0 -isystem stan/lib/stan_math/lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem stan/src -isystem stan/lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DEIGEN_NO_DEBUG -m64 -Wno-unused-but-set-variable -DNO_FPRINTF_OUTPUT -pipe   src/cmdstan/main.cpp -O3 -o C:\Users\mjones\programs\cmdstan-2.18.0\examples\bernoulli\bernoulli.exe -include C:\Users\mjones\programs\cmdstan-2.18.0\examples\bernoulli\bernoulli.hpp -include C:\Users\mjones\programs\cmdstan-2.18.0\examples\bernoulli\USER_HEADER.hpp stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_idas.a
In file included from <command-line>:0:0:
C:\Users\mjones\programs\cmdstan-2.18.0\examples\bernoulli\bernoulli.hpp:343:1: fatal error: C:\Users\mjones\programs\cmdstan-2.18.0\examples\bernoulli\USER_HEADER.hpp: No such file or directory

 ^
compilation terminated.
make: *** [makefile:108: C:\Users\mjones\programs\cmdstan-2.18.0\examples\bernoulli\bernoulli.exe] Error 1

C:\Users\mjones\programs\cmdstan-2.18.0>make bin\stanc
make: Nothing to be done for 'bin\stanc'.

C:\Users\mjones\programs\cmdstan-2.18.0>

I have tried without the STANCFLAGS = --allow_undefined. It makes no difference to outcome.

Am going to try dev release now.

#### Reproducible Steps:
See above

#### Current Version:
v2.18.0

**Comment by sakrejda** [comment]
@t-student I haven't gotten this to replicate on Linux and I don't have access to Windows, did you get a chance to check the `develop` branch on Windows?

**Comment by reuning** [comment]
For what it is worth I am having the same problem on a windows computer. 

```
(cmdstan) C:\Users\reunink\cmdstan>make examples\bernoulli\bernoulli.exe

--- Linking C++ model ---
g++ -std=c++1y -m64 -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs     -O3 -I src -I stan/src -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.66.0 -I stan/lib/stan_math/lib/sundials_4.1.0/include  -D_USE_MATH_DEFINES  -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION            -include examples\bernoulli\user_header.hpp -include examples\bernoulli\bernoulli.hpp src/cmdstan/main.cpp  -static-libgcc -static-libstdc++      stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_idas.a  -o examples\bernoulli\bernoulli.exe
cc1plus.exe: fatal error: examples\bernoulli\user_header.hpp: No such file or directory
compilation terminated.
make: *** [make/program:37: examples\bernoulli\bernoulli.exe] Error 1
```

This is with the most current version, just pulled from the develop branch.

**Comment by syclik** [comment]
Can you try the make command with forward slashes instead of back slashes?

**Comment by reuning** [comment]
Same thing: 

```
(cmdstan) C:\Users\reunink\cmdstan>make examples/bernoulli/bernoulli.exe

--- Linking C++ model ---
g++ -std=c++1y -m64 -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs     -O3 -I src -I stan/src -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.66.0 -I stan/lib/stan_math/lib/sundials_4.1.0/include  -D_USE_MATH_DEFINES  -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION            -include examples/bernoulli/user_header.hpp -include examples/bernoulli/user_header.hpp -include examples/bernoulli/bernoulli.hpp src/cmdstan/main.cpp  -static-libgcc -static-libstdc++      stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_idas.a  -o examples/bernoulli/bernoulli.exe
cc1plus.exe: fatal error: examples/bernoulli/user_header.hpp: No such file or directory
compilation terminated.
make: *** [make/program:37: examples/bernoulli/bernoulli.exe] Error 1
```

gcc info if it helps:

```
(cmdstan) C:\Users\reunink\cmdstan>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/Users/reunink/AppData/Local/Continuum/anaconda3/envs/cmdstan/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-5.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --with-gxx-include-dir=/mingw64/include/c++/5.3.0 --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-version-specific-runtime-libs --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev5, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 5.3.0 (Rev5, Built by MSYS2 project)
```

**Comment by syclik** [comment]
Ahh. I don't know where you got that compiler, but it isn't the immediate
problem.

Can you remove this line from make/local?

STANCFLAGS = --allow_undefined

**Comment by reuning** [comment]
That appears to have fixed it. 

Sorry been trying to get this to work for like 24 hours using different setups. FWIW I was initially following the info on here https://discourse.mc-stan.org/t/cant-make-cmdstan-2-18-in-windows/5088/21 

Not really sure why it works now but it does.

**Comment by syclik** [comment]
So sorry it took so long to get started.

That flag allows you to declare a function in the Stan language without
defining it. It forces the build process to include a header file called
user_header.hpp, but it's clearly failing with an uninterpretable message
when that's not available.

I know it's a bit late, but I hope that helps.

**Comment by reuning** [comment]
Don't worry. I have cmdstan running already on my mac just needed to get it setup on my work windows computer and didn't think it would be as hard as it was. Thanks for the help.

**Comment by rok-cesnovar** [comment]
Cmdstan works on windows now.
