### ISSUE TITLE
Move cmdstan docs to `docs` repo

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#657]
#### Summary:
Remove source files for Stan documentation set from repo src/docs and remove related make tasks.

#### Description:
See https://github.com/stan-dev/stan/issues/2706

The cmdstan docs are still in latex format; they should be converted to Rmarkdown/gitbook.
There are two ugly dependencies between cmdstan and stan:
*  the cmdstan latex files use the stan latex templates and styles.
* the make tasks try to build the Cmdstan docs as well.

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
@mitzimorris is this issue still relevant? I am not completely sure if the intention here was to also move the cmdstan manual?

**Comment by mitzimorris** [comment]
yes, this issue is still relevant.
the current manual needs to be changed to Rmd format in the docs repo.  once we have it in the docs repo,  we can remove it from CmdStan.

this one will take some work because of the fancy use of latex to display info - it needs to be checked for accuracy and could stand some copy-editing as well.

**Comment by rok-cesnovar** [comment]
Thank you for the clarification. Makes sense to me now :)

**Comment by ryan-richt** [comment]
Hello! Is the compiled version of the docs a la cmdstan-guide-version.pdf intended to be available on the website anymore? It doesn't seem to be referenced any longer on either https://mc-stan.org/users/documentation/ or https://mc-stan.org/users/interfaces/cmdstan.html
Though it does exist here: https://github.com/stan-dev/cmdstan/releases/tag/v2.21.0

**Comment by mitzimorris** [comment]
yes, it is intended to be available - thanks for pointing this out - I'll fix the docs pages accordingly.

**Comment by mitzimorris** [comment]
PR #908  - closing
