### ISSUE TITLE
Random seed of 0 accepted, yields same results as random seed 1

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/cmdstan#658]
#### Summary:

According to ``help-all`` a random seed of 0 is invalid. Not only is it accepted, it seems to be equivalent to specifying a random seed of 1.

#### Reproducible Steps:
```bash
examples/bernoulli/bernoulli sample random seed=0 data file=examples/bernoulli/bernoulli.data.R output file=output-seed-0.csv
examples/bernoulli/bernoulli sample random seed=1 data file=examples/bernoulli/bernoulli.data.R output file=output-seed-1.csv
diff output-seed-0.csv output-seed-1.csv
```

#### Current Version:
v2.18.0

**Comment by riddell-stan** [comment]
Happy to submit a PR if someone tells me what the desired behavior is.

**Comment by mitzimorris** [comment]
I see the fix that's needed - the cmdstan argument parser allows any int value.
the fix is to add function "is_valid" to file 'cmdstan/arguments/arg_seed.hpp'
will do ASAP.

**Comment by mitzimorris** [comment]
fixed by https://github.com/stan-dev/cmdstan/pull/695
