### ISSUE TITLE
Looks like a bug in your release scripts

### ISSUE THREAD

**Issue by elbamos** [stan-dev/cmdstan#662]
#### Summary:
2.18.1 release is just your release scripts, without cmdstan.

#### Description:
The contents of the .tar.gz file do not include the release, just release-scripts. 

#### Reproducible Steps:
Download release 2.18.1.  Attempt to install it. 

#### Current Output:
[aelberg:/Volumes/ShareData/LIBRARIES] $ tar -xzvf ./cmdstan-2.18.1.tar.gz
x cmdstan-2.18.1/.gitignore
x cmdstan-2.18.1/README.md
x cmdstan-2.18.1/clean-up.sh
x cmdstan-2.18.1/historic-performance/performance-jenkins-2.5.csv
x cmdstan-2.18.1/historic-performance/performance-jenkins-2.5.pdf
x cmdstan-2.18.1/historic-performance/plot_performance.R
x cmdstan-2.18.1/historic-performance/run_tags.sh
x cmdstan-2.18.1/historic-performance/src/logistic.data.R
x cmdstan-2.18.1/historic-performance/src/logistic.stan
x cmdstan-2.18.1/historic-performance/src/logistic_test.cpp
x cmdstan-2.18.1/historic-performance/src/runTests.py
x cmdstan-2.18.1/historic-performance/src/tests
x cmdstan-2.18.1/historic-performance/src/utility.hpp
x cmdstan-2.18.1/jenkins/agent/Dockerfile
x cmdstan-2.18.1/jenkins/create-cmdstan-pull-request.sh
x cmdstan-2.18.1/jenkins/create-stan-pull-request.sh
x cmdstan-2.18.1/release-scripts/README.md
x cmdstan-2.18.1/release-scripts/functions.sh
x cmdstan-2.18.1/release-scripts/tag-cmdstan.sh
x cmdstan-2.18.1/release-scripts/tag-math.sh
x cmdstan-2.18.1/release-scripts/tag-stan.sh

#### Expected Output:
A bunch of files that can be compiled.

#### Current Version:
v2.18.1

**Comment by seantalts** [comment]
Should be fixed, thanks!
cc @mitzimorris

**Comment by elbamos** [comment]
Hey no big deal, life goes on
