### ISSUE TITLE
Can't compile 2.18.1 on OS  X Mojave 19.14.2

### ISSUE THREAD

**Issue by fprimeau** [stan-dev/cmdstan#667]
#### Summary:
Compilation failed at link stage. 

#### Description:
The final error was the following:

ar: creating archive bin/cmdstan/libstanc.a
/opt/local/bin/ranlib: object: bin/cmdstan/libstanc.a(expression_grammar_inst.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
make: *** [bin/cmdstan/libstanc.a] Error 1

#### Reproducible Steps:
make build

#### Additional Information:
@elbamos reported a similar problem ~1.5 weeks ago and closed the issue stating that the problem had to do with a competing version of ar, but I don't know how to fix such a problem.

#### Current Version:
v2.18.1

**Comment by fprimeau** [comment]
**Summary**
The compilation failed at the link stage.
**Description**
The final error was the following:

ar: creating archive bin/cmdstan/libstanc.a
/opt/local/bin/ranlib: object: bin/cmdstan/libstanc.a(expression_grammar_inst.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
make: *** [bin/cmdstan/libstanc.a] Error 1

**Reproducible Steps**
make build

**Additional Information**
@elbamos reported a similar problem ~1.5 weeks ago and closed the issue stating that the problem had to do with a competing version of ar, but I don't know how to fix such a problem.

**Comment by rok-cesnovar** [comment]
I am closing this stale issue. If anyone on a Mac is experiencing the same issue, please feel free to re-open.
