### ISSUE TITLE
Pull in threading and MPI documentation into CmdStan manual

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstan#678]
#### Summary:
Need to pull in doc from wiki so we can have it appropriately versioned and all in one place.

#### Description:
Currently the installation docs for setting CmdStan up with threading and MPI exist in wiki pages that are linked to from the CmdStan manual, but these wiki pages are not versioned, and we're approaching the point at which that will become a problem as we think about changing how we do threading in a new version.

We'll need to pull that doc in from the wiki into the CmdStan guide pdf. That way, we will archive the instructions for each release with that version's manual. A side benefit will be that all doc is in one place and available offline.

#### Current Version:
v2.18.1

**Comment by wds15** [comment]
BTW, I actually concur with @SteveBronder here in that optional stuff maybe not need that detail of doc as to how to use it. At least what he writes reminds me on what I was thinking at the time when introducing MPI.

What I think we agreed on with MPI is giving basic instructions which work in most cases (for example, what worked on your developer machine). In addition I gave instructions on the wiki on where to find a hello world example for MPI such that people can verify that they have a working system. I do think that we are really not in charge for providing bullet-proof install instructions for anything that is optional. However, giving some docs and pointers is a nice service for our users. After all we want happy users, right?

For MPI I was always able to say "just use threading" which is not an option for you.

**Comment by SteveBronder** [comment]
Yeah I think Sean cleaned this up in the meeting today. Instead of install instructions we should have docs on the compiler flags to use. @wds15 I'm going to fix up the GPU cmdstan doc tonight and can add the compile flags to the mpi and threading stuff as well.

**Comment by seantalts** [comment]
Oops, we talked about this just now in the meeting but I didn't mean we had to include install instructions for other people's software (e.g. MPI, OpenCL). Just that we had to include the instructions for our own software and list the external requirements and mention they can find install instructions for those elsewhere. So in this case we should say how to use `-DSTAN_OPENCL` etc.

**Comment by SteveBronder** [comment]
or you can just slam those into my pr if you have time

**Comment by rok-cesnovar** [comment]
Fixed in #677
