### ISSUE TITLE
cmdstan manual out of date

### ISSUE THREAD

**Issue by wds15** [stan-dev/cmdstan#679]
#### Summary:
The list of tested libraries (and compilers, I think) is out of date.

#### Description:
We list boost 1.58.0 as being tested with 2.18.1 while 2.18.1 is deployed with 1.66.0. The other versions need to be checked.

#### Current Version:
v2.18.1

**Comment by bob-carpenter** [comment]
@mitzimorris has been dealing with doc for this, so I'm assigning this one to her and prioritizing it for the next release.

**Comment by mitzimorris** [comment]
will do all cleanups necessary for next release.

**Comment by mitzimorris** [comment]
@seantalts tested on mojave?
https://github.com/stan-dev/cmdstan/blob/735f003521a414f710681c3b7cc8ea451f62e718/src/docs/cmdstan-guide/installation.tex#L23

**Comment by mitzimorris** [comment]
updated docs, released.
