### ISSUE TITLE
[blocking 2.19] Building the CmdStan manual is broken on develop

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstan#680]
#### Summary:
Looks merging Stan PR https://github.com/stan-dev/stan/pull/2719 broke this.

errors: https://circleci.com/gh/stan-dev/cmdstan/183

#### Current Version:
v2.18.1

**Comment by bob-carpenter** [comment]
Fixed with  https://github.com/stan-dev/cmdstan/pull/681
