### ISSUE TITLE
use model base class for standalone compilation

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstan#712]
#### Summary:

Replace use of templated type in command.hpp with a call to a factory method defined in the generated model class:

```
stan::model::model_base&
new_model(stan::io::var_context& data_context,
    unsigned int seed,
    std::ostream* msg_stream);
```

This depends on `stan-dev/stan` issue https://github.com/stan-dev/stan/issues/2759, which takes care of adding a virtual base class, a CRTP extension, and generating appropriate model code. 

#### Current Output:

Is fine.

#### Expected Output:

Should not change.

#### Current Version:
v2.19.1

**Comment by bob-carpenter** [comment]
Model compilation is now taking 7s on my machine, including linking!

To try it yourself, check out branches:

* stan-dev/cmdstan branch: `feature/0712-model-base-class`
* stan-dev/stan branch:  `feature/2759-model-base`

The issues have the matching numbers.  Use the stan branch to generate appropriate `.hpp` files.

Here's how to compile from the top-level `cmdstan` directory, the various bits.  Make sure to put the generated .hpp file in the right place.

```
# build command (carpenter: 34s on my macbook)
time clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -O3 -I src -I stan/src -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.69.0 -I stan/lib/stan_math/lib/sundials_4.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -c src/cmdstan/main.cpp

# precompiled header for models  (carpenter: 30s, 10s on my macbook)
time make O=3 stan/src/stan/model/model_header.d
time make O=3 stan/src/stan/model/model_header.hpp.gch

# build model (12s w/o precompiled header; 7s with)
cp src/cmdstan/big_norm.hpp src/cmdstan/big_norm.cpp
time clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -O3 -include-pch stan/src/stan/model/model_header.hpp.gch -I src -I stan/src -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.69.0 -I stan/lib/stan_math/lib/sundials_4.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -c src/cmdstan/big_norm.cpp

# link
clang++ -o big_norm main.o big_norm.o
```

**Comment by bob-carpenter** [comment]
For discussion, see https://discourse.mc-stan.org/t/separate-compilation-of-model-and-services-code-complete/9565

**Comment by mitzimorris** [comment]
just updated the makefile and rulesfile `make/program`  - works on my machine.

**Comment by mitzimorris** [comment]
> Here's how to compile from the top-level `cmdstan` directory, the various bits. Make sure to put the generated .hpp file in the right place.

this didn't actually work - perhaps not all of the sequence of session commands was captured?

**Comment by mitzimorris** [comment]
@bob-carpenter I edited some comments, so please click through to issue from your email.

**Comment by bob-carpenter** [comment]
> I think some steps were omitted from the console snippets given above.

Those were ones I was just cutting and pasting.  What failed when you tried it and what did you need to add to get it to work?

> I'm not sure whether the difference in the 7s reported by Bob is due to different compile commands or the fact that his machine has faster processors. and testing on a different model,

The sundials and MPI libs are binaries, so I hope they don't add a lot to compile time.  I don't know what `LBLIBS` is.

1.  To check if it's machine effect, can you compare new compile times vs. old compile times on your machine?

2. Did the precompiled headers get included?  In my example, I had 12s compile times w/o precompiled headers and 7s with.

**Comment by mitzimorris** [comment]
on my machine, bernoulli model under CmdStan 2.19.1 takes 23 sec to compile executible from bernoulli.hpp.

for this PR,  the makefile rule that goes from .hpp file to executable takes 10 sec.

the makefile, as written, also generates a .d file - this takes 1-2 seconds on my machine.  is this necessary?    @syclik - do the Stan model files need a dependencies file?

**Comment by mitzimorris** [comment]
found my error - precompiled headers are needed at compile time, not link time.
fixed and pushed.

bernoulli model, going from .hpp to executible:  now 7 secs, (2.19.1 is 23 seconds).
slightly larger model (bym2), now 9 secs, (2.19.1 is 28).

**Comment by goedman** [comment]
Bob, where is big_norm.hpp coming from? Just any model your using to test this on?

**Comment by bob-carpenter** [comment]
Yes, big_norm.hpp was just a simple example model.

**Comment by mitzimorris** [comment]
addressed via PR https://github.com/stan-dev/cmdstan/pull/713
