### ISSUE TITLE
Does cmdStan allocate space for output files?

### ISSUE THREAD

**Issue by s144117** [stan-dev/cmdstan#714]
Hi,

I have had a sampler run for the past week, 50% done at the moment.
Yesterday I ran out of space on my partition of the computer, didn't realize it.
As a result some more simple runs threw an error when using the `diagnose` function.
I discovered the sampler had continued but no samples had been stored in the output file.
I am not worried about the short runs. But the one that has been running for a week is slightly concerning me. To be safe I could restart, but I don't want to unless it is necessary.

My question is:
Does cmdStan allocate space for the output-file, such that in case of memory shortage it can continue?

Thanks in advance!

#### Current Version:
v2.19.1

**Comment by seantalts** [comment]
There's no space allocated ahead of time, no. And there's currently no way
to "continue" sampling from that exact chain, but you can change the random
seed and start sampling again and those should be from the same
distribution as the ones you already have, meaning you can concat them all
together and treat them all as draws from the posterior as long as the
posterior is ergodic and NUTS is working correctly anyway (you can run some
necessary but not sufficient diagnostic checks on that like rhat,
divergences, BFMI energy, etc) to try to be sure about it.
