### ISSUE TITLE
Error compiling stansummary.o

### ISSUE THREAD

**Issue by jmcoglianese** [stan-dev/cmdstan#721]
#### Summary:
I'm setting up cmdstan on a linux server and running into an issue compiling it. When I try "make build", it throws an error when compiling stansummary.o related to the 'is_nan' function (full details below). 

#### Description:
I initially tried compiling a model without running 'make build' first, and ran into the same error. I also tried building from the released source tar.gz on Github (both versions 2.19.1 and 2.20.0). I deleted all of those files and am now starting from scratch with 'git clone ... --recursive' to use the most up-to-date version. See the steps to reproduce below. 

#### Reproducible Steps:
1. Clone the repository (with '--recursive')
2. Update with 'make stan-update'
3. Run 'make build'

#### Current Output:
Here is the relevant output related to the error: 
```
stan/lib/stan_math/stan/math/prim/scal/err/check_not_nan.hpp:17:31: note: candidate is:
In file included from stan/lib/stan_math/stan/math/prim/scal/err/check_not_nan.hpp:8:0,
                 from stan/lib/stan_math/stan/math/prim/mat/err/check_pos_definite.hpp:6,
                 from stan/lib/stan_math/stan/math/prim/mat/err/check_corr_matrix.hpp:7,
                 from stan/lib/stan_math/stan/math/prim/mat.hpp:12,
                 from stan/src/stan/mcmc/chains.hpp:5,
                 from src/cmdstan/stansummary.cpp:5:
stan/lib/stan_math/stan/math/prim/scal/fun/is_nan.hpp:19:13: note: template<class T, class> bool stan::math::is_nan(T)
 inline bool is_nan(T x) {
             ^
stan/lib/stan_math/stan/math/prim/scal/fun/is_nan.hpp:19:13: note:   template argument deduction/substitution failed:
make: *** [bin/cmdstan/stansummary.o] Error 1
```

#### Expected Output:
I was expecting cmdstan to compile without errors. 

#### Additional Information:
g++ --version: g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
make --version: GNU Make 3.82 Built for x86_64-redhat-linux-gnu

#### Current Version:
v2.20.0

**Comment by seantalts** [comment]
Can you try again with GCC 4.9.3+? That's our minimum supported GCC
version. Thanks!

**Comment by jmcoglianese** [comment]
I can't change the gcc version since it's a university-managed server unfortunately. I'll close the issue since it sounds like it's just a matter of having the right version. It would be great to upgrade the documentation, though, I thought I would be fine since it said you only needed g++ 4.2.1 or higher.

**Comment by seantalts** [comment]
You can often install a new compiler and toolchain in your home directory and set CXX to that.

I'll submit a pull request to update the version. We take them from anyone too, if you wanted to get involved :)
