### ISSUE TITLE
Default Random Seed Doesn't Work As Expected

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/cmdstan#722]
#### Description:

Default random seed of -1 returns consistent results for each evaluation and not the varying results expected by the documentation and tests.  This is causing upstream tests to fail blocking development of the core Stan code.

#### Reproducible Steps:

./runCmdStanTests.py src/test/interface/command_test.cpp

fails for the v2.20.0 tag [OS X 10.12.6, Apple LLVM version 9.0.0 (clang-900.0.39.2)].

The behavior can also be reproduced by running a model, say
```
parameters {
  real x[50];
}

model {
  x ~ normal(0, 1);
}
```
with default settings and examining the resulting output.csv files.

#### Current Output:

Failing tests.

#### Expected Output:

Not failing tests.

#### Additional Information:

I can't find any documentation in the Boost online docs or the 1.69 code currently in Stan that states that seed=-1 yielding random behavior is supported so I can't verify expected behavior.

#### Current Version:
v2.20.0

**Comment by rok-cesnovar** [comment]
That might explain recent fails on develop (see last comment in https://github.com/stan-dev/math/pull/1296)

**Comment by betanalpha** [comment]
Yeah, it’s definitely blocking stan pull requests so it should also be
blocking math pull requests via the same upstream tests.

**Comment by rok-cesnovar** [comment]
Are you seeing this on 2.20 and also on develop or just develop?

**Comment by betanalpha** [comment]
I’m seeing this on develop but I most thoroughly
verified on v2.20.0 where I could align all of the 
repos with the tag (and where the code was
supposed to be in a good state).

Boost doesn’t seem to have been touched,
so I’m not sure why the RNG behavior would
have changed.  Regardless the test may be
relying on undefined behavior, at least for
Boost 1.69.

**Comment by rok-cesnovar** [comment]
Can confirm this test fails if you run it on 2.20 tar from the releases tab. The question is how did this ever pass tests?

**Comment by rok-cesnovar** [comment]
Its getting late so just putting out my findings so far: 

After 5f13b7c8196a1214efe753362886589f5f01198c (merge of PR #695) I am seeing the following errors: 
```
[ RUN      ] StanUiCommand.random_seed_default
[       OK ] StanUiCommand.random_seed_default (7 ms)
[ RUN      ] StanUiCommand.random_seed_specified_same
[       OK ] StanUiCommand.random_seed_specified_same (7 ms)
[ RUN      ] StanUiCommand.random_seed_specified_different
[       OK ] StanUiCommand.random_seed_specified_different (6 ms)
[ RUN      ] StanUiCommand.random_seed_fail_1
src/test/interface/command_test.cpp:455: Failure
Expected equality of these values:
  1
  count_matches(expected_message, out.body)
    Which is: 0
[  FAILED  ] StanUiCommand.random_seed_fail_1 (6 ms)
[ RUN      ] StanUiCommand.random_seed_fail_2
src/test/interface/command_test.cpp:475: Failure
Expected equality of these values:
  1
  count_matches(expected_message, out.body)
    Which is: 0
[  FAILED  ] StanUiCommand.random_seed_fail_2 (7 ms)
[ RUN      ] StanUiCommand.random_seed_fail_3
src/test/interface/command_test.cpp:497: Failure
Expected equality of these values:
  1
  count_matches(expected_message, out.body)
    Which is: 0
[  FAILED  ] StanUiCommand.random_seed_fail_3 (8 ms)
[ RUN      ] StanUiCommand.json_input
[       OK ] StanUiCommand.json_input (8 ms)
[----------] 20 tests from StanUiCommand (170 ms total)

[----------] Global test environment tear-down
[==========] 20 tests from 1 test case ran. (170 ms total)
[  PASSED  ] 17 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] StanUiCommand.random_seed_fail_1
[  FAILED  ] StanUiCommand.random_seed_fail_2
[  FAILED  ] StanUiCommand.random_seed_fail_3
```
Before this commit the random tests pass, there are only these 3 before that PR merge:
```
random_seed_default
random_seed_specified_same
random_seed_specified_different
```
After I apply the next commit ( the model base class PR #713 ) I start getting the same error we are getting now:
```
[ RUN      ] StanUiCommand.random_seed_default
src/test/interface/command_test.cpp:351: Failure
Expected: (random1) != (random2), actual: " [-0.736469,0.505763,-0.170969,2.3785,0.589705,0.924234,1.53572,1.94325,0.879634,1.68832]" vs " [-0.736469,0.505763,-0.170969,2.3785,0.589705,0.924234,1.53572,1.94325,0.879634,1.68832]"
[  FAILED  ] StanUiCommand.random_seed_default (5 ms)
```

None of these commits change any submodule references which should make this easier to track down.

**Comment by rok-cesnovar** [comment]
The issue is this line 

`random_arg->set_value((boost::posix_time::microsec_clock::universal_time() - boost::posix_time::ptime(boost::posix_time::min_date_time)).total_milliseconds());`

The time diff returned by total_milliseconds is an `unsigned int` but its outside the range of `int` (`random_arg->set_value` expects an integer) so it overflows.

I will clean this up and make a PR.

**Comment by betanalpha** [comment]
Good catch — I completely missed that line between
reading the seed in and when it is used later.

**Comment by betanalpha** [comment]
Thanks!

**Comment by seantalts** [comment]
Awesome work, thank you!
