### ISSUE TITLE
Makefile not respecting changes in stan submodule

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstan#727]
#### Summary:

For a model is built in cmdstan, if the algorithms in the stan submodule are changed, on rebuilding make does not detect these changes and says there is nothing to do.

#### Description:

The discussion (and solution from @syclik) is here:

https://discourse.mc-stan.org/t/difficulty-modifying-stan-algorithms-with-cmdstan/10637

#### Current Output:
Make says there's nothing to do

#### Expected Output:
Make recompiles cmdstan main.cpp so that the algorithmic changes go into the model

#### Current Version:
v2.20.0

**Comment by mitzimorris** [comment]
this is a duplicate of

**Comment by bbbales2** [comment]
Fixed by #769
