### ISSUE TITLE
`make stan-revert` shouldn't build dependency files

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstan#745]
#### Summary:
`make stan-revert` shouldn't build dependency files

#### Description:
You can see example output here: https://jenkins.mc-stan.org/blue/organizations/jenkins/CmdStan/detail/PR-737/14/pipeline/12

#### Reproducible Steps:
run `make stan-revert`

#### Current Version:
v2.20.0

**Comment by syclik** [comment]
Yeah... I think to do this, we'll need to exclude the `stan-revert` target from kicking off any of the dependency files. I know that's not enough of a hint to implement, but I think that's what needs to happen.

**Comment by rok-cesnovar** [comment]
This was fixed in one of the makefile refactors. Not an issue on current develop.
