### ISSUE TITLE
Windows tests fail due to failure in copying tbb.dll

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#751]
#### Summary:
This error occurs sometimes on the tests on cmdstan. I havent seen them occur downstream.

Its a result of a workaround we had to resort to due to Windows Jenkins Path configuration issues, which copies the dll if it isnt found in the path. This is not a problem for the users.
```
to avoid copying Intel TBB library files.
to avoid copying Intel TBB library files.
to avoid copying Intel TBB library files.
cp -v stan/lib/stan_math/lib/tbb/tbb.dll src/test/test-models
to avoid copying Intel TBB library files.
to avoid copying Intel TBB library files.
cp -v stan/lib/stan_math/lib/tbb/tbb.dll src/test/test-models
cp -v stan/lib/stan_math/lib/tbb/tbb.dll src/test/test-models
'stan/lib/stan_math/lib/tbb/tbb.dll' -> 'src/test/test-models/tbb.dll'
cp: 'stan/lib/stan_math/lib/tbb/tbb.dll' -> 'src/test/test-models/tbb.dll'
cp -v stan/lib/stan_math/lib/tbb/tbb.dll src/test/test-models
cannot create regular file 'src/test/test-models/tbb.dll': File exists
cp -v stan/lib/stan_math/lib/tbb/tbb.dll src/test/test-models
'stan/lib/stan_math/lib/tbb/tbb.dll' -> 'src/test/test-models/tbb.dll'
make/program:41: recipe for target 'src/test/test-models/proper.exe' failed
mingw32-make: *** [src/test/test-models/proper.exe] Error 1
mingw32-make: *** Waiting for unfinished jobs....
```
I am guessing its due to building with multiple threads and they all start copying but then all except the fastest thread fail. 

The easiest solution is to make the copy command fail silently if that can be done? 

#### Expected Output:
No error on dll copy.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.20.0

**Comment by wds15** [comment]
We should check if the file is already in place before copying. That could solve it...or, even better, is to first build everything only, then copy the dll into all subfolders needed and finally execute the tests.

**Comment by seantalts** [comment]
Can you just make a dependency on the dll in that dir and let make handle
it?

**Comment by wds15** [comment]
That’s what I did...no?

**Comment by seantalts** [comment]
I was suggesting making a target for `%/tbb.dll` with the recipe to print it out and copy it over. I have been having trouble figuring out how to have make add a dependency on an unrelated file in another directory, though.

**Comment by seantalts** [comment]
I can't get it to work! I'm giving up for now, you can kind of see the idea here: https://github.com/stan-dev/cmdstan/compare/bug/issue-751-tbb-dep

**Comment by wds15** [comment]
I will have a look...but it’s difficult. We now have such a target for all of our test directories. For regular Stan files I am working with an if statement. 

Maybe we can tweak makecmdgoals variable to do what we want?

**Comment by seantalts** [comment]
Haha, that might work. Anyway, sorry for butting in here, just thought this seemed like an "obvious" way to do it but then I tried it and it was pretty hairy and I couldn't get it to work. So feel free to ignore me, haha.

**Comment by wds15** [comment]
I will try my advancing make fu knowledge once more (nothing I ever wanted to learn)

**Comment by wds15** [comment]
@seantalts How about this:

https://github.com/stan-dev/cmdstan/compare/bugfix/make-tbb-windows-3

Just click on the changes link from github.

This seems to work at the price of creating a tbb-lib file in addition (to avoid a circular dependency).
