### ISSUE TITLE
targets get rebuild even if unchanged

### ISSUE THREAD

**Issue by wds15** [stan-dev/cmdstan#754]
#### Summary:

Make right now rebuilds stan models even if unchanged. So

```
make examples/bernoulli/bernoulli
make examples/bernoulli/bernoulli
```

Will compile the model 2 times.

#### Description:
clean targets should not be rebuild

#### Reproducible Steps:
see above

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.20.0

**Comment by wds15** [comment]
maybe this report is only valid for the Bernoulli example... which would mean we do not need to investigate further.. pending verification.

**Comment by rok-cesnovar** [comment]
Where did you experience this? Windows? Mac? I am unable to reproduce this on Ubuntu with g++ or clang

**Comment by wds15** [comment]
I saw constant rebuilds under MacOS for the bernoulli example...but for other models everything is just fine. So maybe we can just close this?
