### ISSUE TITLE
Add make/local as a dependency of the pre-compiled header file

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#757]
#### Summary:
If you run `make build` without `CXXFLAGS += -DSTAN_THREADS` and then build your model with `CXXFLAGS += -DSTAN_THREADS` you get the following message

```
/usr/bin/ld: _ZN4stan4math22AutodiffStackSingletonINS0_4variENS0_15chainable_allocEE9instance_E: TLS definition in examples/bernoulli/bernoulli.o section .tbss._ZN4stan4math22AutodiffStackSingletonINS0_4variENS0_15chainable_allocEE9instance_E[_ZN4stan4math22AutodiffStackSingletonINS0_4variENS0_15chainable_allocEE9instance_E] mismatches non-TLS reference in src/cmdstan/main.o
src/cmdstan/main.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make/program:41: recipe for target 'examples/bernoulli/bernoulli' failed
```

A similar issue arises vice-versa, if make build is done with the flag and the model is built without it. I know this issue eill go away once threading is the norm which hopefully comes sooner rather than later.

Can we somehow flag (a stan_threads file in make/ folder idk?) if cmdstan was built with STAN_THREADS and then use that to force a make clean-all and a rebuild if compiling a model with a different setting?

#### Reproducible Steps:
See above.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.20.0

**Comment by wds15** [comment]
Well...if you change the compiler settings then its no surprise that things break due to the pre-compiled stuff which is not any more aligned.

Maybe one can declare the `make/local` file as a dependency of the pre-compiled header file (and all other files which need recompilation) such that changing `make/local` will trigger a rebuild of the pre-compiled header? If that works, then make will automatically rebuild things depending on `make/local` updates... this could be very useful actually.

**Comment by rok-cesnovar** [comment]
> Well...if you change the compiler settings then its no surprise that things break due to the pre-compiled stuff which is not any more aligned.

Completely agree. Not saying this should not happen. Just asking if we can do something about it.

> Maybe one can declare the `make/local` file as a dependency of the pre-compiled header file (and all other files which need recompilation) such that changing `make/local` will trigger a rebuild of the pre-compiled header? If that works, then make will automatically rebuild things depending on `make/local` updates... this could be very useful actually.

That is a great idea. Will try my luck.

**Comment by mitzimorris** [comment]
this assumes that you're using `make/local` to get the compiler options and not passing them in from the command line.  so `make/local` is not a reliable indicator of when you need to recompile `main.o`.

**Comment by mitzimorris** [comment]
@rok-cesnovar - we need to look into GNU Make dependencies - happy to help on this one - http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/

**Comment by bbbales2** [comment]
This is the same bit of memory that we're looking at moving to a new translation unit (https://github.com/stan-dev/cmdstan/issues/834, and https://github.com/stan-dev/math/issues/1750).

If that happens then maybe the solution here is we build the new translation unit in both thread-local and non-thread-local forms and link the right one according to build flags.

But it hasn't been confirmed that the new translation unit thing fixes the bug it was meant to fix and doesn't break something else. And I dunno there's probably other stuff that would need shipped over as well. Maybe it doesn't work.

**Comment by rok-cesnovar** [comment]
No longer required after https://github.com/stan-dev/cmdstan/pull/882
