### ISSUE TITLE
Makefile not respecting changes in model file if .hpp file missing

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstan#763]
#### Summary:

The makefile is not working properly.

#### Description

If I:
1. Build a model (the example bernoulli works here)
2. Change that model and introduce a syntax error
3. Try to rebuild that model (and see the error)
4. Fix the error in the model such that the model is different from how it was in step 1
5. and try to rebuild the model

Then the makefile tells me there's nothing to do and that everything is up to date (and it isn't)

You can also get this error by:
1. Build a model
2. Delete the hpp
3. Change the model in a substantial way
4. and try to rebuild the model

The makefile will also say there's nothing to do.

I'm gonna tag a few people because I think this is important to cmdstan*.

@mitzimorris @syclik @jgabry @rok-cesnovar 

#### Current Version:
v2.21.0

**Comment by bbbales2** [comment]
Also cause it's probably important cause it's a make issue, Ubuntu 18.04, make version 4.1, gcc 7.4.0. I think clang has been a jerk on this computer for me so I haven't used it.

**Comment by seantalts** [comment]
I've seen something like this too on Mac - I think it had do with the new `.o` files introduced with the new way of building models. Possibly some of those intermediate files are marked as expensive or something and not being deleted.

**Comment by rok-cesnovar** [comment]
The model.o should actually be deleted everytime a model is build succesfully. Then everything behaves as normal.

**Comment by rok-cesnovar** [comment]
There is no reason to have it anyway. I think.

**Comment by bbbales2** [comment]
@mitzimorris said she'd have a look at this!

**Comment by mitzimorris** [comment]
the new way of building models introduced in 2.20 messed with the way that make's implicit rules work - the '.d' dependency files are no longer being built.
issue #765 is also a result of that problem.
there is a bugfix branch: 
https://github.com/stan-dev/cmdstan/tree/bugfix/763-765-makefiles

but this version fails to rebuild main.o when changes are made to the sampler.  still investigating, but if @rok-cesnovar has insight, help would be much appreciated!

**Comment by rok-cesnovar** [comment]
Will have a look.
