### ISSUE TITLE
Makefile not rebuilding binary if stuff in stan submodule changes

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstan#765]
#### Summary:

Makefile isn't respecting changes to stan source when rebuilding models

If I:
1. Build examples/bernoulli/bernoulli
2. Change stan/src/stan/mcmc/covar_adaptation.hpp (a file in the Stan submodule)
3. Running make on examples/bernoulli/bernoulli says the binary is up to date (it should rebuild)

Something like this happened before: https://github.com/stan-dev/cmdstan/issues/638, though that issue doesn't seem to have very much useful information in it.

If I manually remove src/cmdstan/main.o then that gets rebuilt and the changes appear. I assume this has something to do with the build speedups.

#### Current Version:
v2.21.0

**Comment by mitzimorris** [comment]
isn't this a duplicate of #727?

**Comment by bbbales2** [comment]
Oh good point it is. Thanks. I'll close this.
