### ISSUE TITLE
add make target `clean-program` to makefiles

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#772]
#### Summary:
when building a stan exe from the stan program file, make creates intermediate files.
add a make command to removes both the exe and all intermediate files.

#### Description:
Example - compile CmdStan's example file `bernoulli.stan` - note resulting intermediate files:

```
~/github/stan-dev/cmdstan (develop)> ls -1F examples/bernoulli
bernoulli.data.R
bernoulli.data.json
bernoulli.stan

~/github/stan-dev/cmdstan (develop)> make examples/bernoulli/bernoulli
...
--- Translating Stan model to C++ code ---
...
--- Compiling, linking C++ code ---
...

~/github/stan-dev/cmdstan (develop)> ls -1F examples/bernoulli
bernoulli*
bernoulli.d
bernoulli.data.R
bernoulli.data.json
bernoulli.hpp
bernoulli.o
bernoulli.stan
~/github/stan-dev/cmdstan (develop)> 
```

command `make clean-program examples/bernoulli/bernoulli`  should remove exe, .d, .hpp, and .o files.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.21.0

**Comment by syclik** [comment]
@mitzimorris, sorry, but that's not going to work with `make`. The space is a delimiter and will result in two targets being passed to `make`: 1) `clean-program` and 2) `examples/bernoulli/bernoulli`. The second target will just try to build it.

One way to deal with something like this is to use a pattern target, so something like `make clean-examples/bernoulli/bernoulli`. That can be matched, the dependencies found, etc.

**Comment by syclik** [comment]
Btw, that's just a technical limitation with `make`. If you find a way to work around it, please let me know! I haven't seen any way to manipulate the targets passed in well enough to handle arguments to make targets.

**Comment by mitzimorris** [comment]
sure, `make clean-<path/to/exe>` would be fine.

the issue is being able to have a simple way to do cleanups after build - `make clean-all` is not fine-grained enough.

**Comment by wesbarnett** [comment]
What if the name/path of the compile binary is passed as an argument?

``` make
clean-program:
	ifndef STANPROG
	$(error STANPROG is not set)
	endif
	rm -v ${STANPROG}{,.o,.hpp}
```

Then you could just run:

```bash
make STANPROG=/path/to/model clean-program
```

**Comment by wesbarnett** [comment]
Here's a way to check if the passed argument is set. Might be safer to pass the name of the stanfile and then pattern match from that. Perhaps there is a better convention though. Here's an example:

```make
.PHONY: clean-program
clean-program:
ifdef STANFILE
	$(RM) $(wildcard $(patsubst %.stan,%.hpp,${STANFILE}))
	$(RM) $(wildcard $(patsubst %.stan,%.o,${STANFILE}))
	$(RM) $(wildcard $(patsubst %.stan,%$(EXE),${STANFILE}))
else
	$(error STANFILE not set)
endif
```
