### ISSUE TITLE
Line ending confusion

### ISSUE THREAD

**Issue by maedoc** [stan-dev/cmdstan#776]
#### Summary:
Stan compiler is confused by line endings.

#### Description:
When compiling a model on Linux with Windows line endings (CRLF) the reported line numbers of errors is wrong. 

#### Reproducible Steps:
Run a Docker image with Stan setup, compile bad Stan file, compare reported line numbers with actual error.  Change line endings to Unix style and recompile for correct error line numbers.

#### Current Output:
for the Stan model
```stan
model {


	real x = sin(0.0));
}
```
with the command
```bash
 make -C $STANDIR $PWD/bad
```
I see
```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
 error in '/work/bad.stan' at line 2, column 21
  -------------------------------------------------
     1: model {
     2:
                            ^
     3:
  -------------------------------------------------

PARSER EXPECTED: ";"
```

#### Expected Output:
Upon changing line endings to LF (from CRLF), I see
```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
 error in '/work/bad.stan' at line 4, column 21
  -------------------------------------------------
     2:
     3:
     4:         real x = sin(0.0));
                            ^
     5: }
  -------------------------------------------------

PARSER EXPECTED: ";"
```

#### Additional Information:
This isn't a big deal but could be a easy/nice fix .

#### Current Version:
v2.20.0

**Comment by maedoc** [comment]
btw, I'm not fuzzing cmdstan or anything, but using it in a Docker container on Windows, which is why I ran into this

**Comment by seantalts** [comment]
Can you try with develop? That should use stanc3, where we may or may not
have the same issue.

**Comment by rok-cesnovar** [comment]
I am going to close this issue as its pretty stale and there was a change to the Stan-to-C++ compiler in between. If the issue persist please open another issue in https://github.com/stan-dev/stanc3
