### ISSUE TITLE
cmdstan cannot run unit tests

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#784]
#### Summary:
the current develop branch of CmdStan fails to run unit tests - compiler error is:

```
~/github/stan-dev/cmdstan (develop)> ./runCmdStanTests.py src/test
------------------------------------------------------------
make build

--- CmdStan v2.21.0 built ---
------------------------------------------------------------
make test-models-exe
cc        -Wl,-L,"/Users/mitzi/github/stan-dev/cmdstan/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/Users/mitzi/github/stan-dev/cmdstan/stan/lib/stan_math/lib/tbb"  src/test/test-models/csv_header_consistency.o stan/src/stan/model/model_header.hpp.gch          -o src/test/test-models/csv_header_consistency
error: invalid value 'precompiled-header' in '-x precompiled-header'
make: *** [src/test/test-models/csv_header_consistency] Error 1
make test-models-exe failed
exit now (12/21/19 19:20:10 EST)
```

#### Description:

CmdStan builds models and they run; however something is screwed up with the unit tests.

#### Reproducible Steps:

commands history:

```
git checkout develop
git pull
make stan-update
make clean-all; make build;
./runCmdStanTests.py src/test
```

#### Current Output:
see above

#### Expected Output:
unit tests should run!

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.21.0

**Comment by mitzimorris** [comment]
@rok-cesnovar  and/or @serban-nicusor-toptal  - how did this pass CI tests?

I have a bugfix branch for issue #775 - would like to get this in because then CmdStanR can use JSON.  bugfix does the right thing on a test model and test data - found this problem when trying to add proper unit test as well.

**Comment by mitzimorris** [comment]
looks like a makefile problem - most likely logic in runCmdStanTests.py - investigating

**Comment by serban-nicusor-toptal** [comment]
Hey, CmdStan is running only interface tests through Jenkins (develop branch) [src/test/interface](https://github.com/stan-dev/cmdstan/blob/develop/Jenkinsfile#L13)
Steps overview [here](https://jenkins.mc-stan.org/blue/organizations/jenkins/CmdStan/detail/develop/497/pipeline/41)
I didn't approve any PR that modified Jenkins so there shouldn't be any change to break this.
Let me know if there is anything I can do to help fix of if I should add a new step in Jenkinsfile to run:  

 ```
make clean-all; make build;  
./runCmdStanTests.py src/test
```

**Comment by mitzimorris** [comment]
thanks @serban-nicusor-toptal - the logs look good.  what's happening locally is that
`runCmdStanTests.py` tries to build the test models via makefile target `make test-models-exe`,  which is defined in `cmdstan/make/tests` - on my machine, this target doesn't do the right thing -

```
~/github/stan-dev/cmdstan (develop)> make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by mitzimorris** [comment]
I think the fix is to rewrite this target - there's a similar rule in `stan/make/tests` - investigating now.

**Comment by mcol** [comment]
I think I saw the same but thought it was something in my setup. Notice how it doesn't seem to pick up `CXX`, but reverts to `cc`, which is just a C compiler.

**Comment by rok-cesnovar** [comment]
The same for me. I dont run Cmdstan src/test usually. When I did the rapidjson PRs I only ran the interface tests and those worked. I can look at this tomorrow to help out if still needed.

**Comment by mitzimorris** [comment]
about to submit a PR for this one - review would be much appreciated.

**Comment by rok-cesnovar** [comment]
Sure, tag me for review.

**Comment by mitzimorris** [comment]
done!  https://github.com/stan-dev/cmdstan/pull/785
