### ISSUE TITLE
Cleanup build warnings on Windows

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#786]
#### Description and reproducible steps:

On `mingw32-make build` on Windows you see the warnings shown below. The build continues as normal but those should be cleaned up. I imagine they are confusing to the users. 

Example:
```
File not found - *cvodes*.hpp
File not found - *idas*.hpp
File not found - *kinsol*.hpp
File not found - *_inst.cpp
File not found - *_def.cpp
INFO: Could not find files for the given pattern(s).
File not found - *.hpp
g++ -std=c++1y -m64 -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs      -I stan/lib/stan_math/lib/tbb_2019_U8/include -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.69.0 -I stan/lib/stan_math/lib/sundials_4.1.0/include  -D_USE_MATH_DEFINES  -DBOOST_DISABLE_ASSERTS      -c -MT src/cmdstan/stanc.o -M -E -MG -MP -MF src/cmdstan/stanc.d src/cmdstan/stanc.cpp
File not found - *cvodes*.hpp
File not found - *idas*.hpp
File not found - *kinsol*.hpp
File not found - *_inst.cpp
File not found - *_def.cpp
INFO: Could not find files for the given pattern(s).
File not found - *.hpp
```

#### Expected Output:

No such warnings

#### Current Version:
v2.21.0

**Comment by rok-cesnovar** [comment]
This is caused by non-compatibility with the windows find command. To avoid this users on windows can add the gnu find that comes with Rtools. 

In order to fix this we need to make a make subroutine for finding files that uses find on unix and `dir /b /a-d /s pattern` on windows. Maybe a recursive $(wildcard) workaround would also work.

**Comment by mitzimorris** [comment]
> To avoid this users on windows can add the gnu find that comes with Rtools.

are you assuming that users on windows have Rtools?

**Comment by rok-cesnovar** [comment]
They probaby either have RTools or use msys2 that also ships with its own gnu find. I would still rather see this fixed without relying on the gnu find. Will hopefuly find some non-hacky solution soon. The recursive call of wildcard that is mostly suggested on stack overfow looks to be rather slow.

**Comment by rok-cesnovar** [comment]
I opened the first PR to address this issue in Stan Math. Once that is merged we can move to Stan and finally Cmdstan.
