### ISSUE TITLE
Revisit printing info on threads and OpenCL devices

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#793]
#### Description:

In #766 I added some output that would print information on threading and OpenCL. 
Example for both:

```
STAN_THREADS is enabled. map_rect will run with at most 2 thread(s).

STAN_OPENCL is enabled. OpenCL supported functions will use:
Platform: AMD Accelerated Parallel Processing
Device: gfx906
```

In https://discourse.mc-stan.org/t/new-message-on-stan-threads/12596 @wds15 raised some fair question on this solution, mainly the following two:

> I actually think that this statement should be part of the stan services which do printout of the chain run parameters. I mean, the exact numerical results will depend on the choice of the number of threads.

> In case the user turns on threading and MPI, then MPI will be used for parallelism (and only a nested map_rect would use threads). Turning on both is not recommended, but it should work.

While the fix for the latter one can be fixed during the feature freeze, which is currently ongoing, I am not sure we can fix the first one before the next release as that does changes some features of the chain run parameters. So we should probably just revert my PR and handle this again after the release?

#### Current Version:
v2.21.0

**Comment by wds15** [comment]
I would be fine with reverting and resorting this for the next release.

Let's hear from @mitzimorris who reviewed the PR letting the first thing in and maybe others have an opinion - @seantalts or @SteveBronder who commented on the earlier PR.

**Comment by SteveBronder** [comment]
> STAN_THREADS is enabled. map_rect will run with at most 2 thread(s). STAN_OPENCL is enabled. OpenCL supported functions will use:
> Platform: AMD Accelerated Parallel Processing 
> Device: gfx906

These all seemed correct and good for the user to know. I'm fine with removing them

**Comment by mitzimorris** [comment]
first off, thanks for alerting me to this and the discussion on the forums.

for the upcoming release, I think that we should leave this as is - this message is informative and the language is appropriate - if it's OK with everyone, I will close this PR - is that OK?

let's discuss changes for 2.22++ on the forums

**Comment by wds15** [comment]
I am only fine with closing the PR (and not reverting) if everyone is fine with changing the CmdStan printouts between releases easily. We are usually super conservative with deprecation/change of existing behavior things. If we are a bit less restrictive in this regard, then I am fine with leaving it in for this release. If not, we should revert the changes and postpone the change.

(Sorry, I have been burned many times by the argument "changes behaviour"; I am not yet good at gauging this)

Also: The message is just wrong whenever you have MPI and threading turned on. Not a very common case, but it's wrong.

**Comment by rok-cesnovar** [comment]
I do not remember any changes to the printouts so I dont have anything to gauge this change with. 

I don't have a sense of how severe a change to the info logger is (hopefully no one is relying on the exact order of output lines), so don't have a strong opinion either way. I do understand your frustration with the "change of existing behavior" things.

> Also: The message is just wrong whenever you have MPI and threading turned on. Not a very common case, but it's wrong.

If the decision will be to keep the current message I will fix this. I agree that for this exact case its wrong. No objection there.

**Comment by rok-cesnovar** [comment]
Based on what @bob-carpenter mentioned on [Discourse](https://discourse.mc-stan.org/t/new-message-on-stan-threads/12596/5) I think we can keep this in for 2.22, but do have to fix the issue whe both MPI and threading are on. After the feature freeze I will move this information to the  chain run parameters as Sebastian suggested.
