### ISSUE TITLE
redo cmdstan arguments; introduce flat arg structure; continue to support current syntax

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#795]
#### Summary:
Change current CmdStan argument parser which imposes idiosyncratic constraints on the ordering of options to a flattened parser which allows arguments to be specified in any order, at the same time, continue to support the current syntax until the next major Stan release.

#### Description:
Knowledgeable Stan users find CmdStan impossible to use because they cannot get the command line syntax right and the error messages that result are often misleading.  cf https://github.com/stan-dev/cmdstan/issues/642, for example.

The code itself is overly complex, difficult to maintain; cf bugfix https://github.com/stan-dev/cmdstan/pull/695 which was a relatively simple code change - < 1 day programmer effort, however the argument test framework was buggy, and demonstrating the correctness of this fix to the satisfaction of the reviewer required an additional 2 weeks of effort.

#### Current Version:
v2.21.0

**Comment by mitzimorris** [comment]
next step is a design spec for flattened argument structure which is will compatible with CmdStanX lightweight wrappers.

**Comment by wds15** [comment]
maybe boost is an option here:

https://www.boost.org/doc/libs/1_72_0/doc/html/program_options.html

**Comment by mitzimorris** [comment]
thanks - that's promising, however, for the time being, in order to accept the current syntax as well as a flat syntax, we'll need a custom parser which processes the command line arguments in order and maintains a notion of "state" as needed for the current system.

**Comment by rok-cesnovar** [comment]
+1 to this. Feel free to tag me for review(s).

This means that there will be duplicate arguments mapping to the same values, which I personally think is fine for this transition period. 

A few questions: 
- what will happen in the unlikely case of someone using both mappings of the same value in the call? For example: `model ... output file=something.csv output_file=something_else.csv`. Do we error in this case or use the first/last provided value with a warning? Silently using either the first or last provided value is probably bad.

- `model help` should probably print the new flattened arguments?

- will we add output stating that the old style of arguments is deprecated?

**Comment by mitzimorris** [comment]
> * what will happen in the unlikely case of someone using both mappings of the same value in the call? For example: `model ... output file=something.csv output_file=something_else.csv`. Do we error in this case or use the first/last provided value with a warning? Silently using either the first or last provided value is probably bad.

everything is more likely than you think - imagine a simple cut and paste error and a long command line - this may well happen.  agreed that we should not do things silently - we should flag things.    the problem with the current argument parser is that when you ignore the implicit nested syntax, you get a very unhelpful error message.


> * `model help` should probably print the new flattened arguments?

yes!


> * will we add output stating that the old style of arguments is deprecated?

we shouldn't do anything that will cause existing production scripts to break - is there any chance that adding an info message would cause problems?

**Comment by rok-cesnovar** [comment]
> we shouldn't do anything that will cause existing production scripts to break - is there any chance that adding an info message would cause problems?

I dont see how it could. I mean, it would only break scripts that rely on some exact order (exact down to spaces and newlines) of info messages... Which seems like a bad idea from the start.

**Comment by mitzimorris** [comment]
closing this issue after discussion with @bob-carpenter who suggested a different command-line interface using a more git-like syntax.

@rok-cesnovar, @bbbales2, @jgabry, @syclik, @wds15, and Bob - feedback and suggestions for draft spec for a new command line interface, tentatively called CmdStan3: https://github.com/stan-dev/design-docs/blob/cmdstan3/designs/0005-cmdstan3.md

**Comment by mitzimorris** [comment]
really closing this issue.
