### ISSUE TITLE
Random seed is not logged/written correctly

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/cmdstan#803]
#### Summary:
cmdstan output records default random seed as `-1` instead of its exact value.

#### Description:
cmdstan output records default random seed as `-1` instead of its exact value.

#### Reproducible Steps:
```bash
make examples/bernoulli/bernoulli; cd examples/bernoulli
./bernoulli sample data file=bernoulli.data.R
grep 'seed' output.csv
```

#### Current Output:
```bash
#   seed = -1 (Default)
```

#### Expected Output:
The value of current seed.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.21.0

**Comment by mitzimorris** [comment]
CmdStan reports the user-specified command-line arguments - in this case, no random seed was specified, so the default argument value `-1` was used; when `-1` is the argument value, then the Stan executable sets the seed based on the timestamp.

What you're asking for, if I understand correctly, is that the csv file contain the random seed value - it that correct?  A reasonable request - we should do something like this in the future - I'd like to replace CmdStan altogether - see https://github.com/stan-dev/design-docs/pull/15

closing this issue for now.

**Comment by yizhang-yiz** [comment]
Yes, I’d like to see cmdstan reports exact value of the seed, just like in 2.19.1  &  earlier.
  
  
  
    
  
  
>

**Comment by mitzimorris** [comment]
> just like in 2.19.1 & earlier.

**Comment by rok-cesnovar** [comment]
See details for reopening https://github.com/stan-dev/cmdstan/pull/831
