### ISSUE TITLE
`make build` fails

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/cmdstan#804]
#### Summary:

When running `make build` with a fresh cmdstan there's no /bin

I'm getting the following errors

#### Current Output:

download of new compiler fails

#### Expected Output:

new compiler downloads

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.22.0

**Comment by bbbales2** [comment]
Same.

I'm getting the error:
```
cp bin/linux-stanc) bin/stanc
/bin/sh: 1: Syntax error: ")" unexpected
make: *** [bin/stanc] Error 2
make: *** Waiting for unfinished jobs...
```

The problem seems to be an extra right parenthesis here: https://github.com/stan-dev/cmdstan/blob/develop/make/stanc#L46

**Comment by rok-cesnovar** [comment]
What to do here? Do we re-do the release for cmdstan or a hotfix? We could fix just the tarball.

**Comment by SteveBronder** [comment]
I'm not sure on what's kosher here but I'm fine with a re-release as 2.22.1

**Comment by mitzimorris** [comment]
please let's do a hotfix and fix the tarball.

**Comment by mitzimorris** [comment]
I can fix the makefile tomorrow - if someone can do it before then, that would be awesome.

**Comment by SteveBronder** [comment]
Got a fix in #805. We were just missing a one liner to make the bin directory.

We only released like two days ago so I don't see this as a big sweat as long as we get it in soon

**Comment by rok-cesnovar** [comment]
The tarball bug which @bbales notes (the parenthesis) is my fault, I didn't do a thorough enough review of everything introduced in https://github.com/stan-dev/cmdstan/pull/799

To make sure this one doesn't happen again, we should add a test that tries to () build with windows-stanc, linux-stanc and mac-stanc. I can take care of that. I apologize to anyone affected. 

I am not sure about this bug Steve is seeing. I re-ran develop manually on Jenkins (see https://jenkins.mc-stan.org/blue/organizations/jenkins/CmdStan/detail/develop/550/pipeline)and everything is green. And Jenkins tests download the stanc3 binary same as Steve.

The way stanc is download has stayed the same for 3 months now (there is no /bin on fresh clone and develop always used curl to download). #799 only added behavior when bin/windows-stanc, linux-stanc or mac-stanc are present. So it might be that only the tarball is broken and this is something else.

**Comment by rok-cesnovar** [comment]
Ok, got to the bottom of how this happened. I reviewed #799 while on Windows and on Windows mkdir is used https://github.com/stan-dev/cmdstan/blob/develop/make/stanc#L51

Before #799, mkdir was used in both Windows and non-windows, so what I said before "The way stanc is download has stayed the same for 3 months now" doesnt hold. Sorry.

As to why Jenkins passes: because of parallel builds. bin/cmdstan/diagnose or something else is built before the binary is downloaded. Argh. We should maybe add something like this to one of the interface tests: 
```
make -j1 build
make clean-all
//proceed as beforel
```

**Comment by mitzimorris** [comment]
Steve's fix is in - https://github.com/stan-dev/cmdstan/pull/805  - many thanks!!

can we do a hotfix for CmdStan relrease and create a new tarball?  this will bump the version to 2.22.1,  correct?

**Comment by rok-cesnovar** [comment]
So https://github.com/stan-dev/cmdstan/commit/e9075d0b750205cfe23f4f86cef59446b27db8d5 should be merged to the current master and released with a new tarball that also contains the bin/windows-stanc, bin/linux-stanc, bin/mac-stanc.

cc @serban-nicusor-toptal

**Comment by rok-cesnovar** [comment]
We will also have to do a Math 3.1.1, as @avehtari has uncovered a separate issue.

**Comment by wds15** [comment]
How about a 2.23.0 ?

**Comment by rok-cesnovar** [comment]
I think 2.22.1 would be better, as this would a huge release and I am almost sure other issue will come up that will require additional patches. Not going to oppose though.

**Comment by wds15** [comment]
Sure. I just recall that these hot fixes were difficult to manage release wise... but nothing I am affected.

(moreover, in case we were to go with 2.23.0, then we should have another week of a feature freeze)

**Comment by mitzimorris** [comment]
closing this issue - fixed and released
