### ISSUE TITLE
add stanc version to output of bin/stanc --version

### ISSUE THREAD

**Issue by avehtari** [stan-dev/cmdstan#807]
#### Summary:
```
bin/stanc --version
```
 prints
```
stanc version 2.22.0
```
It would be useful to show also whether stanc2 or stanc3 is used

#### Current Version:
v2.22.0

**Comment by wds15** [comment]
I am not sure this is useful. The plan is definitely to drop stanc2 entirely. There will only be a single stanc for a given cmdstan version. @mitzimorris should weigh in here, but I would not think that we need this.

**Comment by avehtari** [comment]
As long as there are two options, there should be a way to see which is actually used. It seems this will be fixed in stanc3 stan-dev/stanc3#443, see also stan-dev/cmdstanr#115

**Comment by rok-cesnovar** [comment]
In order to distinguish until we have both, stanc3 will output stanc3 on 2.22.1+. The fix was already merged so I am going to close this.

After the old compiler is phased out we can come back to this.
