### ISSUE TITLE
Release of Cmdstan 2.22.1

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#808]
#### Summary:

So as we know, we will have to do a hotfix release for Cmdstan. Compared to the current master that will update the Stan submodule to 2.22.1 (see https://github.com/stan-dev/stan/issues/2883) and cherry pick the merge commit https://github.com/stan-dev/cmdstan/commit/e9075d0b750205cfe23f4f86cef59446b27db8d5 of https://github.com/stan-dev/cmdstan/pull/805 to master.

This will probably go down tomorrow sometime after the Stan Math 3.1.1 and Stan 2.22.1 tests pass.

If anyone has any comments please let me know.

#### Current Version:
v2.22.0

**Comment by serban-nicusor-toptal** [comment]
CmdStan was releases [v2.22.1](https://github.com/stan-dev/cmdstan/releases/tag/v2.22.1), tests passed.
Will add manual and tar.gz soon.

**Comment by rok-cesnovar** [comment]
Everything released, tarball ready. Thanks @serban-nicusor-toptal

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal Argh, the windows tarball has a new bug if bin/windows-stanc is present. Lets fix this temporarily by removing the bin/windows-stanc from the tarball in which case everything is fine. I dont think this needs another release now. We can release this when we fix any other new found stanc3 issues.
