### ISSUE TITLE
generate_quantities fails with non-scalar parameters

### ISSUE THREAD

**Issue by teddygroves** [stan-dev/cmdstan#841]
#### Summary:
I get the following type of error when running the cmdstanpy `generate_quantities` method with a model that has vector parameters:

```
Mismatch between model and fitted_parameters csv file "./samples/2019/model-202003110919-2.csv"
```

#### Description:

To narrow down what is happening I tried changing [this line](https://github.com/stan-dev/cmdstan/blob/f348bc1dbe8b85f6b94e01a38030ccaa0acb83ed/src/cmdstan/command.hpp#L223) in cmdstan as follows:

```
          msg << "Mismatch between model and fitted_parameters csv file \"" << param_names[i] << "\"" << fitted_params.header[i + hmc_fixed_cols] << "\"" << std::endl;

```

The error message then changed to:

```
Mismatch between model and fitted_parameters csv file "theta.1"theta[1]"
```

I think this might mean that the problem is something to do with the `param_names` or `fitted_params.header` objects in that cmdstan file.

#### Reproducible Steps:

First create these two .stan files in the cmdstan root directory: 
`bern_model.stan`:

```
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta[1];
} 
model {
  theta ~ beta(1,1);
  y ~ bernoulli(theta[1]);
}
```
`bern_model_gq.stan`:
```
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta[1];
} 
model {
  theta ~ beta(1,1);
  y ~ bernoulli(theta[1]);
}
generated quantities {
  int y_sim[N];
  real<lower=0,upper=1> theta_rep;
  for (n in 1:N)
    y_sim[n] = bernoulli_rng(theta[1]);
  theta_rep = sum(y) / N;
}
```
Next run the following shell commands:
```
make bern_model
make bern_model_gq
./bern_model sample data file=examples/bernoulli/bernoulli.data.json
./bern_model_gq generate_quantities fitted_params=output.csv data file=examples/bernoulli/bernoulli.data.json
```

#### Current Output:
```
method = generate_quantities
  generate_quantities
    fitted_params = output.csv
id = 0 (Default)
data
  file = examples/bernoulli/bernoulli.data.json
init = 2 (Default)
random
  seed = -1 (Default)
output
  file = output.csv (Default)
  diagnostic_file =  (Default)
  refresh = 100 (Default)

Error reading fitted param names from sample csv file "output.csv"
```

#### Expected Output:
Normal `generate_quantities` output

#### Additional information
I originally posted this bug [here](https://github.com/stan-dev/cmdstanpy/issues/226) but closed when I found I could reproduce it with pure cmdstan.

#### Current Version:
v2.22

**Comment by mitzimorris** [comment]
thanks for the thorough report - will investigate

**Comment by rok-cesnovar** [comment]
This was fixed by https://github.com/stan-dev/stan/pull/2931

**Comment by rok-cesnovar** [comment]
Apologies, this is still very much an open issue.
