### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [stan-dev/cmdstan#851]
Hey, thanks for this great library! I wanted to let you know there's now a [Ruby library](https://github.com/ankane/cmdstan) for it. It's modeled after the CmdStanPy API and works on Linux, Mac, and Windows. I started with the methods/options needed to port [Prophet](https://github.com/facebook/prophet).

If you have any feedback, let me know or feel free to open an issue on the project. Thanks!

**Comment by rok-cesnovar** [comment]
That looks great! Would you mind posting that on our Discourse: https://discourse.mc-stan.org/
It will definitely get more exposure there. And thanks for notifying us. 

As technically this isnt an "issue" we will close this after a week or so. We can leave it open for some time.

**Comment by ankane** [comment]
Will do, thanks @rok-cesnovar!
