### ISSUE TITLE
docs cleanup for rel 2.23

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#854]
#### Summary:
Pre-release check that information in CmdStan guide is appropriate for the 2.23 release.

#### Description:
CmdStan features are unchanged by this release, but there were some makefile changes to allow for both stanc2 and stanc3 - make sure that documentation is correct w/r/t makefile and build.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.22

**Comment by wds15** [comment]
There is now reduce sum which is a stanc3 only feature...do we document this somewhere?

**Comment by mitzimorris** [comment]
reduce_sum is documented in the online Stan documentation - we'll build 2.23 versions of all three manuals - I think @serban-nicusor-toptal now has scripts that automate this.

the CmdStan guide is still in latex and therefore pdf-only.

**Comment by wds15** [comment]
Sorry if what I said was confusing... in case users use the stanc2 flavor, then they will not be able to use reduce sum as this is only implemented in stanc3. I think this is the first stanc3 only feature we have.

**Comment by rok-cesnovar** [comment]
stanc2 is only meant for debugging purposes. Not really as a second type of use of cmdstan. Well, except as a backup if something doesnt work in stanc3 as it should. There are quite a number of functions that are already only implemented in stanc3 (gp_* functions for example).

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstan/pull/855
