### ISSUE TITLE
Optimize compile time

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#863]
#### Description:
We have regressed substantially in terms of compile time since the CRTP change in 2.20.

Bernoulli example compile time in 2.20: ~11.5 seconds
Bernoulli example compile time in 2.23: ~14.5 seconds

I also tried we a few other models: 
![430d0c0c294600700e09e1d6640fe705a945a2df](https://user-images.githubusercontent.com/28476796/80379627-a30d7580-889e-11ea-9746-a734c2fbe815.png)

All with g++ on Ubuntu.

Some of this is due to added complexity/number of files/templating and so on. Some of it however can be improved. I identified a few potential spots that could be improved.

#### Reproducible Steps:
Repeat the below a few times:

```
touch examples/bernoulli/bernoulli.stan
time make examples/bernoulli/bernoulli
```

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.23.0

**Comment by rok-cesnovar** [comment]
Its similar for clang++ on Ubuntu:

2.20: ~5.8s
2.23: ~8s

**Comment by mitzimorris** [comment]
looks great!  please elaborate on potential spots and let me know if I can be of help.

**Comment by bob-carpenter** [comment]
Thanks for the nice analysis, @rok-cesnovar.  

Would it be possible to add compile-time tests to the test framework?  I'm pinging @serban-nicusor-toptal in case he has any thoughts.

With these tests instrumented, we can evaluate the tradeoffs of complicating our template patterns or other new features, as that's presumably where the time's going.

**Comment by rok-cesnovar** [comment]
> please elaborate on potential spots

Sure, here is a chart of a "git bisection" I ran with a script. I started at 2.20 and evaluated at every 20th commit to cmdstan develop to 2.23.

![Rplot](https://user-images.githubusercontent.com/28476796/80397096-efb07b00-88b5-11ea-9b75-f6bebdc9e95d.png)

As you can see there is some gradual increase all the time (I think its due to increased complexity), but also 2 significant jumps. The second jump is due to some small details in https://github.com/stan-dev/cmdstan/pull/769 
I figured out another way which reduces compilation for ~1.5 (14.5 to 13 for g++, 7.5 to 6s with clang++). WIll open a PR.

The second one is between git commits 7a884896ca82ca3dc0c3d017c168a8477f2b4558 and 920d31bc0ecda5e54d626ae44297c1bb58a4442a
I have one candidate, will elaborate once I know more.

**Comment by rok-cesnovar** [comment]
> Would it be possible to add compile-time tests to the test framework?

We have those in some form (see performance.compilation in https://github.com/stan-dev/cmdstan/pull/862#issuecomment-617605734) but they are unreliable. One would have to run the (touch + make) thing in a loop to get more of a sense.

**Comment by rok-cesnovar** [comment]
Another part is including boost headers we either dont need or use or can replace with std::. This is mostly in stan (outside of stan compiler code) and cmdstan.

**Comment by rok-cesnovar** [comment]
Ran a custom performance run with all three boost cleanup branches https://jenkins.mc-stan.org/job/CmdStan%20Performance%20Tests/job/Custom/155/
Linux: 
| Name | Old Result | New Result | Ratio | Performance change( 1 - new / old ) | 
| ------------- |------------- | ------------- | ------------- | ------------- | 
| compilation | 56.89 | 51.63 | 1.1 | 9.24% faster | 

Mac: 
| Name | Old Result | New Result | Ratio | Performance change( 1 - new / old ) | 
| ------------- |------------- | ------------- | ------------- | ------------- | 
| compilation | 91.24 | 89.63 | 1.02 | 1.76% faster |

**Comment by rok-cesnovar** [comment]
Did some more digging with clang

Compile times of arK model over time with clang6 on Ubuntu:

![clangMarked](https://user-images.githubusercontent.com/28476796/80501342-9dcc2b80-896f-11ea-9f68-0fc5c72f96de.png)

Seeing as I fell in this rabbit already, I decided to dive in further. Here is a bit more details.

A - https://github.com/stan-dev/math/pull/1262 (this one is weird to me, but it seems to be the added use of boost_policy_t() in gamma_p) - but not much can be done here (except if maybe the default policy becomes the one we use)
B - the drop in B is due to switch to stanc3, the rise is due to https://github.com/stan-dev/math/pull/1334 (nothing special but 2 functions added) - not much can be done here
C - the first peek (between 7 and 7.5) is due to the switch back to stanc2, and that goes away when we again went to stanc3. The peek in C at ~8 is due to https://github.com/stan-dev/cmdstan/pull/769 that is fixable - a PR is open
D - https://github.com/stan-dev/math/pull/1747 (One would expect generalization to have the opposite effect but yay!)

With the cleanup of unused and unnecessary boost:: stuff and the open makefile PR we get back to ~6.0s for this same model and ~12.5-13 on g++ so going to close this issue once that is merged.

**Comment by rok-cesnovar** [comment]
At least on my system with clang++ we are mostly where we were when CRTP was added.

![clang](https://user-images.githubusercontent.com/28476796/80809131-54731a80-8bc1-11ea-8cad-582178dfb97c.png)

g++ was hit more by the added complexity, but also looks better

![gplusplus](https://user-images.githubusercontent.com/28476796/80809192-710f5280-8bc1-11ea-9ad7-7dc996169763.png)

Closing. Thanks @mitzimorris for testing and debugging.
