### ISSUE TITLE
boost exception in MPI job: Exception: unregistered class - derived class not registered or exported

### ISSUE THREAD

**Issue by wresch** [stan-dev/cmdstan#867]
#### Summary:
A model that worked in 2.21.0 fails in 2.22.1 and 2.23.0 with an exception that appears to be coming from the boost serialization library. Error message:

```
Exception: unregistered class - derived class not registered or exported (in 'linreg/linreg_par.stan', line 44, column 3 to line 45, column 43) [origin: unknown original type]
Exception: unregistered class - derived class not registered or exported (in 'linreg/linreg_par.stan', line 44, column 3 to line 45, column 43) [origin: unknown original type]
```

#### Description and reproduction

Building cmdstan with gcc 9.2.0 and OpenMPI 3.1.4
```console
$ wget https://github.com/stan-dev/cmdstan/releases/download/v2.23.0/cmdstan-2.23.0.tar.gz
$ tar -xzf cmdstan-2.23.0.tar.gz
$ cd cmdstan-2.23.0
$  mpicc --version
gcc (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ cat <<EOF > make/local
STAN_MPI=true
CXX=mpicxx
TBB_CXX_TYPE=gcc
EOF
$ make -j8 build
```

Other things i've tried:
 - gcc 5.5.0 with mpich2 3.2.1
 - openmpi 3.1.4 with intel compiler
 - openmpi 3.1.4 with gcc 7.4.0
 - openmpi 3.1.4 with gcc 9.2.0 and `-O2` instead of `-O3`

Then build the following model in the source tree with make:

```
functions {
  vector bl_glm(vector sigma_beta, vector theta,
                real[] xs, int[] xi) {
        int J = xi[1];
        int K = xi[2];
        real lp;
    real sigma = sigma_beta[1];
        vector[K] beta= sigma_beta[2:(K+1)];
    lp=normal_lpdf(xs[1:J] | to_matrix(xs[(J+1):(J*(K+1))],J,K) * beta, sigma);
    return [lp]';
  }
}
data {
  int<lower = 0> K;
  int<lower = 0> shards;
  int<lower = 0> N;
  matrix[N,K] X;
  vector[N] Y;
}

transformed data {
vector[0] theta[shards];
  int<lower = 0> J = N / shards;
  real x_r[shards, J * (K+1)];
  int x_i[shards, 2];
  {
    int pos = 1;
    for (k in 1:shards) {
      int end = pos + J - 1;
      x_r[k] = to_array_1d(append_col(Y[pos:end],X[pos:end,]));
      x_i[k,1] = J;
      x_i[k,2] = K;
      pos += J;
    }
  }
}
parameters {
  vector[K] beta;
  real<lower=0> sigma;
}
model {
  beta ~ normal(0, 2);
  sigma ~ normal(0, 2);
   target += sum(map_rect(bl_glm, append_row(sigma, beta),
                         theta, x_r, x_i));
}
```

Ran with 28 MPI tasks on a single node. Always fails with

```
Exception: unregistered class - derived class not registered or exported (in 'linreg/linreg_par.stan', line 44, column 3 to line 45, column 43) [origin: unknown original type]
Exception: unregistered class - derived class not registered or exported (in 'linreg/linreg_par.stan', line 44, column 3 to line 45, column 43) [origin: unknown original type]
```

Ran to completion with 2.21.0. I use a rather large input file (around 1GB), so that's not included here. But i used the following R script to generate data and used order 4 input for this test:

```r
library(rstan)
set.seed(123)
# - very slow at order 4
# - output files for different numbers of shards
#   are identical except for the shards variable
for (order in c(2,3,4)){
  print(order)
  K <- (10^order)/2
  N <- 10^order
  X <- matrix(rnorm(N*K), ncol=K)
  b <- rnorm(K)
  Y <- as.vector(X %*% b + rnorm(N))
  for (shard in c(1,2,4,5,10)){
    shards <- shard
    stan_rdump(c('K','N','X','Y','shards'),
               file=paste0("dat_order_", order, "_shards_", shard, ".Rdump"))
  }
}
```

I'm a cluster admin trying to help our users run cmdstan but I myself don't know stan well so this may just be operator error...

#### Current Version:
v2.23.0

**Comment by wds15** [comment]
Nope, I think this is stanc3 bug.

Can you put STANC2=true into make/local, then clean everything and try again?

**Comment by rok-cesnovar** [comment]
Hi, this is the same issue as reported in https://github.com/stan-dev/stanc3/issues/527 and https://github.com/stan-dev/stanc3/issues/516

It will be fixed in https://github.com/stan-dev/stanc3/pull/517 we just need to get the PR reviewed.
Until then, use STANC2=true to get this model working.

**Comment by wresch** [comment]
Ah - I should have checked over there. Thanks for the super fast and helpful feedback - testing now

**Comment by wresch** [comment]
yes - that works! Thank you.

**Comment by rok-cesnovar** [comment]
I didnt mean that in the sense that you should checked there - you are not expected to know all the details of the various repositories. So no worries there. 

I posted so that other devs dont waste their time looking for bugs that are already known.

Thanks for reporting back and happy sampling.
