### ISSUE TITLE
When rebuilding stanc3 from source, main.o is rebuilt unnecessarily

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#885]
#### Description:

When using stanc3 built from source with cmdstan (`STANC3=path/to/stanc3` in `make/local`), every time there is a change in the stanc3 compiler, main.o is recompiled. 

This only affects developers not the users but it is unnecessary. 

#### Current Version:
v2.23.0

**Comment by mitzimorris** [comment]
good catch!

**Comment by rok-cesnovar** [comment]
Cant replicate anymore. Closing.
