### ISSUE TITLE
Performance tests should fail on compile error

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#886]
#### Description:

A model in the performance tests failed to compile:
https://jenkins.mc-stan.org/blue/organizations/jenkins/CmdStan/detail/downstream_tests/1715/pipeline/83

but the test went green. It should fail.

#### Current Version:
v2.23.0

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal would you know a simple fix for this?

**Comment by serban-nicusor-toptal** [comment]
Hey, took a look last night and couldn't find a reason for it. Will keep debugging
