### ISSUE TITLE
Add ./model compile_info 

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#887]
#### Description:

We should add a  "compile_info" argument to the model executable that would output information on how to executable was compiled:

Example:

`./examples/bernoulli/bernoulli compile-info`

outputs:

```
MODEL_NAME = bernoulli_model
STAN_VERSION = 2.23.0
STANCFLAGS = --allow_undefined
STANC_VERSION = stanc3 124f5639
STAN_THREADS = true
```
For now, I envisioned adding the stan version, stanc flags, stanc version, and whether the THREADS/MPI/OPENCL flags were used.

Other options I am not sure we want to use but could if there is interest:
- c++ compiler and version
- the time of compilation
- hash of the model code
- model code (but that is probably overkill)

#### Current Version:
v2.23.0

**Comment by rok-cesnovar** [comment]
I have this implemented in stan/cmdstanstanc3 but will wait for feedback before proceeding.

The model would get a constructor with no arguments and a compile info function.

```cpp
  bernoulli_model() : model_base_crtp(0)  {}  

  std::vector<std::string> model_compile_info() const {
    std::vector<std::string> info;
    info.push_back("MODEL_NAME=bernoulli_model");
    info.push_back("STANCFLAGS=--allow_undefined");
    info.push_back("STANC_VERSION=%%NAME%%3 %%VERSION%%");
#ifdef STAN_THREADS
    info.push_back("STAN_THREADS=true");
#endif
#ifdef STAN_MPI
    info.push_back("STAN_MPI=true");
#endif
#ifdef STAN_OPENCL
    info.push_back("STAN_OPENCL=true");
    std::stringstream msg;
    msg << "OPENCL_PLATFORM_ID=" << OPENCL_PLATFORM_ID << "\n"
        << "OPENCL_DEVICE_ID=" << OPENCL_DEVICE_ID;
    info.push_back(msg.str());
#endif
    return info;
  } 
```
and

```cpp
stan::model::model_base& new_model() {
  stan_model* m = new stan_model();
  return *m;
}
```

**Comment by rok-cesnovar** [comment]
Primary use case is cmdstanX wrappers but this is useful for cmdstan also. I found myself not knowing if I compiled a model with STAN_THREADS/STAN_OPENCL a lot :) .

**Comment by wds15** [comment]
I would find it better to have a config.hpp or the like in stan-math. This file would be like our make/local, but more standard like as other packages are doing it.

What is the use case for exposing this via cmdstan?

The name compile_info is possibly misleading as this would include -OX things as well. It should be better to call it something which says „enabled features“ or the like.

**Comment by rok-cesnovar** [comment]
> I would find it better to have a config.hpp or the like in stan-math. This file would be like our make/local, but more standard like as other packages are doing it.

That would work for THREADS/MPI/OPENCL but that does not give you version numbers/stanc3 version. Maybe there is a misunderstanding here. This is meant for printing information on how the model was compiled. Not compiling or setting compile flags.

> What is the use case for exposing this via cmdstan?

Not sure I understand. This is a cmdstan(X) feature, so it should be exposed in cmdstan. It makes on sense in math as we have no concept of a model there.

> The name compile_info is possibly misleading as this would include -OX things as well. It should be better to call it something which says „enabled features“ or the like.

The name is a placeholder for now. There are better names for sure.

**Comment by betanalpha** [comment]
While we still have the monolithic CSV output it would be great to add this
info there as well to make everything as reproducible as possible.

**Comment by rok-cesnovar** [comment]
That is a good call. The threads/mpi/opencl are represented in a way in the CSV, though that could be made more explicit. For example, num threads is listed but we should also state that threads_enabled = 1. 

The version of the compiler and the flags used to compile is however not there. And given that compile-time optimizations in stanc will be available in the next release we really must add this to the CSV to make this more reproducible.

**Comment by rok-cesnovar** [comment]
One other potentially nice thing would be to also output the input data names and their types in a machine friendly way.
```
DATA
int N
int[] y
vector z
ENDDATA
```
The use case is nicer messages on what data is missing in both cmdstan and cmdstanX.

**Comment by mitzimorris** [comment]
> While we still have the monolithic CSV output it would be great to add this info there as well to make everything as reproducible as possible.

putting this into the monolithic CSV output header makes sense - we need to document the exact format or order of this info w/r/t the command line config info.
