### ISSUE TITLE
make doesn't detect Windows OS

### ISSUE THREAD

**Issue by PhilClemson** [stan-dev/cmdstan#906]
#### Summary:
I tried to install CmdStan 2.23.0 on a Windows 10 laptop this week and ran into errors upon running make.

#### Description:
I followed the step-by-step installation provided by the CmdStan user's guide. I already had RTOOLS installed on the laptop so skipped those steps. However, I ran the `g++ -v` and `mingw32-make -v` as a check and got:

>Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=C:/Rtools/mingw_64/bin/../libexec/gcc/x86_64-w64-mingw32/4.9.3/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-4.9.3/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/home/Jeroen/mingw-gcc-4.9.3/x86_64-493-posix-seh-rt_v3-s/mingw64 --with-gxx-include-dir=/mingw64/x86_64-w64-mingw32/include/c++ --enable-static --disable-shared --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-isl-version-check --disable-cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static --with-mpc=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static --with-isl=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static --with-cloog=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='x86_64-posix-seh, Built by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/home/Jeroen/mingw-gcc-4.9.3/x86_64-493-posix-seh-rt_v3-s/mingw64/opt/include -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-zlib-static/include -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/home/Jeroen/mingw-gcc-4.9.3/x86_64-493-posix-seh-rt_v3-s/mingw64/opt/include -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-zlib-static/include -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/home/Jeroen/mingw-gcc-4.9.3/x86_64-493-posix-seh-rt_v3-s/mingw64/opt/lib -L/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-zlib-static/lib -L/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 4.9.3 (x86_64-posix-seh, Built by MinGW-W64 project)

>GNU Make 4.1
Built for x86_64-w64-mingw32
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

After extracting the .tar file and running `make build` from the CmdStan folder I get the error [output1.txt](https://github.com/stan-dev/cmdstan/files/4904215/output1.txt).

The problem is fixed by creating a `make/local` file which includes `OS=Windows_NT`. I also just discovered that running `make build` a second time also solves the issue.

It's also worth noting that in the documentation it says that the `make` command installs the Intel TBB library, but this must in fact be installed using `mingw32-make install-tbb` _before_ running the `make` command. Not installing the TBB library results in the error shown in [output2.txt](https://github.com/stan-dev/cmdstan/files/4904216/output2.txt) during installation.

#### Reproducible Steps:
See description.

#### Current Output:
See description.

#### Expected Output:
"`--- CmdStan v.2.23.0 built ---`" on first `make build` command.

#### Additional Information:
Here's the specs of the laptop I'm working with:
OS - Microsoft Windows 10 Pro
Version - 10.0.18362 Build 18362
Processor - Intel i7-4790K
Physical Memory - 16.0 GB

#### Current Version:
v2.23.0

**Comment by mitzimorris** [comment]
thanks for the careful report.
were you using the pdf version of the User's Guide distributed with the release?
or the new online version?

**Comment by PhilClemson** [comment]
> 
> 
> thanks for the careful report.
> were you using the pdf version of the User's Guide distributed with the release?
> or the new online version?

I was using the User's Guide pdf that was distributed with the release

**Comment by rok-cesnovar** [comment]
You should run `mingw32-make build`, not `make build`. I believe that is the main issue here.

Going to close this, not sure there is any further action required here. But do reopen/comment if you feel we can do something.
