### ISSUE TITLE
mingw32-make is not included in RTools 4.0 for Windows

### ISSUE THREAD

**Issue by conchra** [stan-dev/cmdstan#909]
#### Summary:
Can not build CmdStan 2.23.0 on Windows 10 (18363) with RTools version 4.0.

#### Description:
I used the setup instructions in the documentation CmdStan Interface User’s Guide Version 2.23.0 (22 April 2020) with RTools 4.0 installed. Checking `mingw32-make -v'` results in the error "'mingw32-make' is not recognized as an internal or external command...".

#### Reproducible Steps:
See Description. Some checking shows that RTools 4.0 is quite different to RTools 3.5. 

#### Current Output:
"'mingw32-make' is not recognized as an internal or external command, operable program or batch file.".

#### Expected Output:
`--- CmdStan v.2.23.0 built ---`

#### Additional Information:
I tried just using `make build`. This works up to the point that TBB is being built and then fails with 
```
ERROR: Please use mingw32-make on Windows to build the Intel TBB library.
This is packaged with RTools, for example.
make: *** [stan/lib/stan_math/make/libraries:132: stan/lib/stan_math/lib/tbb/tbb-make-check] Error 1
```

#### Current Version:
v2.23.0

**Comment by rok-cesnovar** [comment]
Hi, 

you need to install mingw32-make manually via RTools Bash. 

To open RTools Bash, which comes with RTools 4.0, just hit Windows Key, type rtools bash and hit Enter. A new console window will pop up. Now, just type

`pacman -Sy mingw-w64-x86_64-make`

Then try again.

**Comment by conchra** [comment]
Installing mingw32-make with the command provided works.
