### ISSUE TITLE
makefile is recompiling `main.o` and tbb libs when it shouldn't

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#910]
#### Summary:

In running both CmdStan and CmdStanR, successive calls to compile
different stan programs, using all default compiler options,
appear to sometimes trigger a rebuild when they shouldn't.

#### Description:
Still investigating.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.23.0

**Comment by bbbales2** [comment]
I tried a couple models (one in cmdstan and one in cmdstanr) and didn't get this.

Can you try to get this to happen again with your stansummary branch? I was getting some unnecessary compiling in the ODE development, but the cmdstan I was using there was quite out of date so I'd rather reproduce a problem with something new.

**Comment by mitzimorris** [comment]
just realized that cmdstanr was also using out-of-date CmdStan - path was set to 2.23.0 release.
will try on 2.24.0-rc

**Comment by mcol** [comment]
Isn't this the same as #885?

**Comment by mitzimorris** [comment]
closing this as I haven't been able to reproduce this problem via successive recompiles of Stan programs.
