### ISSUE TITLE
Release of CmdStan 2.24.0

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#911]
#### Summary:
2.24 Release Notes

**Comment by wds15** [comment]
@serban-nicusor-toptal the just tagged cmdstan 2.24-rc1 does not include the dependencies like stan, Stan-math, etc....

**Comment by serban-nicusor-toptal** [comment]
I'm uploading the archive now, takes a bit sorry ... slow internet

**Comment by wds15** [comment]
I just downloaded the archive and now it's 33MB... that's good, but the extracted files land in a directory "cmdstan-"... can that be renamed to "cmdstan-2.24.0rc1" please?

Thanks.

**Comment by serban-nicusor-toptal** [comment]
Sure, one moment. Must have been a typo.

**Comment by serban-nicusor-toptal** [comment]
@wds15 Should be all fine now.

**Comment by wds15** [comment]
Now it is "cmdstan-**v**2.24.0-rc1" while it should be "cmdstan-2.24.0-rc1" as it is usually, but maybe just leave it as is for now. Next time.

**Comment by serban-nicusor-toptal** [comment]
No worries, my bad forgot to remove the `v` as a prefix. Will re-upload in a moment

**Comment by mitzimorris** [comment]
CmdStan 2.24.0

Features:

- CmdStan User's Guide now online - updated and revised

- Utility command `stansummary` allows user-specified quantile reporting,
  improved output format, better command-line options handling

- Many makefile improvements:
  + precompiled headers
  + detect compiler option dependencies
  + improved messaging

Bugfixes

- Generated quantities for models with non-scalar parameters
