### ISSUE TITLE
Release 2.24.1 is still numbered 2.24.0

### ISSUE THREAD

**Issue by karldw** [stan-dev/cmdstan#919]
#### Summary:
The just-released v2.24.1 still has 2.24.0 version numbers.

#### Description:

The version number here is still 2.24.0 in the 2.24.1 release: https://github.com/stan-dev/cmdstan/blob/fa449c544e93fd215a5314c5701c5309fcbc8489/makefile#L63

This means cmdstanr's `cmdstan_version()` returns `2.24.0` for release `2.24.1`.

(Definitely not a big deal, it just makes version pinning harder.)

#### Current Output:

2.24.0 whenever a version number is asked for.

#### Expected Output:

2.24.1 whenever a version number is asked for.

#### Current Version:
v2.24.1

**Comment by rok-cesnovar** [comment]
Thans!

@serban-nicusor-toptal can we fix that just on master and tarballs?

**Comment by serban-nicusor-toptal** [comment]
Ouch, my bad. On it.

**Comment by karldw** [comment]
Thanks!

**Comment by serban-nicusor-toptal** [comment]
Everything should be fine now @karldw 
Thanks a lot for the quick notice!
