### ISSUE TITLE
improve installation instructions

### ISSUE THREAD

**Issue by avehtari** [stan-dev/cmdstan#92]
README.md says
1. Download the latest release tarball (use the "green" link) from: CmdStan releases
2. Unpack the tarball.
3. From the folder, type make for a quick tutorial on how to build models.
This works, but if I instead use 'git clone' to get CmdStan, make stanc gives an error
find: <80><98>stan/src/stan/lang<80><99>: No such file or directory
which is due to stan directory being empty. I figured out what to do, bit it would be nice to have additional instructions reminding that you need to clone Stan, too, instead of just giving the error.

**Comment by syclik** [comment]
Good call. I need to link:
https://github.com/stan-dev/cmdstan/wiki/Getting-Started-with-CmdStan

Do you have permissions to edit the site? If so, would you mind editing it?


Daniel

**Comment by avehtari** [comment]
I don't have any permissions.

**Comment by avehtari** [comment]
fixed
