### ISSUE TITLE
Function in Stan program only compiles in stanc2

### ISSUE THREAD

**Issue by gbarz** [stan-dev/cmdstan#920]
#### Summary:
Incorporating a user-defined function which calls ceil(x) fails to compile unless compiled with stanc2

#### Description:
Perhaps it's a non-issue and instead simply due to my naivete both with Stan and C, however given compilation is successful using STANC2, I thought it was worth mentioning.

#### Reproducible Steps:
Only if the STANC2=TRUE flag is added to make/local will the program compile.

#### Expected Output:
No compiling errors

#### Additional Information:
Apologies if this item is more appropriate for STAN than CMDSTAN.

#### Current Version:
The "issue" occurs using both v2.24.1 and v2.23.0

**Comment by mitzimorris** [comment]
not sure - this might be a Stanc3 issue - will check.

**Comment by mitzimorris** [comment]
do you have a minimal example?  if so, could you post on Discourse?  https://discourse.mc-stan.org

**Comment by gbarz** [comment]
I'll try to put something simple together..

**Comment by mitzimorris** [comment]
there's a warning in the Stan functions manual, not sure whether it's relevant:  https://mc-stan.org/docs/2_24/functions-reference/step-functions.html#step-functions

**Comment by rok-cesnovar** [comment]
The following model compiles on develop: 

```
functions{
    real test(int i, real r, vector v, row_vector rv, matrix m, real[] ra) {
        real p1 = ceil(i);
        real p2 = ceil(r);
        vector[5] p3 = ceil(v);
        row_vector[5] p4 = ceil(rv);
        matrix[5,5] p5 = ceil(m);
        real rra[5] = ceil(ra);
        return 5.0;
    }
}
transformed data {
    int a1;
    real a2;
    vector[5] a3;
    row_vector[5] a4;
    matrix[5,5] a5;
    real a6[5];
    real td = test(a1, a2, a3, a4, a5, a6);
}
parameters {
    real b2;
    vector[5] b3;
    row_vector[5] b4;
    matrix[5,5] b5;
    real b6[5];
}
transformed parameters {
    real tp = test(a1, b2, b3, b4, b5, b6);
}
```
so I am guessing we can close this. Feel free to reopen if the problem persists. Please provide an example if that happens.
