### ISSUE TITLE
precompiled header optimization issue blocking compilation

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstan#932]
#### Summary:

The optimize settings in precompiled headers are blocking recompilation.  
Please provide a short couple sentence summary.

#### Description:

I compiled once, everything was fine.  Then I changed the model and tried again and got this (space inserted by me to highlight the error):

```
~/github/stan-dev/cmdstan(develop)$ mk ~/temp2/diverge2

--- Translating Stan model to C++ code ---
bin/stanc  --o=/Users/carp/temp2/diverge2.hpp /Users/carp/temp2/diverge2.stan

--- Compiling, linking C++ code ---
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2019_U8/include   -O0 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.7 -I stan/lib/stan_math/lib/boost_1.72.0 -I stan/lib/stan_math/lib/sundials_5.2.0/include    -DBOOST_DISABLE_ASSERTS        -c -include-pch stan/src/stan/model/model_header.hpp.gch -x c++ -o /Users/carp/temp2/diverge2.o /Users/carp/temp2/diverge2.hpp

error: __OPTIMIZE__ predefined macro was enabled in PCH file but is currently disabled
1 error generated.
```

#### Reproducible Steps:

Check out latest develop version of cmdstan, compile a model, change it, try to recompile it.

#### Current Output:

See above.

#### Expected Output:

Successful compilation.

#### Additional Information:

Mac OS X

#### Current Version:
v2.24.0

**Comment by wds15** [comment]
Xcode got updated a few times recently... maybe a `make clean-all` followed by `make build` and a model rebuild solves the matter?

**Comment by mitzimorris** [comment]
I just hit this error again and in this case, it was in an absolutely fresh install of CmdStan, i.e., brand new directory, no existing files anywhere:

```
> git clone https://github.com/stan-dev/cmdstan.git --recursive
> cd cmdstan
> make -j4 build
```

build OK, compilation fails:

```
> make examples/bernoulli/bernoulli

./examples/bernoulli/clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2019_U8/include   -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.7 -I stan/lib/stan_math/lib/boost_1.72.0 -I stan/lib/stan_math/lib/sundials_5.2.0/include    -DBOOST_DISABLE_ASSERTS        -c -MT stan/src/stan/model/model_header.hpp.gch -MT stan/src/stan/model/model_header.d -MM -E -MG -MP -MF stan/src/stan/model/model_header.d stan/src/stan/model/model_header.hpp
bernoclang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2019_U8/include   -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.7 -I stan/lib/stan_math/lib/boost_1.72.0 -I stan/lib/stan_math/lib/sundials_5.2.0/include    -DBOOST_DISABLE_ASSERTS        -c -MT src/cmdstan/main.o -MM -E -MG -MP -MF src/cmdstan/main.d src/cmdstan/main.cpp
u
--- Translating Stan model to C++ code ---
bin/stanc  --o=examples/bernoulli/bernoulli.hpp examples/bernoulli/bernoulli.stan
l
--- Compiling, linking C++ code ---
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2019_U8/include   -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.7 -I stan/lib/stan_math/lib/boost_1.72.0 -I stan/lib/stan_math/lib/sundials_5.2.0/include    -DBOOST_DISABLE_ASSERTS        -c -include-pch stan/src/stan/model/model_header.hpp.gch -x c++ -o examples/bernoulli/bernoulli.o examples/bernoulli/bernoulli.hpp
error: PCH file uses an older PCH format that is no longer supported
1 error generated.
```

this is a MacBook Pro - Bob set himself up on it over a year ago, but has stopped using it in favor of his new desktop machine.  there's a version of Xcode on it - probably an old one.

@wds15 - are you suggesting we require users to upgrade Xcode?  this is highly problematic.

**Comment by mitzimorris** [comment]
this is problematic:

```
 -c -include-pch stan/src/stan/model/model_header.hpp.gch
```

is there a version checked into GitHub?  why is it necessary to run `build` target twice in order to get it right?

**Comment by mitzimorris** [comment]
cannot recreate.  perhaps a ~/Library cache issue?  last time I used this machine was over a year ago.

will add error and recommendation to clean and rebuild to CmdStan docs section on troubleshooting the install.

**Comment by SteveBronder** [comment]
This line `error: PCH file uses an older PCH format that is no longer supported` + clearing out the whole directory makes me feel like it's an issue with `make clean-all`

**Comment by mitzimorris** [comment]
at the point where it failed, *there was no previous build*  - so nothing for `make clean-all` to clean.
commands prior to ones shown were to make directories `github` and `stan-dev`.

**Comment by SteveBronder** [comment]
Oh weird! Then yeah I think your `~/Library` cache idea adds up. Even odder that nothing should be touched if the optimization flag is not turned on?

**Comment by mitzimorris** [comment]
looks like Bob ran CmdStanR under 2.23.0 - there are two .gch files - `model_header_noflags.hpp.gch` and the regular.  how anything I did logged in as me would have found these is beyond me.  file under "shrug"

**Comment by wlandau** [comment]
I use a Mac and just encountered the PCH issue while trying to compile a simple model with `cmdstanr`. Reinstalling a fresh copy of `cmstan` worked for me. Guess some recent xcode updates might have invalidated the binaries as was previously mentioned.

**Comment by SteveBronder** [comment]
We should probably warn about this in the release

**Comment by mitzimorris** [comment]
added this to the CmdStan docs:

> Updates to CmdStan, changes in compiler options, or updates to the
> C++ toolchain may result in errors when trying to compile a Stan program.
> Often, these problems can be resolved by removing the existing CmdStan binaries
> and recompiling.

**Comment by mitzimorris** [comment]
definitely a bug outside of CmdStan - just updated Xcode - this error message is pretty informative:

```
error: PCH file built from a different branch ((clang-1200.0.32.2)) than the compiler ((clang-1200.0.32.21))
```

**Comment by rok-cesnovar** [comment]
Closing this, as I think it has been established that PCH errors occur with compiler upgrades. A rebuild of CmdStan addresses it typically.
