### ISSUE TITLE
`make` on develop fails - error in `stan/lib/stan_math/make/libraries`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#933]
#### Summary:
updated to latest develop, all `make` commands are failing

#### Description:
history:
```
  505  git checkout develop
  506  git pull
  507  make clean-all
  508  make stan-update
```

```
~/github/stan-dev/cmdstan (develop)> make stan-update
stan/lib/stan_math/make/libraries:108: *** "Need to set TBB_CXX_TYPE for non-standard compiler other than gcc or clang.".  Stop.
```

#### Reproducible Steps:
see above.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.24.0

**Comment by SteveBronder** [comment]
Is this for mac? Is there anything in your make/local? @wds15 can you try this when you get a minute? We can revert the optim stuff if we want to release tmrw CET

**Comment by mitzimorris** [comment]
don't have a `make/local` for cmdstan.
I checked out `develop` branch of math, and there `make clean-all` works fine, also `make clean-all` is OK for repo stan, using `develop` branch of math.  has anything in cmdstan makefile changed?

**Comment by mitzimorris** [comment]
> Is this for mac?
yes

**Comment by SteveBronder** [comment]
> has anything in cmdstan makefile changed?

Yeah so I just reverted the changes to the cmdstan makefile in #934. We were adding lto something must have goofed up

**Comment by mitzimorris** [comment]
thanks.

my bad for not paying attention to CmdStan makefiles.  those changes need some work - happy to help debug/refactor.

**Comment by mitzimorris** [comment]
checked out latest - it's working, but complains:

```
~/github/stan-dev/cmdstan (develop)> make clean-all
rm -f -r test
make: *** No rule to make target `clean-libraries', needed by `clean-all'.  Stop.
make: *** Waiting for unfinished jobs....
....
```
