### ISSUE TITLE
make/local template

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/cmdstan#942]
#### Summary:

I think it would be good to template `make/local` with options. Like how linux config files are these days. So if someone goes in there looking for stuff they see:

```
# Uncomment to enable threading
# STAN_THREADS=TRUE
```

And similarly for MPI, OpenCL, the common C++ flags, etc.

#### Current Version:
v2.25.0

**Comment by mitzimorris** [comment]
how will this work with git?   we don't want to clobber any existing `make/local` files, nor do we want folks checking them back in.  we could distribute `make/local.template`, or maybe release scripts copy `make/local.template` to `make/local` when assembling the tarball?

**Comment by mitzimorris** [comment]
related:  template file options will need clear guidance of when to turn/on off.

**Comment by bbbales2** [comment]
> how will this work with git?

Oh good point. Guess it wouldn't, so this wouldn't work

**Comment by rok-cesnovar** [comment]
We could add a local.example.
