### ISSUE TITLE
generate_quantities - more intelligent reading of CSV header file

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstan#943]
#### Summary:
Generate quantities method currently has var `hmc_fixed_cols` which expects NUTS sampler output columns.
Instead, read CSV column header names; sampler variable names end in `__` - calculate offset from this.
This will allow more inputs consisting of just parameter columns from a set of draws.

#### Description:
We want to make the use of `generate_quantities` method work in a production setting by allowing minimal CSV file which is still parse-able by Stan CSV reader, since we still need to allow full Stan CSV files as well.

#### Current Version:
v2.24.0

**Comment by WardBrian** [comment]
https://github.com/stan-dev/cmdstan/pull/1106
