### ISSUE TITLE
`--warn-pedantic` does not work when `--auto-format` is also flagged

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/cmdstan#944]
#### Description:
I'm working on a [PR](https://github.com/stan-dev/cmdstanr/pull/306) for cmdstanr and discovered that when `--auto-format` is flagged, `--warn-pedantic` appears to be ignored. 

#### Reproducible Steps:
R code (but once the stan file is created, same behaviour is observed using raw stanc in a terminal):
```r
library(cmdstanr)
model_code <- "
parameters {
  real y;
  real x;
}
model {
  y ~ std_normal();
}
"
stan_file <- write_stan_file(model_code)
mod_pedantic_warn <- cmdstan_model(stan_file, compile = FALSE)

#this works fine:
mod_pedantic_warn$check_syntax(
  stanc_options = list("warn-pedantic" = TRUE)
)

#however this doesn't show the pedantic warning
mod_pedantic_warn$check_syntax(
  stanc_options = list("warn-pedantic" = TRUE,"auto-format"=TRUE)
)
```
#### Current Version:
v2.25.0

**Comment by rok-cesnovar** [comment]
Hey Mike,

I would not necessarily mark this as a bug. When using the auto-format, you are not exactly "compiling" your model and no C++ is generated. 

We also for example have `--version` that just outputs the version and other flags are ignored.

**Comment by mike-lawrence** [comment]
Gotcha, yeah in retrospect that makes total sense.
