### ISSUE TITLE
I want to know how to install the tbb

### ISSUE THREAD

**Issue by fanzheng0352** [stan-dev/cmdstan#949]
#### Summary:

I have followed the guide to install the cdmstan for r
but i am comfused why shown this 

G:\R\pro\git\cmdstan>mingw32-make install-tbb
cmd.exe /C install-tbb.bat
Permanently setting the PATH user environment variable:

Please close this shell and open a new shell.
This will make the changes to the PATH variable
become active.

I am sure i have put the [tbb path] into envirment variable.

is samething wrong for me ?

and i can run the example "bernoulli" but i can not install tbb and i can not use r-studio to set_cmdstan_path() .

when i run the code "check_cmdstan_toolchain(fix = TRUE)" . the error show "Other C++ toolchains installed on your system conflict with RTools. Please run check_cmdstan_toolchain(fix = TRUE) to fix the issue. "

and i can not install_cmdstan(). 

so i want to get help. i have install some stan packages like bayesplot / rstan and so on .

**Comment by wds15** [comment]
You should file this onto the discourse forums. Not here. Thanks.
