### ISSUE TITLE
Release cmdstan with pre-built TBB for Windows

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstan#955]
#### Description:

We could pre-build TBB DLLs (Windows) for releases and include them in the release tarball.

What do we gain?
- mingw32-make would no longer be a requirement for those using releases (to me this is a huge bonus, at least half of Windows support issues come from missing mingw32-make). mingw32-make would still be required to build TBB for those that use cmdstan repo clones, but that is much less of a problem. Devs having to install toolchains is much less of a support issue.

What do we lose?
- we get a few MBs of heavier release tarballs

Things we need to solve:
- how to handle make clean that it won't clean up the DLL files? Probably easiest solution is to store tbb.dll as tbb_somesuffix.dll and just copy it on build. Similar to how we handle stanc3.
- cleanup make logic that stops the build with no mingw32-make 

Does anyone oppose this? The release is in ~6-7 weeks, would say we need to decide until the first week of January to do this without time pressure.

#### Current Version:
v2.25.0

**Comment by mitzimorris** [comment]
please correct my confusion - do TBB DLLs need to be recompiled if user specifies different compiler options that how TBB DLLs were compiled?

**Comment by mitzimorris** [comment]
if this is viable, I think we should have platform-specific  CmdStan releases which include pre-built binaries for all libs and programs.

**Comment by rok-cesnovar** [comment]
TBB DLLs are built using Intel supplied makefiles and they are linked in dynamiclly. they never get recompiled after the user does make build.

> we should have platform-specific CmdStan releases which include pre-built binaries for all libs and programs.

I think this is only viable on Windows. On Linux its not an option (too many different variations of linux) and with macs shipping two architectures now I dont think its worth it.

we only build tbb, sundials, stansummary, diagnose and print.

I dont think we wanr to prebuild just to save a few seconds of install time. To me that is not worth it. On Windows prebuilding tbb simplifies the installation by removing the largest pain point. That may be worth it.

**Comment by mitzimorris** [comment]
thanks for the clarification

> too many different variations of linux

Debian and RH would go pretty far, no?

so that's 2 Linux, 2 Mac, and Windows - 5 is still doable.

>  just to save a few seconds of install time.

I thought this would save at least few minutes on a Windows machine - or is all of that time taken up by buildng TBB?

**Comment by rok-cesnovar** [comment]
> Debian and RH would go pretty far, no?

Maybe, but Almost no one prebuilds for Linux and I would say that is a good sign that we should not open that can of worms. I have a fairly old Ubuntu laptop and it installs within a minute and some change.

> I thought this would save at least few minutes on a Windows machine - or is all of that time taken up by buildng TBB?

Most of it yes. But is it really a few minutes? I doubt it should be much more than two after we stopped builiding stanc2 out of the box.

**Comment by mitzimorris** [comment]
agree that Windows install is top priority.

**Comment by rok-cesnovar** [comment]
Fixing https://github.com/stan-dev/cmdstan/issues/929 would go a long way for that as well.

**Comment by mitzimorris** [comment]
strongly agree.
