### ISSUE TITLE
provide make install option (at least for GNU/Linux)

### ISSUE THREAD

**Issue by japhir** [stan-dev/cmdstan#970]
#### Summary:
I'm trying to create an [AUR](aur.archlinux.org/) PKGBUILD file to install cmdstan from my package manager and to allow other [Arch Linux](archlinux.org/) users to stay up to date. I've got the git cloning/building parts configured, but I don't understand the directory structure of the project. It would be great if the makefile provided a simple `make install` command that puts the resources in the correct locations.

#### Reproducible Steps:
Here's my work in progress PKGBUILD file:

If you save this on an arch distro, you can `makepkg -si` while in the directory. This will download/build/compress the package but I'm not sure where to put the subcomponents of the file.

```
# Maintainer: Ilja Kocken <iljakocken <at> gmail <dot> com>

pkgname=cmdstan-git
_pkgname=cmdstan
pkgver=v2.25.0.r126.g07ceb18
pkgrel=1
pkgdesc='The command line interface to Stan'
arch=('x86_64')
license=('BSD-3')
depends=()
makedepends=('git')
url="https://mc-stan.org/cmdstanr/articles/cmdstanr.html"
# https://github.com/stan-dev/cmdstan/releases/download/v2.25.0/cmdstan-2.25.0.tar.gz
source=("${pkgname%-*}::git+https://github.com/stan-dev/cmdstan.git")
sha256sums=('SKIP')
provides=('cmdstan')
conflicts=('cmdstan')

pkgver() {
    cd "$_pkgname"
    (
        set -o pipefail
        git describe --long 2> /dev/null | sed 's/\([^-]*-g\)/r\1/;s/-/./g' ||
            printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
    )
}

prepare() {
  cd "${_pkgname}"
  # this gets all the sub-directories
  make stan-update
}

build() {
  cd "${_pkgname}"
  # the -j4 option can be set in /etc/makepkg.conf 
  make build
}

package() {
  # unfortunately there is no simple make install for cmdstan
  install -dm0755 "${_pkgdir}/usr/lib/stan"
  install -dm0755 "${_pkgdir}/usr/src/stan"

  cp -a --no-preserve=ownership "${_pkgname}/lib" "${pkgdir}/usr/lib/stan"
  cp -a --no-preserve=ownership "${_pkgname}/src" "${pkgdir}/usr/src/stan"
  cp -a --no-preserve=ownership "${_pkgname}/bin" "${pkgdir}/usr/bin/"

  cd "${_pkgdir}
  install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
  install -Dm644 README.md "${pkgdir}/usr/share/doc/${pkgname}/README.md"
}
```

#### Current Output:
This installs only the `lib`, `src`, and `bin` directories, but I'm not sure if they can link to each other correctly and whether missing the root directory of the project misses essential components.

#### Expected Output:
I was hoping to put a very simple 
```
cd "${_pkgname}" 
make install
```
in the `package` function.

#### Additional Information:
Here's some more info on making AUR packages for Arch: https://wiki.archlinux.org/index.php/Arch_package_guidelines

#### Current Version:
v2.25.0

**Comment by wds15** [comment]
cmdstan has not been designed to be installed into different locations. I don't disagree with your ambitions and intentions here, but things are just not setup this way. I doubt that it would be simple to do. So maybe just stay with install things into /opt/cmdstan for now (and foreseeable future).

**Comment by japhir** [comment]
Thanks for the info. Does the cmdstan directory have to be editable? Because if so, then it's not desirable to install it in /opt because then you'd need sudo access whenever you're running anything.

**Comment by wds15** [comment]
No, it does not need to be editable once the compiler flags are set and you have build at least one model (because of the pre-compiled headers).

**Comment by japhir** [comment]
OK thanks! That means that this pkgbuild works correctly now :)

I guess I'll close the issue since it appears that it's not on the roadmap to re-structure the package to work with regular system directories.

```
# Maintainer: Ilja Kocken <iljakocken <at> gmail <dot> com>

pkgname=cmdstan-git
_pkgname=cmdstan
pkgver=v2.25.0.r126.g07ceb18
pkgrel=1
pkgdesc='The command line interface to Stan'
arch=('x86_64')
license=('BSD-3')
depends=()
makedepends=('git')
url="https://mc-stan.org/cmdstanr"
source=("${pkgname%-*}::git+https://github.com/stan-dev/cmdstan.git")
sha256sums=('SKIP')
provides=('cmdstan')
conflicts=('cmdstan')

pkgver() {
    cd "$_pkgname"
    (
        set -o pipefail
        git describe --long 2> /dev/null | sed 's/\([^-]*-g\)/r\1/;s/-/./g' ||
            printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
    )
}

prepare() {
  cd "${_pkgname}"
  make stan-update
}

build() {
  cd "${_pkgname}"
  make build
  make examples/bernoulli/bernoulli
}

package() {
  install -dm0755 "${pkgdir}/opt"
  cp -a --no-preserve=ownership "${_pkgname}" "${pkgdir}/opt"

  cd "${_pkgname}"
  install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${_pkgname}/LICENSE"
  install -Dm644 README.md "${pkgdir}/usr/share/doc/${_pkgname}/README.md"
}
```

**Comment by japhir** [comment]
Hmm it looks like perhaps it does need the permissions to be set to the user. This is the output of running a simple model:

```
This is cmdstanr version 0.3.0.9000
- Online documentation and vignettes at mc-stan.org/cmdstanr
- CmdStan path set to: /opt/cmdstan
- Use set_cmdstan_path() to change the path
Compiling Stan program...
<built-in>: fatal error: opening dependency file stan/src/stan/model/model_header_threads.d: Permission denied
compilation terminated.
Assembler messages:
Fatal error: can't create src/cmdstan/main_threads.o: Permission denied
make: *** [make/program:14: src/cmdstan/main_threads.o] Error 1
Error: An error occured during compilation! See the message above for more information.
```

**Comment by wds15** [comment]
Like I say... you need to install things and then compile a model, so

as root do:
make build
make example/bernoulli/bernoulli

then you should be able to compile as a user other models

**Comment by japhir** [comment]
I had those instructions included in the PKGBUILD file, so root already did that during the build. But while running another model it was now complaining that it didn't have permission.

**Comment by rok-cesnovar** [comment]
The first time you use threads it will bulid main_threads.o

**Comment by mitzimorris** [comment]
for the CmdStanPy and CmdStanR packages, the default location for the CmdStan install is in the user's home directory, in hidden directory `.cmdstan` and/or `.cmdstanr` (although there's an issue on CmdStanR to change to name `.cmdstan`), precisely because users typically don't have admin perms on their machine.

**Comment by japhir** [comment]
Ahh ok. Yeah in my model I did set it to run with multiple chains/cores.

Ok looks like I'm going to give up on this effort and in stead rely on the `cmdstanr::install_cmdstanr()` function.

Thanks everyone for chiming in.
