### ISSUE TITLE
cmdstan installation fails on Windows 10, tries to create directory with Windows reserved name

### ISSUE THREAD

**Issue by ianmtaylor1** [stan-dev/cmdstan#978]
#### Summary:
Installing cmdstan through cmdstanr::install_cmdstan() fails on Windows 10 with cmdstanr version 0.3.0, R version 4.0.3, and Rtools40.

#### Description:

The installation fails with the error message:

```
Error in mydir.create(name) : 
  failed to create directory ‘cmdstan-2.25.0/stan/lib/stan_math/lib/boost_1.72.0/tools/auto_index/doc/html/boost_autoindex/tut/con’
In addition: Warning message:
In dir.create(path, showWarnings = TRUE, recursive = TRUE, ...) :
  cannot create dir 'cmdstan-2.25.0\stan\lib\stan_math\lib\boost_1.72.0\tools\auto_index\doc\html\boost_autoindex\tut\con', reason 'Invalid argument'
```

The same error happens with cmdstan version 2.26.0 and 2.25.0

"con" is a reserved name in Windows, and creating any directory or file named "con" will result in an error.

#### Reproducible Steps:

1. Install R version 4.0.3
2. Install Rtools40
3. Install cmdstanr 0.3.0 from mc-stan.org repository.
4. Run cmdstanr::install_cmdstan()

To test the directory name issue generally, in cmd.exe:
```
C:\Users\myusername>mkdir con
The directory name is invalid.
```

#### Current Output:

For example, attempting to install version 2.25.0:
```
> cmdstanr::install_cmdstan(version="2.25.0")
The CmdStan toolchain is setup properly!
* Installing Cmdstan from https://github.com/stan-dev/cmdstan/releases/download/v2.25.0/cmdstan-2.25.0.tar.gz
* Download complete
* Unpacking archive...
Error in mydir.create(name) : 
  failed to create directory ‘cmdstan-2.25.0/stan/lib/stan_math/lib/boost_1.72.0/tools/auto_index/doc/html/boost_autoindex/tut/con’
In addition: Warning message:
In dir.create(path, showWarnings = TRUE, recursive = TRUE, ...) :
  cannot create dir 'cmdstan-2.25.0\stan\lib\stan_math\lib\boost_1.72.0\tools\auto_index\doc\html\boost_autoindex\tut\con', reason 'Invalid argument'
```

#### Expected Output:

cmdstan installs correctly.

#### Additional Information:

N/A

#### Current Version:
v2.26.0

**Comment by mitzimorris** [comment]
FWIW, windows reserved words:  https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN

> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

**Comment by mitzimorris** [comment]
I think this is a different problem - perhaps max filename path in windows?
the directory under `tut` should be `configure`, not `con` - here's what gets built for 2.25 on my machine:

```
/Users/mitzi/.cmdstan/cmdstan-2.25.0/stan/lib/stan_math/lib/boost_1.72.0/tools/auto_index/doc/html/boost_autoindex/tut:
  total used in directory 144 available 9763449029
  drwxr-xr-x  11 mitzi  staff    352 Oct 26 07:47 .
  drwxr-xr-x  10 mitzi  staff    320 Oct 26 07:47 ..
  -rw-r--r--   1 mitzi  staff  10511 Oct 26 07:47 add_indexes.html
  -rw-r--r--   1 mitzi  staff   5653 Oct 26 07:47 build.html
  -rw-r--r--   1 mitzi  staff   4454 Oct 26 07:47 build_docs.html
  drwxr-xr-x   4 mitzi  staff    128 Oct 26 07:47 configure
```

**Comment by rok-cesnovar** [comment]
I am not sure if the long filename either, at least not for 2.26. Removing the requirement of Boost program options has 
I tried installing cmdstan via cmdstanr on a few windows systems with paths of 150+ characters and its no longer an issue for 2.26.

@ianmtaylor1 maybe a bit silly, but can you double check that you have enough disk space?

**Comment by ianmtaylor1** [comment]
Thanks @rok-cesnovar and @mitzimorris for your help. Here are some follow-ups to your questions and observations.

1. File path length limit: the same link you posted says the limit is 260 characters, but the full path in the error message is `C:\Users\ianmt\Documents\.cmdstan\cmdstan-2.25.0\cmdstan-2.25.0\stan\lib\stan_math\lib\boost_1.72.0\tools\auto_index\doc\html\boost_autoindex\tut\con`, which is only 150 characters long. (I don't know why there are two `cmdstan-2.25.0` directories but there are.)
2. The registry key `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` is enabled on my machine, which removes the path length limit according to these Windows docs: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation
3. My disk has about 98GB free.

**Comment by mitzimorris** [comment]
from a DOS or powershell,  in directory, `C:\Users\ianmt\Documents\.cmdstan\cmdstan-2.25.0\cmdstan-2.25.0`,
can you run make - `mingw32-make -j4 build` ?

**Comment by ianmtaylor1** [comment]
mingw32-make was not in my path, so I had to specify the full executable. Initially I got this error about missing files:

```
C:\Users\ianmt\Documents\.cmdstanr\cmdstan-2.25.0\cmdstan-2.25.0>C:\rtools40\mingw64\bin\mingw32-make.exe -j4 build
INFO: Could not find files for the given pattern(s).
cp bin/windows-stanc bin/stanc
process_begin: CreateProcess(NULL, cp bin/windows-stanc bin/stanc, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make: *** [make/stanc:62: bin/stanc] Error 2
```

This made me think that `cmdstanr::install_cmdstan()` never actually finished unpacking the downloaded archive. I unpacked it manually and retried the above command, and another file not found error but for different files:

```
C:\Users\ianmt\Documents\.cmdstanr\cmdstan-2.25.0\cmdstan-2.25.0>C:\rtools40\mingw64\bin\mingw32-make.exe -j4 build
INFO: Could not find files for the given pattern(s).
cp bin/windows-stanc bin/stanc.exe
process_begin: CreateProcess(NULL, cp bin/windows-stanc bin/stanc.exe, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make: *** [make/stanc:62: bin/stanc.exe] Error 2
```

As far as I can tell, `bin/windows-stanc` definitely exists though.

But this makes me think: could the problem be with a file path limit, not in Windows itself, but in R while attempting to unpack the archive?

**Comment by ianmtaylor1** [comment]
Update:

The file `mingw32-make` couldn't find was `cp`, not `bin/windows-stanc`. The executable for `cp` is in `C:\rtools40\usr\bin\cp.exe`. This is added to my PATH in `.Renviron`, so the build may work through R even though it doesn't work from cmd.exe.

So in R, after unpacking the archive manually, I ran `cmdstanr::rebuild_cmdstan()`, and that appears to have worked.

Based on this, I think this may be an issue unpacking the archive in cmdstanr 0.3.0, not an issue with cmdstan itself.

**Comment by rok-cesnovar** [comment]
Run `cmdstanr::check_cmdstan_toolchain(fix = TRUE)` to add the necessary paths for cmdstan(r) and it should work (that adds the path to cp.exe) from R.

For outside of R add `C:\rtools40\usr\bin\` to PATH on Windows.

**Comment by be-green** [comment]
I had the same issue, and it also required manual edits to my path and, separately, manual unzipping of the tar.gz file to work properly. `cmdstanr::check_cmdstan_toolchain(fix = TRUE)` did not fix the issue, it seemed like the archive wasn't fully extracted by the download process.

**Comment by Luis188141** [comment]
I am confronting the same errors as follows.
Is there anyone who can help me or shares some possible sulutions?
 
The C++ toolchain required for CmdStan is setup properly!
* Latest CmdStan release is v2.31.0
* Installing CmdStan v2.31.0 in D:/????/.cmdstan/cmdstan-2.31.0
* Downloading cmdstan-2.31.0.tar.gz from GitHub...
Error: Download of CmdStan failed. Please try again.
In addition: Warning message:
In dir.create(dir, recursive = TRUE) :
  cannot create dir 'D:\????', reason 'Invalid argument'
