### ISSUE TITLE
Warnings when compiling .stan file

### ISSUE THREAD

**Issue by juandiazmart** [stan-dev/cmdstan#983]
#### Summary:
I was trying to compile a .stan file in cmdstan and got these warnings

`/home/juandiaz/covid19_epi/Mexico/code/stan-models/base_reduce_sum3.hpp:1555:49: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
                 (((1 - pow(weekly_rho, 2)) - pow(weekly_rho1, 2)) -
                                                 ^
In file included from /cvmfs/soft.computecanada.ca/nix/store/59wpzavgpf1syqd6zzgc385qkm0qrd35-glibc-2.24-dev/include/features.h:368:0,
                 from /cvmfs/soft.computecanada.ca/nix/store/m64vdgyzr1d29j8372iibl2m3ixg2f0d-gfortran-5.4.0/include/c++/5.4.0/x86_64-unknown-linux-gnu/bits/os_defines.h:39,
                 from /cvmfs/soft.computecanada.ca/nix/store/m64vdgyzr1d29j8372iibl2m3ixg2f0d-gfortran-5.4.0/include/c++/5.4.0/x86_64-unknown-linux-gnu/bits/c++config.h:482,
                 from /cvmfs/soft.computecanada.ca/nix/store/m64vdgyzr1d29j8372iibl2m3ixg2f0d-gfortran-5.4.0/include/c++/5.4.0/new:39,
                 from stan/lib/stan_math/lib/eigen_3.3.9/Eigen/Core:82,
                 from stan/lib/stan_math/lib/eigen_3.3.9/Eigen/Dense:1,
                 from stan/lib/stan_math/stan/math/prim/fun/Eigen.hpp:22,
                 from stan/lib/stan_math/stan/math/rev.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:19,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /home/juandiaz/covid19_epi/Mexico/code/stan-models/base_reduce_sum3.hpp:3:
/cvmfs/soft.computecanada.ca/nix/store/59wpzavgpf1syqd6zzgc385qkm0qrd35-glibc-2.24-dev/include/bits/mathcalls.h:153:1: note: candidate 1: double pow(double, double)
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
 ^
In file included from stan/lib/stan_math/stan/math/rev/fun/inc_beta.hpp:6:0,
                 from stan/lib/stan_math/stan/math/rev/fun/grad_inc_beta.hpp:11,
                 from stan/lib/stan_math/stan/math/rev/fun.hpp:74,
                 from stan/lib/stan_math/stan/math/rev.hpp:10,
                 from stan/lib/stan_math/stan/math.hpp:19,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /home/juandiaz/covid19_epi/Mexico/code/stan-models/base_reduce_sum3.hpp:3:
stan/lib/stan_math/stan/math/rev/fun/pow.hpp:242:26: note: candidate 2: std::complex<stan::math::var_value<double> > stan::math::pow(const std::complex<stan::math::var_value<double> >&, T) [with T = int; <template-parameter-1-2> = void]
 inline std::complex<var> pow(const std::complex<var>& x, T y) {`

The file was successfully compiled but I am not sure if I should be worried about these warnings

#### Current Version:
v2.25.0

**Comment by rok-cesnovar** [comment]
If the model successfully compiled you have no reason to worry and I am going to close the issue. 

Could you provide a bit more detail so we can look at ways to remove the warning? 

Primarily the OS version and the output of `g++ --version`.
