### ISSUE TITLE
stansummary in 2.26 changes first line of output

### ISSUE THREAD

**Issue by adamConnerSax** [stan-dev/cmdstan#988]
#### Summary:
In CmdStan v2.26.1 the stan summary executable behaves differently than previous versions (at least 2.24 and 2.25) in that it drops the first line of output, the one saying "input files: ..."

This presents a potential problem for software which parses the summary file.  This change is easy to work around.  But perhaps going forward, such changes could be mentioned in the release notes?  Especially ones which change the structure of the summary in any more substantive way.

#### Current Version:
v2.26.0

**Comment by mitzimorris** [comment]
this was introduced in PR https://github.com/stan-dev/cmdstan/pull/965/files# - lines 100-108 of `stansummary.cpp` were removed.  will look into putting them back.

**Comment by adamConnerSax** [comment]
Thanks! I don't have strong feelings about them being in or not--I modified the parser to deal with it either way.  It would be nice to have a heads up when the format is changing.

**Comment by mitzimorris** [comment]
OK, then won't change this back.
regarding "heads up" - would advertising this via GitHub issues be sufficient?

**Comment by adamConnerSax** [comment]
I think so! Is it too small a thing to put in the release notes?  I could understand that.  

But yes, if it was flagged in the issues with a title that included "summary format" or something standard so it could be easily searched, that would be helpful.

**Comment by mitzimorris** [comment]
noted - for future releases, will provide issues and flag changes in the release notes.
